### ISSUE TITLE
Validation fails if componentSpecs.metadata.creationTimestamp is not specified

### ISSUE THREAD

**Issue by kparaju** [SeldonIO/seldon-core#1061]
Seldon version: v0.5

If creationTimestamp is not in componentSpecs.metadata, validation fails and k8s fails to apply the changes.

```
kubectl failed exit status 1: The SeldonDeployment "exp-ta-sort-products" is invalid: []: Invalid value: map[string]interface  validation failure list:
(...........)
spec.predictors.componentSpecs.metadata.creationTimestamp in body must be of type string: "null"
```

To fix, we need to add metadata.creationTimestamp:

```
spec:
  name: exp-ta-sort-products
  predictors:
    - annotations:
        seldon.io/no-engine: "true"
      componentSpecs:
        - metadata:
            creationTimestamp: "2019-11-05T19:29:12Z"
          spec:
            containers:
              - env:
                  - name: API_TYPE
                    value: REST
                  - name: GUNICORN_WORKERS
                    value: "2"
```
