### ISSUE TITLE
Cannot create a SeldonDeployment having volumes of type projected and configMap.

### ISSUE THREAD

**Issue by sumeetgajjar** [SeldonIO/seldon-core#1072]
Seldon version: v0.4.1

If SeldonDeployment is created with volumes of type `projected` and `configMap` it fails stating the following message

`kubectl failed exit status 1: Error from server (InternalError): Internal error occurred: Internal error occurred: Unable to access invalid index: 2`

In order to reproduce the error use the following yaml
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: bug-demo
  name: bug-demo
spec:
  name: bug-demo
  predictors:
  - componentSpecs:
    - spec:
        volumes:
          - downwardAPI:
              defaultMode: 420
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.annotations
                  path: annotations
            name: podinfo
          - configMap:
              name: site-config
            name: site-config-volume
          - projected:
              sources:
                - configMap:
                    name: site-config
                    items:
                      - key: SITE_CONFIG
                        path: site_config
            name: site-config-projected-volume
        containers:
        - image: bug-demo-image
          imagePullPolicy: IfNotPresent # IfNotPresent or Always
          name: classifier
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: main
    replicas: 1
```
