### ISSUE TITLE
How to pass ModelInitializerContainerImage  path

### ISSUE THREAD

**Issue by hemantha-kumara** [SeldonIO/seldon-core#1116]
We have deployed seldoncore on-premise where gcr.io docker registy is not reachable. due to gcr.io is not reachable, we are getting imagepullbackoff error. is there anyway we can pass dockerimage to ModelInitializerContainerImage   ?

**Comment by axsaucedo** [comment]
You can upload the image into the node's docker daemon, but this is something beyond the scope to seldon core. There are quite a lot of resources that could guide you to do this online

**Comment by hemantha-kumara** [comment]
@axsaucedo  I am asking is there anyway we can specify init docker image?  by deafult initcontianer is trying to pull image gcr.io/kfserving/model-initializer but where as my node is not able ot pull image from outside. hence I am asking is there anyway we can specify docker image to initcontainer? 

```
apiVersion: "machinelearning.seldon.io/v1alpha2"
kind: "SeldonDeployment"
metadata:
  name: "xgboost"
spec:
  name: "iris"
  predictors:
  - graph:
      children: []
      implementation: XGBOOST_SERVER
      modelUri: pvc://seldon/xgboost_model/model.bst
      name: classifier
    name: default
    replicas: 1

```
