### ISSUE TITLE
Engine using separate pod, ignoring annotations

### ISSUE THREAD

**Issue by mwm5945** [SeldonIO/seldon-core#1120]
After upgrading to 0.4.0 with Istio, the seldon deployment appears to be ignoring the `engine-seperate-pod` annotation. In the previous version (0.3.2 with ambassador) that we were using, setting this to `false` would have the service orchestrator and the model in the same pod. However, the same deployment in 0.4.0 results in separate pods. This also affects Horizontal pod autoscaling in the SDEP, as the HPA only applys to one of the deployments. 

``` yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  annotations:
  labels:
    app: seldon
  name: test-model-1
  namespace: <NS>
spec:
  annotations:
    deployment_version: "1"
    project_name: test model Prediction
    seldon.io/engine-java-opts: -XX:+UseG1GC
    seldon.io/engine-separate-pod: "false"
    seldon.io/grpc-read-timeout: "100000"
    seldon.io/rest-connection-timeout: "100000"
    seldon.io/rest-read-timeout: "100000"
  name: test-model-1
  predictors:
  - annotations:
      maas_model_name: test-model
      maas_model_version: "1"
    componentSpecs:
    - spec:
        containers:
        - env:
          - name: HTTP_PROXY
            value: <PROXY>
          - name: HTTPS_PROXY
            value: <PROXY>
          - name: http_proxy
            value: <PROXY>
          - name: https_proxy
            value: <PROXY>
          - name: NO_PROXY
            value: 127.0.0.1
          image: <IMAGE_URL>
          imagePullPolicy: Always
          name: test-model
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: 100m
              memory: 1Gi
        terminationGracePeriodSeconds: 20
    graph:
      children: []
      endpoint:
        type: REST
      name: test-model
      type: MODEL
    labels:
      model_name: test model
      model_version: "1"
      predictor_version: "1"
      version: test-model
    name: test-model
    replicas: 10
    svcOrchSpec:
      resources:
        limits:
          cpu: "2"
          memory: 3Gi
        requests:
          cpu: 201m
          memory: 1Gi
``` 
yields the following deployment: 
``` shell
NAME                                                 READY   STATUS              RESTARTS   AGE
test-model-1-test-model-a8fc82d-6464bd686c-hm4m9    2/2     Running             0          24m
test-model-1-test-model-a8fc82d-6464bd686c-w9zkr    2/2     Running             0          24m
test-model-1-test-model-svc-orch-84e689e-79bm26rf   2/2     Running             0          24m
test-model-1-test-model-svc-orch-84e689e-79brdvvz   2/2     Running             0          24m
```

Any insights would be greatly appreciated! Thanks!
