### ISSUE TITLE
Can we attach pvc to model-initializer(storage-initializer) ?

### ISSUE THREAD

**Issue by hemantha-kumara** [SeldonIO/seldon-core#1146]
Hi,
I am trying to run XGBOOST_SERVER serving by using model present in pv 

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: xgboost
spec:
  name: iris
  predictors:
  - graph:
      children: []
      implementation: XGBOOST_SERVER
      modelUri: file://seldon-models/xgboost/iris
      name: classifier
    name: default
    replicas: 1 
```

but problem is I am not able to attach pvc to model-initializer and hence model is not accesible to storage-initializer. 
Due to mentioned problem i am not able to serve models.

can anyone pls help me to attach pvc to init container?
