### ISSUE TITLE
Unschedulable: pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by kenhglee** [SeldonIO/seldon-core#1191]
Hello Seldon team!

I know this may be more of a Kubernetes issue than that of Seldon, but I must say I am still counting on you because I haven't still recovered from the last crash that we had with the [end-to-end kubeflow-seldon flow](https://github.com/SeldonIO/seldon-core/tree/master/examples/kubeflow) that relies on ksonnet that appears increasingly incomplete. 

The apparent symptom is that I am hitting the above mentioned error at the "data-downloader" phase,

![pvcissue](https://user-images.githubusercontent.com/11827065/70199728-48913400-16c7-11ea-957d-b92bdc2346ee.jpg)

, but the exact error message that pops up by describing the resulting pvc is,
```
Name:          nlp-xqvl5-my-pvc
Namespace:     kubeflow
StorageClass:  standard
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    nlp-xqvl5-4142835798
Events:
  Type     Reason              Age                  From                         Message
  ----     ------              ----                 ----                         -------
  Warning  ProvisioningFailed  93s (x68 over 137m)  persistentvolume-controller  Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported
```

Realizing that I should either change the AccessMode of StorageClass or the dynamic pvc to comply, I tried with the former to which I thought I had control by applying

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc 
spec:
  accessModes:
    - 'ReadWriteOnce'
  storageClassName: slow
  resources:
    requests:
      storage: '10Gi'
```
and changing the default storage class to the above, but it didn't really help giving me the exact same error message. 

Could there be any suggestion at this point, how I could get around with this error? Thank you in advance!

Regards, Ken
