### ISSUE TITLE
hpa cannot work

### ISSUE THREAD

**Issue by andrewshaoyu** [SeldonIO/seldon-core#1310]
kubernetes version 1.13.2
seldon-core version 1.0.0

1. create seldondeployment with hpa, set min=3,max=4
1. find that only one pod left
1. from k8s controller manager log, I found hpa controller add two pods to match the min replicas
1. but the added two pod will be delete soon
1. finally, i find the problem. during reconciling, I find that the equality.Semantic.DeepEqual
the found.spec.template.spec has `"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\" ` but deploy didnot have. then seldon-operator update the deployment with replicas 1.

**Comment by cliveseldon** [comment]
Can you modify a simple example that shows the issue? For example on the slack channel I posted a Seldon Deployment with pre/post transformers. 

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: feeds-sort
  namespace: seldon
spec:
  annotations:
    seldon.io/engine-separate-pod: "true"
  name: feeds-sort
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/identity_model_rest:0.1
          name: preprocessor
          ports:
          - name: http
            containerPort: 9000
            protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
      metadata:
        name: v1-preprocessor
    - spec:
        containers:
        - image: seldonio/identity_model_rest:0.1
          name: predicter
          ports:
          - name: http
            containerPort: 5000
            protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 4Gi
      metadata:
        name: v1-predictor
    - spec:
        containers:
        - image: seldonio/identity_model_rest:0.1
          name: postprocessor
          ports:
          - name: http
            containerPort: 9000
            protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
      metadata:
        name: v1-postprocessor
    graph:
      children:
      - endpoint:
          type: REST
        implementation: UNKNOWN_IMPLEMENTATION
        name: preprocessor
        type: TRANSFORMER
        children:
        - endpoint:
            type: REST
          implementation: UNKNOWN_IMPLEMENTATION
          name: predicter
          type: MODEL
          children: []
      endpoint:
        type: REST
      implementation: UNKNOWN_IMPLEMENTATION
      name: postprocessor
      type: OUTPUT_TRANSFORMER
    labels:
      version: v1
    name: v1
    replicas: 1
    svcOrchSpec:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
```

Do we need these for  your issue or does it happen on a more simple SeldomDeployment?
