### ISSUE TITLE
How to craft an ambassador-config override with shadow mode

### ISSUE THREAD

**Issue by zcharli** [SeldonIO/seldon-core#1347]
Hello, I'm currently trying to experiment with some retry policies which I figured the override method provides a good balance of flexibility to mirror the same deployment's traffic patterns and observe changes. I'm having some trouble crafting the right ambassador-config to make the shadow work. 

I have two seldon deployments called `main_model` and `shadow_main_model` and my config currently looks like this:
```
spec:
  annotations:
    seldon.io/ambassador-config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: shadow_main_model-amba_model_rest_mapping
      prefix: /seldon/my-namespace/main_model
      service: shadow_main_model-shadow_main_model-model.my-namespace:8000
      timeout_ms: 300
      weight: 100
      retry_policy:
        retry_on: connect-failure
        num_retries: 0
      shadow: true
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: shadow_main_model-amba_model_grpc_mapping
      grpc: true
      prefix: /seldon.protos.Seldon
      rewrite: /seldon.protos.Seldon
      service: shadow_main_model-shadow_main_model-model.my-namespace:5001
      timeout_ms: 300
      weight: 100
      headers:
        namespace: my-namespace
        seldon: main_model
      retry_policy:
        retry_on: connect-failure
        num_retries: 0
      shadow: true
```
The example above is based on the ambassador configs generated by setting https://docs.seldon.io/projects/seldon-core/en/latest/examples/ambassador_shadow.html. Although it's not quite right, there are several differences:
- The auto generated configs have a service name made from a seldon hash for example `seldon-562061dc7798a30d44047a6d3d2df14b.my-namespace:5001` 
- There are two ambassador mappings for the shadow model under the `Ambassador Diagnostics` tool. Seems to be one for my shadow and one for the main.

So I'm currently stuck and reach out for any expertise in crafting these settings for my seldon deployment.
