### ISSUE TITLE
v1.0.0 Seldon operator crashes when fail to deploy sdep. 

### ISSUE THREAD

**Issue by yufengshan** [SeldonIO/seldon-core#1385]
Operator container in crash loop status when trying to create a Seldon deployment fails. The right behavior would be just logging an error when can not create a Seldon deployment without crashing.  Here is the crash log:

```2020-01-30T16:09:51.093Z	INFO	controllers.SeldonDeployment	Reconcile called	{"SeldonDeployment": "dspe-seldon/moduko-diversity-airport"}
2020-01-30T16:09:51.093Z	INFO	controllers.SeldonDeployment	pSvcName	{"SeldonDeployment": "dspe-seldon/moduko-diversity-airport", "val": "moduko-diversity-airport-moduko-diversity-airport-main"}
2020-01-30T16:09:51.093Z	INFO	controllers.SeldonDeployment	Not creating container service for classifier	{"SeldonDeployment": "dspe-seldon/moduko-diversity-airport"}
2020-01-30T16:09:51.093Z	INFO	controllers.SeldonDeployment	Not creating container service for scribe	{"SeldonDeployment": "dspe-seldon/moduko-diversity-airport"}
2020-01-30T16:09:51.093Z	INFO	controllers.SeldonDeployment	Not creating container service for diversity	{"SeldonDeployment": "dspe-seldon/moduko-diversity-airport"}
2020-01-30T16:09:51.093Z	INFO	controllers.SeldonDeployment	Not creating container service for airport-transfer	{"SeldonDeployment": "dspe-seldon/moduko-diversity-airport"}
E0130 16:09:51.093593       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:76
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:65
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/workspace/controllers/seldondeployment_prepackaged_servers.go:255
/workspace/controllers/seldondeployment_prepackaged_servers.go:255
/workspace/controllers/seldondeployment_controller.go:452
/workspace/controllers/seldondeployment_controller.go:1346
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11ccceb]

goroutine 217 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1321b60, 0x21e6950)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/seldonio/seldon-core/operator/apis/machinelearning/v1.IsPrepack(...)
	/workspace/apis/machinelearning/v1/seldondeployment_webhook.go:125
github.com/seldonio/seldon-core/operator/controllers.createStandaloneModelServers(0xc000364900, 0xc000142ea0, 0xc00036fd40, 0xc0008bc680, 0xc001302000, 0xc0002541c8, 0x0)
	/workspace/controllers/seldondeployment_prepackaged_servers.go:255 +0x1cb
github.com/seldonio/seldon-core/operator/controllers.createComponents(0xc000364900, 0xc000142ea0, 0x16aff00, 0xc00068e360, 0x22197a0, 0xc00048c0a0, 0xb)
	/workspace/controllers/seldondeployment_controller.go:452 +0x15a4
github.com/seldonio/seldon-core/operator/controllers.(*SeldonDeploymentReconciler).Reconcile(0xc000364900, 0xc00048c0a0, 0xb, 0xc000359040, 0x18, 0x21fad20, 0x42bd21, 0x16838a0, 0xc001e27d88)
	/workspace/controllers/seldondeployment_controller.go:1346 +0x4ae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004e40a0, 0x136cca0, 0xc00058e3a0, 0x136cc00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216 +0x149
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004e40a0, 0xc000ab2200)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192 +0xb5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0004e40a0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00148e0c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00148e0c0, 0x3b9aca00, 0x0, 0x458e01, 0xc0003664e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00148e0c0, 0x3b9aca00, 0xc0003664e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:157 +0x311

```

**Comment by kparaju** [comment]
Here is the YAML to cause the crash. The only thing you will have to change in the namespace.

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: my-app
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: seldon-namespace
  name: my-app
  namespace: seldon-namespace
spec:
  name: my-app
  predictors:
    - componentSpecs:
        - metadata:
            creationTimestamp: '2019-11-05T19:29:12Z'
          spec:
            containers:
              - env:
                  - name: API_TYPE
                    value: REST
                  - name: TA_ML_SERVICE_IN_SELDON
                    value: '1'
                  - name: GUNICORN_WORKERS
                    value: '2'
                  - name: GUNICORN_MAX_REQUESTS
                    value: '0'
                image: >-
                  docker-image-path/docker-image:v1
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /seldon.json
                    port: http
                    scheme: HTTP
                  initialDelaySeconds: 60
                  periodSeconds: 5
                  successThreshold: 1
                  timeoutSeconds: 1
                name: classifier
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /seldon.json
                    port: http
                    scheme: HTTP
                  initialDelaySeconds: 20
                  periodSeconds: 5
                  successThreshold: 1
                  timeoutSeconds: 1
                resources:
                  limits:
                    cpu: 2000m
                    memory: 4Gi
                  requests:
                    cpu: 1000m
                    memory: 2Gi
                volumeMounts:
                  - mountPath: /etc/podinfo
                    name: podinfo
              - args:
                  - '--argname'
                  - 'argvalue'
                env:
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.name
                  - name: SELDON_DEPLOYMENT_ID
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: 'metadata.labels[''seldon-deployment-id'']'
                image: >-
                  docker-image-path/sidecar:v1
                imagePullPolicy: IfNotPresent
                lifecycle:
                  preStop:
                    exec:
                      command:
                        - /bin/sleep
                        - '15'
                name: scribe
                ports:
                  - containerPort: 1818
                    name: probe-port
                    protocol: TCP
                  - containerPort: 1919
                    protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 300Mi
                  requests:
                    cpu: 500m
                    memory: 300Mi
                securityContext:
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
                  runAsUser: 99
                volumeMounts:
                  - mountPath: /tmp
                    name: tmpdir-rw
                  - mountPath: /etc/sysconfig
                    name: config-and-secrets
                    readOnly: true
                  - mountPath: /var/log/scribe
                    name: another-tmpdir-rw
                  - mountPath: /etc/myapp/another-tmpdir-rw
                    name: application-configs-rw
                  - mountPath: /etc/certs
                    name: config-and-secrets
                    readOnly: true
              - env:
                  - name: API_TYPE
                    value: REST
                  - name: TA_ML_SERVICE_IN_SELDON
                    value: '1'
                  - name: GUNICORN_WORKERS
                    value: '2'
                  - name: GUNICORN_MAX_REQUESTS
                    value: '0'
                  - name: OMP_NUM_THREADS
                    value: '2'
                  - name: LOAD_CONFIG_FROM_K8S_CONFIG
                    value: '0'
                image: >-
                  docker-image-path/docker-image-name:v1
                imagePullPolicy: IfNotPresent
                name: first-transform
                resources:
                  limits:
                    cpu: 2000m
                    memory: 2Gi
                  requests:
                    cpu: 2000m
                    memory: 1Gi
              - env:
                  - name: API_TYPE
                    value: REST
                  - name: TA_ML_SERVICE_IN_SELDON
                    value: '1'
                  - name: GUNICORN_WORKERS
                    value: '2'
                  - name: GUNICORN_MAX_REQUESTS
                    value: '0'
                image: >-
                  docker-host/docker/image/path:v1
                imagePullPolicy: IfNotPresent
                name: second-transform
                resources:
                  limits:
                    cpu: 1000m
                    memory: 2Gi
                  requests:
                    cpu: 1000m
                    memory: 1Gi

            initContainers: []
            volumes:
              - downwardAPI:
                  defaultMode: 420
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.annotations
                      path: annotations
                name: podinfo
              - emptyDir:
                  medium: Memory
                name: tmpdir-rw
              - emptyDir:
                  medium: Memory
                name: another-tmpdir-rw
              - emptyDir:
                  medium: Memory
                name: application-configs-rw
              - name: config-and-secrets
                projected:
                  defaultMode: 420
                  sources:
                    - secret:
                        items:
                          - key: namespace.key
                            path: client.key
                        name: namespace-certificate
                    - configMap:
                        items:
                          - key: SITE_CONFIG
                            path: site_config
                        name: another-tmpdir-rw
      graph:
        endpoint:
          type: REST
        name: second-transform
        type: OUTPUT_TRANSFORMER
        children:
          - name: first-transform
            type: OUTPUT_TRANSFORMER
            endpoint:
              type: REST
            children:
              - name: classifier
                type: MODEL
                endpoint:
                  type: REST
      labels:
        version: main
      name: main
      replicas: 2
      svcOrchSpec:
        env:
          - name: JAVA_OPTS
            value: >-
              -server -Xms512m -Xmx512m -XX:+AlwaysPreTouch
              -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20
              -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:GCLogFileSize=10485760
              -XX:NumberOfGCLogFiles=1 -XX:+PrintGC
              -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps
              -XX:+PrintGCDetails -XX:+PrintGCTimeStamps
              -XX:+PrintTenuringDistribution -XX:+UseGCLogFileRotation
              -Xloggc:/tmp/gc.log -XX:+UseTLAB -XX:+DisableExplicitGC
          - name: SELDON_LOG_LEVEL
            value: INFO
        resources:
          limits:
            cpu: 4000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi

```

**Comment by cliveseldon** [comment]
Is this happening for just this deployment? Can you confirm the webhook is still active? Also, you have only a single operator installed nothing more advanced?

**Comment by cliveseldon** [comment]
can you also confirm this simple deployment gets created (which is of a similar structure)?
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: my-app
  namespace: seldon
spec:
  name: my-app
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - image: seldonio/mock_classifier_rest:1.3
                name: first-transform
              - image: seldonio/mock_classifier_rest:1.3
                name: second-transform
              - image: seldonio/mock_classifier_rest:1.3
                name: classifier
      graph:
        endpoint:
          type: REST
        name: second-transform
        type: OUTPUT_TRANSFORMER
        children:
          - name: first-transform
            type: OUTPUT_TRANSFORMER
            endpoint:
              type: REST
            children:
              - name: classifier
                type: MODEL
                endpoint:
                  type: REST
      name: main
      replicas: 1
```
