### ISSUE TITLE
new v1.0.0 CRD's resources validator is not backward compatible 

### ISSUE THREAD

**Issue by yufengshan** [SeldonIO/seldon-core#1410]
After upgraded to seldon v1.0.0 (with latest CRD) from v0.51/v0.4. The operator report error as below. It seems the new CRD has stricter validation requirement in the sdep resources section. With the following changes, operator can successfully deploy the sdep. 

```       resources:
         limits:
-          cpu: 4
+          cpu: "4"
           memory: 4Gi
         requests:
-          cpu: 1
+          cpu: "1"
```

This breaks the backward compatibility, engineers have to update their sdeps. Can someone take a look to make it backward compatible? Thanks. 

============ error ==============
```validation failure list:\nspec.predictors.svcOrchSpec.resources.limits.cpu in body must be of type string: \"integer\"\nspec
.predictors.componentSpecs.spec.containers.resources.limits.cpu in body must be of type string: \"integer\"\nspec.predictors.componentSpecs.spec.containers.resources.requests.cpu in body must be of t
ype string: \"integer\""}                                                                                                                                                                              
github.com/go-logr/zapr.(*zapLogger).Error                                                                                                                                                             
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128                                                                                                                                         
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler                                                                                                                  
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:218                                                                                                    
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem                                                                                                               
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192                                                                                                    
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker                                                                                                                            
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171                                                                                                    
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1                                                                                                                                                    
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152                                                                                                   
k8s.io/apimachinery/pkg/util/wait.JitterUntil                                                                                                                                                          
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153                                                                                                   
k8s.io/apimachinery/pkg/util/wait.Until                                                                                                                                                                
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88 ```

**Comment by cliveseldon** [comment]
The OpenAPISchema spec is generated automatically by Kubebuilder which generates the CRD yaml from the golang spec. The actual value is meant to be a string : see https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/

However, I agree kubectl allows one to use integers.

**Comment by cliveseldon** [comment]
The value is a Quantity which is meant to be a string: see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#quantity-resource-core 
`When a Quantity is parsed from a string...`

However, kubectl does allow integer for values of this and seems to parse them to Quantities.

**Comment by cliveseldon** [comment]
I agree this is a braking change but I think it may be hard to implement the kubectl functionality which is above and beyond what CRDs provide without some hacks to the OpenAPISchema which is as stated generated.

We could update the docs FAQs for this?

**Comment by cliveseldon** [comment]
This works with the current master code on 1.16. Please reopen if still an issue.
Tested with:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 2
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: example
    replicas: 1

```
