### ISSUE TITLE
Seldon controller crashes when submitting deployer

### ISSUE THREAD

**Issue by jamborta** [SeldonIO/seldon-core#1418]
I'm using Seldon installed with Kubeflow 7.0

I submit the following:
```yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: my-app
  namespace: seldon
spec:
  name: my-app
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - image: seldonio/mock_classifier_rest:1.3
                name: first-transform
              - image: seldonio/mock_classifier_rest:1.3
                name: second-transform
              - image: seldonio/mock_classifier_rest:1.3
                name: classifier
      graph:
        endpoint:
          type: REST
        name: second-transform
        type: OUTPUT_TRANSFORMER
        children:
          - name: first-transform
            type: OUTPUT_TRANSFORMER
            endpoint:
              type: REST
            children:
              - name: classifier
                type: MODEL
                endpoint:
                  type: REST
      name: main
      replicas: 1
```

Which causes the controller to crash:

```
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfc1f20]

goroutine 226 [running]:
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1149620, 0x1b88eb0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/seldonio/seldon-operator/pkg/controller/seldondeployment.addModelDefaultServers(0xc42000a440, 0xc420454cf0, 0xc4201a0fc0, 0xc42010e480, 0xc4200cacd0, 0x1)
	/go/src/github.com/seldonio/seldon-operator/pkg/controller/seldondeployment/seldondeployment_prepackaged_servers.go:110 +0x40
github.com/seldonio/seldon-operator/pkg/controller/seldondeployment.createStandaloneModelServers(0xc42000a440, 0xc420c041a0, 0xc4201a0fc0, 0xc420832480, 0xc420454cf0, 0xc4200cad08, 0x0)
	/go/src/github.com/seldonio/seldon-operator/pkg/controller/seldondeployment/seldondeployment_prepackaged_servers.go:273 +0x1bf
github.com/seldonio/seldon-operator/pkg/controller/seldondeployment.createComponents(0xc42000a440, 0xc420c041a0, 0xc4200460f0, 0xc4208ed9c0, 0x8)
	/go/src/github.com/seldonio/seldon-operator/pkg/controller/seldondeployment/seldondeployment_controller.go:437 +0xa9c
github.com/seldonio/seldon-operator/pkg/controller/seldondeployment.(*ReconcileSeldonDeployment).Reconcile(0xc42000a440, 0xc4208ed9c0, 0x8, 0xc4208ed9a0, 0x6, 0x1b9c040, 0x3, 0x3, 0x0)
	/go/src/github.com/seldonio/seldon-operator/pkg/controller/seldondeployment/seldondeployment_controller.go:1169 +0x17b
github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc42016f2c0, 0x0)
	/go/src/github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x188
github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42087ebd0)
	/go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42087ebd0, 0x3b9aca00, 0x0, 0x20001, 0xc420318660)
	/go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42087ebd0, 0x3b9aca00, 0xc420318660)
	/go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x35b
```

First I though it is related to #1385, but this version does not have multiple configurations in the webhook config.
