### ISSUE TITLE
OSS-34: Internal traffic routing architecture

### ISSUE THREAD

**Issue by groszewn** [SeldonIO/seldon-core#1472]
Currently, istio-enabled Seldon installations work by leveraging an already installed istio-ingressgateway and expects a gateway to be supplied for the Seldon namespace.  A diagram showing the traffic pattern for weighted routing with this pattern can be seen below.

![](https://user-images.githubusercontent.com/13921855/74967075-4b5a1600-53e6-11ea-9e69-dc1119e344df.png)

*N.B. `VirtualServices` are not actually DNS entries that can be routed to directly, this diagram includes them only for the sake of clarity of how the traffic routing is being handled*

As can be seen, the first actual component that has a DNS entry before the weighted routing is handled is the istio-ingressgateway `Service`.  When traffic is generated from inside the cluster, this introduces an extra network hop.  From my understanding, this is a byproduct of the way that `VirtualServices` are leveraged for weighted routing.  An example that closely resembles what would be deployed with the above setup can be seen below.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: canary-canary-example-grpc
  namespace: seldon-system
spec:
  gateways:
  - seldon-gateway
  hosts:
  - '*'
  http:
  - match:
    - headers:
        namespace:
          exact: seldon-system
        seldon:
          exact: canary-example
      uri:
        prefix: /seldon.protos.Seldon/
    route:
    - destination:
        host: canary-example-canary-v1-predictor
        port:
          number: 5001
        subset: v1-predictor
      weight: 75
    - destination:
        host: canary-example-canary-v2-predictor
        port:
          number: 5001
        subset: v2-predictor
      weight: 25
```

Each model in the canary deployment gets its own `Service` and a corresponding `DestinationRule` to route traffic to the specific model based on metadata passed in the request.  Each model endpoint can still be reached directly by using the specific model's `Service`, but any weighted routing/shadow scoring would need to route traffic through the `istio-ingressgateway` for it to work.

One potential solution to this problem would be to have a single `Service` shared between the different models and have a `VirtualService`/`DestinationRule` applied at that level to handle weighted routing, as opposed to splitting the traffic at the `Gateway`.  Changing this implementation could potentially have cascading events, so I'd love to hear any other thoughts/suggestions.
