### ISSUE TITLE
executor: tags do not propagate through inference graph

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1474]
For example, same requests with `engine`
```json
curl -X POST -H 'Content-Type: application/json' \
        -d '{"data": {"names": ["get"], "ndarray": ["data"]}}' \
        http://localhost:8003/seldon/seldon/step-experiments/api/v0.1/predictions
{
  "meta": {
    "puid": "qgrk9e6dlvpcdcgu0ip539afgt",
    "tags": {
      "current": "three",
      "one": "yes",
      "value_at_one": ["data"],
      "two": "yes",
      "value_at_two": ["one"],
      "three": "yes",
      "value_at_three": ["two"]
    },
    "routing": {
      "step-one": -1,
      "step-two": -1
    },
    "requestPath": {
      "step-three": "seldon-experiments:step-3",
      "step-one": "seldon-experiments:step-1",
      "step-two": "seldon-experiments:step-2"
    },
    "metrics": []
  },
  "data": {
    "names": [],
    "ndarray": ["two"]
  }
```

and with `executor`
```json
curl -X POST -H 'Content-Type: application/json' \
        -d '{"data": {"names": ["get"], "ndarray": ["data"]}}' \
        http://localhost:8003/seldon/seldon/step-experiments/api/v0.1/predictions
{"data":{"names":[],"ndarray":["two"]},"meta":{"tags":{"current":"three","three":"yes","value_at_three":["two"]}}}
```

both performed using `1.0.3-SNAPSHOT` and for following seldon deployment:
```yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: step-experiments
spec:
  name: three-steps
  annotations:
    seldon.io/executor: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldon-experiments:step-1
          name: step-one
          imagePullPolicy: IfNotPresent
          env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
        - image: seldon-experiments:step-2
          name: step-two
          imagePullPolicy: IfNotPresent
          env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
        - image: seldon-experiments:step-3
          name: step-three
          imagePullPolicy: IfNotPresent
          env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
    graph:
      children:
      - children:
        - endpoint:
            type: REST
          name: step-three
          type: MODEL
        endpoint:
          type: REST
        name: step-two
        type: MODEL
      endpoint:
        type: REST
      name: step-one
      type: MODEL
    name: steps-graph
    replicas: 1
```

(see models [here](https://github.com/RafalSkolasinski/seldon-experiments/tree/22b615a21bfc41c0921b15cbf8384d79444ed759/steps))

Issue related to https://github.com/SeldonIO/seldon-core/issues/1362 in order to provide backwards compatibility with behaviour present with engine.
