### ISSUE TITLE
Expose /metrics prometheus endpoint in python wrapper

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1476]
* For custom metrics

**Comment by RafalSkolasinski** [comment]
@cliveseldon It would be very helpful if you could give me some pointers where to start.

**Comment by cliveseldon** [comment]
Here is the current code location:
https://github.com/SeldonIO/seldon-core/blob/1cc1e9b1a28afba3c9d356e330d797bd178d1835/python/seldon_core/utils.py#L457

So a new module needs to be created using I assume https://github.com/prometheus/client_python to expose the metrics for prometheus to scrape.

The current engine code for reference is : https://github.com/SeldonIO/seldon-core/blob/1cc1e9b1a28afba3c9d356e330d797bd178d1835/engine/src/main/java/io/seldon/engine/predictors/PredictiveUnitBean.java#L334-L357

**Comment by RafalSkolasinski** [comment]
So as far as I understand, currently `metrics` is returned to the `engine` in the `meta.metrics` block of the response. This won't work with executor so from now on we need to add `/metrics` endpoint in the wrapper such that all containers expose it.

I guess this can be done flask as described [here](https://github.com/prometheus/client_python#flask).

So far pretty straightforward. 

Now, what need to be done for Prometheus to find those endpoints successfully?

**Comment by cliveseldon** [comment]
You may need to update the operator to add to each pod like we do for the engine:
https://github.com/SeldonIO/seldon-core/blob/1cc1e9b1a28afba3c9d356e330d797bd178d1835/operator/controllers/seldondeployment_engine.go#L83-L85

These should probably be added if they do NOT exist to allow people to customize them for their own containers.

However, if we add they by default I hope Prometheus won't complain for pods that don't expose them - not sure

**Comment by RafalSkolasinski** [comment]
Hmm... I start to wonder if Prometheus can scrape multiple endpoints from one POD.
Somehow I cannot find an example for this so far but maybe it's because I'm new to Prometheus.

**Comment by axsaucedo** [comment]
Also I think there's confusion on "single endpoint"... one pod has multiple containers, each container has their respective endpoints - prometheus scrapes from each container. Same with Elastic, or other monitoring services

**Comment by RafalSkolasinski** [comment]
What I had in mind that maybe it could be easier if yes, all microservices expose `/metrics` with raw information returned from user model defined `metrics` method and executor could query those and combine them to expose single endpoint to the prometheus.

**Comment by RafalSkolasinski** [comment]
Just to give an update, I am following with what we decided on Friday to add `/metrics` endpoint to the python wrapper and abandon Thursday idea of  aggregating them on the executor. 

What I have just pushed seems to work well for REST api type both in single and multi worker (gunicorn) mode -> using shared memory provided by `multiprocessing.Manager`:
- each worker updates its own metrics
- each worker expose metrics from all workers

I am now working out how to make it work GRPC api type.

@cliveseldon Do I recall correctly that you suggested to have metrics exposed by a separate flask microservice  independent from current REST/GRPC one? 

I wonder if I should follow this path or try to figure out how to serve this custom metrics on GRPC protocol.

**Comment by RafalSkolasinski** [comment]
I managed to expose today `/metrics` as independent microservice that serves metrics gathered in both REST and GRPC mode. I also made sure that all three types of custom metrics that were supported before are still working properly.

What's left in short:
- [ ] Configure metrics port via environmental variable
- [ ] Expose all metric labels to microservice via environmental variable (like image version, image name, model name, etc.)
- [ ] Configure Prometheus to scrape those new endpoints

**Comment by RafalSkolasinski** [comment]
Added missing labels via environmental variables yesterday.

**Comment by RafalSkolasinski** [comment]
I have confirmed that Prometheus can scrape multiple ports for a given endpoint in the Pod, it is go over multiple containers.

One of the means to do it is to not define port with 
```
    prometheus.io/port: "8000"
```
annotation. Prometheus will there probe all exposed ports for a configured endpoint default being `/metrics`. 
Downside is that it will probe even points that do not expose metrics leading to lots of spurious 404 in logs.

A better solution giving more control is to use named ports as suggested in this [stackoverflow](https://stackoverflow.com/questions/43121132/prometheus-with-multi-container-pod-on-kubernetes/46825817#46825817) post.

The underlying mechanism is as follows. Prometheus is configured to look only on ports that has name `metrics` by adding following entry as discussed in the post
```
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: metrics
```

Pods still need to have `prometheus.io/scrape: "true"` annotation present. For example with following section added to the Promeheus config a following Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-single-model-pod
  annotations:
    prometheus.io/scrape: "true"
spec:
  containers:
  - image: mock-model:latest
    imagePullPolicy: IfNotPresent
    name: my-mock-model-001
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
    - containerPort: 6000
      name: metrics
      protocol: TCP
    env:
    - name: PREDICTIVE_UNIT_SERVICE_PORT
      value: "5000"
    - name: PREDICTIVE_UNIT_METRICS_SERVICE_PORT
      value: "6000"
    - name: "SELDON_DEPLOYMENT_ID"
      value: "Deployment 001"
  - image: mock-model:latest
    imagePullPolicy: IfNotPresent
    name: my-mock-model-002
    ports:
    - containerPort: 5001
      name: http
      protocol: TCP
    - containerPort: 6001
      name: metrics
      protocol: TCP
    env:
    - name: PREDICTIVE_UNIT_SERVICE_PORT
      value: "5001"
    - name: PREDICTIVE_UNIT_METRICS_SERVICE_PORT
      value: "6001"
    - name: "SELDON_DEPLOYMENT_ID"
      value: "Deployment 002"
```
is successfully scraped by Prometheus.

Note the 
```
    - containerPort: 6000
      name: metrics
      protocol: TCP
```
section that both exposes the port and gives it a name.

On the side note port may have two names as I tried following and it didn't cause problems:
```
    - containerPort: 6000
      name: metrics
      protocol: TCP
    - containerPort: 6000
      name: metrics-other
      protocol: TCP
```

As the final note I have also confirmed that `prometheus.io/path: /prometheus` annotation is still respected.
