### ISSUE TITLE
Update seldon-core-analytics to use Prometheus operator

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1502]
Prometheus now offers an [operator](https://github.com/coreos/prometheus-operator) which manages the install of the Prometheus instance (plus AlertManager, etc). It also exposes some extra functionality through new CRDs which allow for distributed configs. For example, it now allows to have multiple [`PrometheusRules`](https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md) instances, which the operator then aggregates for the Prometheus config.

It would be good to consider migrating the [`seldon-core-analytics` charts](https://github.com/SeldonIO/seldon-core/tree/master/helm-charts/seldon-core-analytics) to use the new operator, which is published as a Helm chart itself in  https://github.com/helm/charts/tree/master/stable/prometheus-operator

**Comment by kinihun** [comment]
This would be a good to have feature, having duplicate Prometheus installations in the same cluster is not desirable.

**Comment by dewnull** [comment]
I created the following pod monitors and it seems to works okay. I wasn't sure if it can be done using service monitors.

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-apps-monitor
  labels:
    release: ${selector}
spec:
  namespaceSelector:
    matchNames:
    - ${namespace}
  selector:
    matchExpressions:
      - key: seldon-app
        operator: Exists
  podMetricsEndpoints:
  - port: metrics
    interval: 5s  
    path: /prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-monitor
  labels:
    release: ${selector}
spec:
  namespaceSelector:
    matchNames:
    - ${namespace}
  selector:
    matchLabels:
      app: seldon
  podMetricsEndpoints:
  - port: metrics
    interval: 5s  
```
