### ISSUE TITLE
Istio creates different path to Ambassador for explainer

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1548]
When launching a loanclassifier model, the path created in the virtualservice is: `prefix: /seldon/default/loanclassifier/loanclassifier/explainer/`, wheres in ambassador it would be `prefix: /seldon/default/loanclassifier-explainer/`. Running on master (1.0.3-SNAPSHOT)

File to replicate:

```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: loanclassifier
spec:
  name: loanclassifier
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: loanclassifier:0.1
          name: model
    graph:
      children: []
      name: model
      type: MODEL
      endpoint:
        type: REST
    explainer:
      type: "AnchorTabular"
      modelUri: gs://seldon-models/sklearn/income/explainer
    name: loanclassifier
    replicas: 1
```
