### ISSUE TITLE
Should only set istio route weight when seldon traffic field value > 0

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#1658]
The following deployment will generate Istio virtualservice with route weight = 0

```
kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1alpha2
metadata:
  name: iris
spec:
  name: iris
  predictors:
    - name: default
      graph:
        name: iris-default
        implementation: SKLEARN_SERVER
        modelUri: gs://seldon-models/sklearn/iris
      replicas: 1
    - name: shadow
      graph:
        name: iris-shadow
        implementation: SKLEARN_SERVER
        modelUri: gs://seldon-models/sklearn/iris
      replicas: 1
      shadow: true
```

```
      route:
        - destination:
            host: iris-iris-default
            port:
              number: 8000
            subset: default
          weight: 0
```

This feels like a bug to me, should only add weight field when user provide traffic field with value > 0
