### ISSUE TITLE
Unable to use HPA with a pre-packaged "implementation:TENSORFLOW_SERVER" model due to "tfserving" container not having requests/limits defined

### ISSUE THREAD

**Issue by thjwhite** [SeldonIO/seldon-core#1676]
I was able to verify that all containers brought up in the pod have requests and limits as described in the SeldonDeployment, with the exception of the "tfserving" container, but it seem that this is created implicitly in addition to the tfserving proxy wrapper so I couldn't find a way to set the requests / limits.

seldon-core-operator v1.0.1 installed with helm

kubectl describe hpa:
```
Events:
  Type     Reason                        Age                  From                       Message
  ----     ------                        ----                 ----                       -------
  Warning  FailedComputeMetricsReplicas  30m (x268 over 99m)  horizontal-pod-autoscaler  Invalid metrics (1 invalid out of 1), last error was: failed to get cpu utilization: missing request for cpu
  Warning  FailedGetResourceMetric       34s (x386 over 99m)  horizontal-pod-autoscaler  missing request for cpu
```

kubectl describe pod: 
```
tfserving:
    Container ID:  docker://e1a497370ef5f5540aed513ab296070af9cae058714b051769534e77baccf82a
    Image:         tensorflow/serving:latest
    Image ID:      docker-pullable://tensorflow/serving@sha256:ea44bf657f8cff7b07df12361749ea94628185352836bb08065345f5c8284bae
    Ports:         2000/TCP, 2001/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      /usr/bin/tensorflow_model_server
      --port=2000
      --rest_api_port=2001
      --model_name=redacted
      --model_base_path=/mnt/models
    State:          Running
      Started:      Wed, 08 Apr 2020 13:02:03 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/models from tfserving-provision-location (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-blnzj (ro)
```

kubectl get seldondeployment -o yaml

```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: redacted
  namespace: redacted
spec:
  annotations:
    seldon.io/engine-java-opts: -Dspring.task.execution.pool.core-size=20 -Dspring.task.execution.pool.max-size=100
      -Dspring.task.execution.pool.queue-capacity=100
    seldon.io/grpc-read-timeout: "60000"
    seldon.io/rest-read-timeout: "60000"
  name: redacted
  predictors:
  - componentSpecs:
    - hpaSpec:
        maxReplicas: 6
        metrics:
        - resource:
            name: cpu
            targetAverageUtilization: 80
          type: Resource
        minReplicas: 1
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: MODEL_NAME
            value: redacted
          image: redacted
          imagePullPolicy: IfNotPresent
          name: input-resizer
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 256Mi
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
        - env:
          - name: MODEL_NAME
            value: redacted
          image: redacted
          imagePullPolicy: IfNotPresent
          name: output-transformer
          resources:
            limits:
              cpu: 20m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 256Mi
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
        - image: seldonio/tfserving-proxy_grpc:0.7
          name: redacted
          resources:
            limits:
              cpu: "2"
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
    engineResources: {}
    explainer:
      containerSpec:
        name: ""
        resources: {}
    graph:
      children:
      - children:
        - endpoint:
            service_host: localhost
            service_port: 9002
            type: GRPC
          envSecretRefName: seldon-init-container-secret
          implementation: TENSORFLOW_SERVER
          modelUri: redacted
          name: redacted
          parameters:
          - name: signature_name
            type: STRING
            value: serving_default
          - name: model_name
            type: STRING
            value: redacted
          - name: model_input
            type: STRING
            value: in
          - name: model_output
            type: STRING
            value: out
          type: MODEL
        endpoint:
          service_host: localhost
          service_port: 9001
          type: GRPC
        implementation: UNKNOWN_IMPLEMENTATION
        name: output-transformer
        type: OUTPUT_TRANSFORMER
      endpoint:
        service_host: localhost
        service_port: 9000
        type: GRPC
      implementation: UNKNOWN_IMPLEMENTATION
      name: input-resizer
      type: TRANSFORMER
    labels:
      version: redacted
    name: redacted
    svcOrchSpec:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 25m
          memory: 512Mi
```

**Comment by thjwhite** [comment]
I was able to figure out a work around. There was some confusion though, initially I tried to just add the resources section, but it was error'ing out that it didn't have an image spec. Turns out what is required is the full specification for the container (including the image, args, ports, etc..). 

Initial container def from kubectl describe
```
  tfserving:
    Container ID:  docker://88bff9b128c3c01e0b411aae7e091b21b31e4c55d110e20610c7bb939a7c8cd8
    Image:         tensorflow/serving:latest
    Image ID:      docker-pullable://tensorflow/serving@sha256:ea44bf657f8cff7b07df12361749ea94628185352836bb08065345f5c8284bae
    Ports:         2000/TCP, 2001/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      /usr/bin/tensorflow_model_server
      --port=2000
      --rest_api_port=2001
      --model_name=redacted
      --model_base_path=/mnt/models
    State:          Running
      Started:      Wed, 08 Apr 2020 14:27:23 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/models from tfserving-provision-location (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-blnzj (ro)
```


With just requests added in a new tfserving entry  in the SeldonDeployment under .spec.predictors[].componentSpecs[].spec.containers

```yaml
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: tfserving
          resources:
            requests:
              cpu: 100m
```

```
  tfserving:
    Container ID:   docker://0b3f144cca27931ee9f2c3da2a500f9563f263535162fb09e22b753eca7714f4
    Image:          tensorflow/serving:2.1.0
    Image ID:       docker-pullable://tensorflow/serving@sha256:ea44bf657f8cff7b07df12361749ea94628185352836bb08065345f5c8284bae
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 08 Apr 2020 14:27:22 -0700
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /mnt/models from tfserving-provision-location (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-blnzj (ro)
```

What worked, fully specifying the container def
```
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: tfserving
          image: {{ .Values.tfserving.image }}
          args:
            - /usr/bin/tensorflow_model_server
            - --port=2000
            - --rest_api_port=2001
            - --model_name=redacted
            - --model_base_path=/mnt/models
          ports:
          - name: grpc
            containerPort: 2000
            protocol: TCP
          - name: http
            containerPort: 2001
            protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 1Gi
```
