### ISSUE TITLE
Autogenerate an OpenAPI spec and SDK

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1682]
At present we do not have python or other language SDKs for manipulating the SeldonDeployment resources.

 * Add openApi schema and generate SDK for python

**Comment by RexG** [comment]
+1;

really like the idea, working with/preparing yaml config is not systematic and straightforward;
please consider providing some SDKs for model deployment;

btw, if SDK for golang will be great LOL

**Comment by adriangonz** [comment]
@RexG if all you want is to manipulate `SeldonDeployment` resources, you could also import the type definition directly as:

```go
import (
 sc "github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1"
)

// ...

sdep := sc.SeldonDeployment{...}
```

**Comment by RexG** [comment]
thank you @adriangonz 

the goal is to **deploy model** on Seldon using SDK/API; 

i can see the [SeldonDeployment Struct](https://github.com/SeldonIO/seldon-core/blob/master/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go); can you guide me how use it to do the model deployment?

**Comment by adriangonz** [comment]
I see! You are right @RexG, the `SeldonDeployment` struct will only allow you to define the resource and manipulate it, but not to deploy it.

However, wouldn't something like the [Kubernetes' Go client](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#go-client) solve that? You could use that client to essentially run `kubectl apply` programmatically. 

Would that solve your use case? Otherwise, what else would you like to see in an SDK?

**Comment by RexG** [comment]
Thank you @adriangonz 

something like:
```
cli := Seldon.Client(url string)
restful_api := cli.deploy(SeldonDeployment())
```

then looks like i have to programmatically prepare the YAML configuration, and use Go client to do the model deployment

**Comment by cliveseldon** [comment]
We already have Go client libraries generated for kubernetes Go client so you should be able to do this: https://github.com/SeldonIO/seldon-core/tree/master/operator/client/machinelearning.seldon.io

Does this for your need?

**Comment by RexG** [comment]
hi @cliveseldon 

currently i'm using `kubectl apply -f xx.yaml` to deploy models in Seldon

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: wines
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: gs://seldon-models/mlflow/elasticnet_wine
        name: classifier
      name: default
      replicas: 1
```

can i do the same thing with [create](https://github.com/SeldonIO/seldon-core/blob/master/operator/client/machinelearning.seldon.io/v1/clientset/versioned/typed/machinelearning.seldon.io/v1/seldondeployment.go#L110)?
