### ISSUE TITLE
failed calling webhook

### ISSUE THREAD

**Issue by decoin** [SeldonIO/seldon-core#1742]
when i type command _kubectl apply -f deployment.yaml_, error occurred:

<pre>
Error from server (InternalError): error when creating "/Users/jason/sodb/deployment/deployment.yaml": Internal error occurred: failed calling webhook "v1.mseldondeployment.kb.io": Post https://seldon-webhook-service.seldon-system.svc:443/mutate-machinelearning-seldon-io-v1-seldondeployment?timeout=30s: stream error: stream ID 3; INTERNAL_ERROR
</pre>

**Comment by decoin** [comment]
> kubectl get validatingwebhookconfguration

return error:
<pre>
error: the server doesn't have a resource type "validatingwebhookconfguration"
</pre>

**Comment by cliveseldon** [comment]
Which version and how did you install Seldon Core?
Also what version of k8s?

**Comment by ryandawsonuk** [comment]
What about mutatingwebhookconfiguration?

K8s should have both (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks). There is something strange about your cluster if you don’t have them.

Seems the mutating Webhook is during as that is what leads to the error. You should have a detailed error in the pod logs of the Seldon-controller-manager - probably you have that installed in the seldon-system namespace.

Any details on cluster and Seldon version you can give would help also here.

**Comment by decoin** [comment]
> Which version and how did you install Seldon Core?
> Also what version of k8s?


helm list show this info about seldon:
<img width="673" alt="seldon_v" src="https://user-images.githubusercontent.com/5328179/80329068-b0613a80-8873-11ea-852c-38fb5e2aaed1.png">

and i installed seldon core as below:
<img width="633" alt="seldon_inst" src="https://user-images.githubusercontent.com/5328179/80329158-fa4a2080-8873-11ea-8808-8c8c9bfcae80.png">

and k8s version is v1.15.5

**Comment by decoin** [comment]
> What about mutatingwebhookconfiguration?
> 
> K8s should have both (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks). There is something strange about your cluster if you don’t have them.
> 
> Seems the mutating Webhook is there as that is what leads to the error. You should have a detailed error in the pod logs of the Seldon-controller-manager in the seldon-system namespace.
> 
> Those logs and any details on cluster and Seldon version you can give would help here.

when i command `kubectl get mutatingwebhookconfiguration`

it's looks like well:
<img width="591" alt="mutat" src="https://user-images.githubusercontent.com/5328179/80329442-ebb03900-8874-11ea-965e-1e95a9ddbfe6.png">

maybe the problem was caused by validatingwebhookconfguration?
how can i get the detail error log in pod or Seldon-controller-manager？

thanks for your ans!

**Comment by decoin** [comment]
@cliveseldon @ryandawsonuk 

i had print the log of Seldon-controller-manager:
[seldon-controller-manager.log](https://github.com/SeldonIO/seldon-core/files/4537321/seldon-controller-manager.log)

**Comment by cliveseldon** [comment]
It looks like it is calling the mutating webhook and then panic.
Can you show us your SeldonDeployment yaml?

**Comment by cliveseldon** [comment]
I can create this by leaving out the `graph` section of the resource:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
    name: example
    replicas: 1
```

The mutator is called before the validator is it has to handle bad graphs. So this does need to be fixed.

**Comment by cliveseldon** [comment]
Maybe we can remove the pointer from https://github.com/SeldonIO/seldon-core/blob/401aead1caadd04ff39dd537e3567b77e0b092cc/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go#L211

As is is required.

**Comment by decoin** [comment]
> I can create this by leaving out the `graph` section of the resource:
> 
> ```
> apiVersion: machinelearning.seldon.io/v1
> kind: SeldonDeployment
> metadata:
>   name: seldon-model
> spec:
>   name: test-deployment
>   predictors:
>   - componentSpecs:
>     - spec:
>         containers:
>         - image: seldonio/mock_classifier_rest:1.3
>           name: classifier
>     name: example
>     replicas: 1
> ```
> 
> The mutator is called before the validator so it has to handle bad graphs. So this does need to be fixed.


this is my deployment.yaml :

<pre>
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: obd-lof
  namespace: model-namespace
spec:
  name: obd-lof-model
  predictors:
  - componentSpecs:
    - spec:
      containers:
      - name: obd-lof-detection
        image: obd_lof:0.1
  - graph:
      name: obd-lof-detection
    name: obd-lof-predictor
    replicas: 1
</pre>

**Comment by cliveseldon** [comment]
@decoin Your yaml is badly formatted, the following should work

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: obd-lof
spec:
  name: obd-lof-model
  predictors:
  - componentSpecs:
    - spec:
       containers:
       - name: obd-lof-detection
         image: obd_lof:0.1
    graph:
      name: obd-lof-detection
    name: obd-lof-predictor
    replicas: 1
```

However, we will address the issue you highlighted. One reason its not caught is that k8s CRD is presently not structural so it will throw away parts of the spec that are not recognised. In the future when the CRD is structure it will complain about unknown fields.
