### ISSUE TITLE
Can't have a colon in the registry name with the Seldon-Core Python Package

### ISSUE THREAD

**Issue by Ogaday** [SeldonIO/seldon-core#1756]
This is usually the case when running a private registry. For instance, I am using the private registry provided with microk8s for local development, which is accessible at `localhost:32000`.

The example [here](https://github.com/Ogaday/minimal-seldon) works fine, but if I push to the private registry instead and modify the deployment yaml to reflect that:

```yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: identity
  namespace: models
spec:
  name: identity-model
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: model
          image: localhost:32000/identity:0.1.0
    graph:
      children: []
      endpoint:
        type: REST
      name: model
      type: MODEL
    name: model
    replicas: 1
```
and run the following:
```bash
docker pull ogaday/identity:0.1.0
docker tag ogaday/identity:0.1.0 localhost:32000/identity:0.1.0
docker push localhost:32000/identity:0.1.0
kubectl apply -f sdep.yaml
kubectl get pods -n models
# NAME                                      READY   STATUS             RESTARTS   AGE
# identity-model-0-model-658dc46898-b7h9t   0/2     CrashLoopBackOff   1          18s
kubectl logs -n models identity-model-0-model-658dc46898-b7h9t model
# Traceback (most recent call last):
#   File "/opt/conda/bin/seldon-core-microservice", line 5, in <module>
#     from seldon_core.microservice import main
#   File "/opt/conda/lib/python3.7/site-packages/seldon_core/__init__.py", line 2, in <module>
#     from .storage import Storage
#   File "/opt/conda/lib/python3.7/site-packages/seldon_core/storage.py", line 28, in <module>
#     from seldon_core.utils import getenv
#   File "/opt/conda/lib/python3.7/site-packages/seldon_core/utils.py", line 13, in <module>
#     from seldon_core.user_model import (
#   File "/opt/conda/lib/python3.7/site-packages/seldon_core/user_model.py", line 1, in <module>
#     from seldon_core.metrics import validate_metrics
#   File "/opt/conda/lib/python3.7/site-packages/seldon_core/metrics.py", line 39, in <module>
#     image_name, image_version = image.split(":")
# ValueError: too many values to unpack (expected 2)
```

Which I guess is because of the colon in the registry name, similar to #562. The code breaks [here](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/metrics.py#L39) and I see there's a similar line [here](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/metadata.py#L159).

---

Extra:
- https://microk8s.io/docs/registry-built-in

```bash
docker run --rm -it localhost:32000/identity bash -c 'pip freeze | grep seldon'
# seldon-core==1.1.0
```
```bash
kubectl version
# Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
# Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
