### ISSUE TITLE
Helm Chart - Seldon Core Analytics - extraEnv and VirtualService not working anymore.

### ISSUE THREAD

**Issue by ericmeadows** [SeldonIO/seldon-core#1791]
The following PR broke functionality to use the endpoint to expose the analytics endpoint using the normal URI:

https://github.com/SeldonIO/seldon-core/commit/95951e9bf853a080bcd9aa472db0996c5c914001#diff-5e3fb95c76b2c7485bcac774eaeb3ea5

`extraEnv` was removed, without question, breaking basically _all_ functionality when trying to expose the endpoint.  Previously we had used:
```
grafana_prom_service_type: ClusterIP
grafana_anonymous_auth: true
persistence.enabled: true
usage_metrics.enabled: true
grafana:
  virtualservice:
    enabled: true
    #trailing dash important and should be used when accessing
    prefix: "/grafana/"
    gateways:
      - kubeflow-gateway.kubeflow.svc.cluster.local
  extraEnv:
    #replace with KF gateway URI
    GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana"
```
but now this is completely not present anymore!
