### ISSUE TITLE
Duplicate ports defined in seldon-container-engine container

### ISSUE THREAD

**Issue by xaniasd** [SeldonIO/seldon-core#1799]
port 8000 is defined twice in the seldon-container-engine spec, as in the following example:

```yaml
      name: seldon-container-engine
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8000
          name: metrics
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
```

using seldon-core v1.1.0

**Comment by xaniasd** [comment]
I believe [this](https://github.com/SeldonIO/seldon-core/blob/88714deab5de4d4b5ffdc4d9f21935f88c973306/operator/controllers/seldondeployment_engine.go#L305-L306) is the culprit.

**Comment by RafalSkolasinski** [comment]
This was because this port serves not only `metrics` in executor / engine.
Do you know about any side-effects / downsides to having it duplicated?

**Comment by xaniasd** [comment]
That was my guess as well. About side-effects, haven't noticed any. Istio picks 2 application ports instead of one but no real effect. But this is not clean and confusing.

**Comment by RafalSkolasinski** [comment]
My understanding was that this section is mostly informative.
I have for sure have checked at a time that `port` entry may appear twice with two different `name`s.

This was more when I was looking at models before I decided to add `metrics` there on separate port. For models we have
```
    ports:
    - containerPort: 6000
      name: metrics
      protocol: TCP
    - containerPort: 9000
      name: http
      protocol: TCP
```
but initially I was thinking about having `metrics` also served on the same port as `http` and I checked that following would work
```
    ports:
    - containerPort: 6000
      name: metrics
      protocol: TCP
    - containerPort: 6000
      name: http
      protocol: TCP
```

Maybe for `executor` / `engine` we should instead of removing duplicate just add name to it to go from
```
    ports:
    - containerPort: 8000
      protocol: TCP
    - containerPort: 8000
      name: metrics
      protocol: TCP
```
to
```
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
    - containerPort: 8000
      name: metrics
      protocol: TCP
```
in order to make it clear at glance what purpose these ports serve.

I need to check in Kubernetes documentation for a potential downsides and/or side-effects,

@cliveseldon  any thoughts on this?
