### ISSUE TITLE
Seldon deployment name in case of complex graph 

### ISSUE THREAD

**Issue by amirclam** [SeldonIO/seldon-core#1801]
We have installed new 1.1 version 
The new changes in the k8s deployment name as described in the link below 
https://docs.seldon.io/projects/seldon-core/en/v1.1.0/reference/upgrading.html#deployment-naming-and-rolling-updates

Are working as expected when running one predictor in the graph when running a graph with more than one predictor

For example :
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-spam-classifier
  namespace: default
spec:
  annotations:
    project_name: seldon-spam-classifier
    deployment_version: v1
    seldon.io/rest-read-timeout: '100000'
    seldon.io/rest-connection-timeout: '100000'
    seldon.io/grpc-read-timeout: '100000'
  name: seldon-spam-classifier
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: translator
          image: sandhya1594/translator:1.0.0.1
          imagePullPolicy: Always
        - name: spam-classifier
          image: sandhya1594/spam-classifier:1.0.0.1
          imagePullPolicy: IfNotPresent
        terminationGracePeriodSeconds: 20
    graph:
      children:
      - name: spam-classifier
        endpoint:
          type: REST
        type: MODEL
        children: []
      name: translator
      endpoint:
        type: REST
      type: TRANSFORMER
    name: seldon-transformer
    replicas: 1
    annotations:
      predictor_version: v1
```
We get name seldon-77845c49ae296cbf824be799890890b2
Is there is why we can set the name of the deployment ? 

in case of graph the name should start with the seldon deployment name 
and not the generic name seldon 

for example after deploying 3 seldon graph
```
kubectl get deployment
NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
seldon-4753724109c3bf4ee202f2b20583de11   1/1     1            1           3h41m
seldon-4b6779613c5d28f51882c9619ad61e4e   1/1     1            1           3h29m
seldon-77845c49ae296cbf824be799890890b2   0/1     1            0           16s
```
