### ISSUE TITLE
Hyphens in names cause the service orchestrator to start a grpc server

### ISSUE THREAD

**Issue by mattpiatkus** [SeldonIO/seldon-core#1850]
Seldon version 1.1
Kubernetes version 1.14

On my cluster, the following starts a grpc orchestrator rather than a rest one:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: fixed
spec:
  name: fixed-hyphenated
  protocol: seldon
  transport: rest
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/fixed-model:0.1
          name: classifier1
    graph:
      children: []
      name: classifier1
      type: MODEL
    name: default
    replicas: 1
```

With `fixed-hyphenated` reverted to just `fixed`, it correctly starts a rest server.

The problem also seems to occur with hyphens in the repository name, predictor name, etc.  Repository names are a particular problem because (in my case) the name comes from the Google cloud project which can't be changed.  I was only able to use a rest orchestrator for my image by hosting it on an entirely new project with no hyphens in the name.
