### ISSUE TITLE
Grafana Dashboard not updating the deployments

### ISSUE THREAD

**Issue by Deunitato-sentient** [SeldonIO/seldon-core#1854]
I have encountered a problem whereby newly deployed deployments are not being captured by grafana dashboard for Seldon-core-analytics. I am able to view any old deployments I have made before creation of the grafana dashboard following the metrics helm [example](https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html) in the documentation.

Is this a bug or did I not do something correctly.

**Comment by axsaucedo** [comment]
What version of seldon-core-operator and seldon-core-analytics are you running? Master currently was updated and requires #1809 to match. Otherwise you need to make sure you are aligned with the compatibility table https://docs.seldon.io/projects/seldon-core/en/latest/reference/upgrading.html#wrapper-compatibility-table. 

Once you share the versions of both libraries we'll have a better insight on what the issue is.

**Comment by Deunitato-sentient** [comment]
Currently, I am using Seldon-core 1.1.0 and Seldon core analytics also 1.1.0.
Also, I realised that I left the namespace of my deployments and ambassador under `default`, does this affect anything?
Prometheus however, does reflect the deployments thou.

Seldon-core-analytics is configured under `seldon-system` namespace and I did a portforward using the command `kubectl port-forward svc/seldon-core-analytics-grafana 3000:80 -n seldon-system`

**Comment by ryandawsonuk** [comment]
Could you try port-forwarding to prometheus instead of grafana and in prometheus run each of:
`seldon_api_executor_client_requests_seconds_bucket{deployment_name=~".*",kubernetes_namespace=~"seldon",service="/predict",model_image=~".*",predictor_name=~".*",predictor_version=~".*",model_name=~".*",model_version=~".*"}`
`seldon_api_engine_client_requests_seconds_bucket{deployment_name=~".*",kubernetes_namespace=~"seldon",service="/predict",model_image=~".*",predictor_name=~".*",predictor_version=~".*",model_name=~".*",model_version=~".*"}`
`seldon_api_executor_client_requests_seconds_count{deployment_name=~".*",kubernetes_namespace=~".*",predictor_name=~".*"}`
`seldon_api_engine_client_requests_seconds_count{deployment_name=~"iris",kubernetes_namespace=~".*",predictor_name=~".*"}`

That should help us determine the problem. I'm guessing you have [left the executor enabled as that's the default now](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/values.yaml#L39) instead of the Java engine. The metrics did change when that change was made. But with the new analytics I'd expect the new models to be showing metrics and not the old ones.

**Comment by Deunitato-sentient** [comment]
`seldon_api_executor_client_requests_seconds_bucket{deployment_name=~".*",kubernetes_namespace=~"seldon",service="/predict",model_image=~".*",predictor_name=~".*",predictor_version=~".*",model_name=~".*",model_version=~".*"}`

**Results: Show all the old models but not the new models**

`seldon_api_engine_client_requests_seconds_bucket{deployment_name=~".*",kubernetes_namespace=~"seldon",service="/predict",model_image=~".*",predictor_name=~".*",predictor_version=~".*",model_name=~".*",model_version=~".*"}`

**Results: Shows nothing**

`seldon_api_executor_client_requests_seconds_count{deployment_name=~".*",kubernetes_namespace=~".*",predictor_name=~".*"}`
**Result: Show all old models but not the new one**

`seldon_api_engine_client_requests_seconds_count{deployment_name=~"iris",kubernetes_namespace=~".*",predictor_name=~".*"}`

**Result: Show nothing**

Is there something that needs to be set up first or am I doing something wrong..

**Comment by ryandawsonuk** [comment]
Oh in that first query kubernetes_namespace=~"seldon" should be kubernetes_namespace=~".*". But I guess you figured that out as you got results. You can experiment with replacing values with .* and removing fields to broaden the query. Then you might find the new model data. Strange that the data for new models is missing.

What version of seldon core were the old models created with? 

Is it an option for you to uninstall and reinstall seldon core analytics? Is that how you upgraded seldon core analytics?

**Comment by Deunitato-sentient** [comment]
It is a fresh installation of seldon-core-analytics, all the models created are using `1.1.0` and no upgrading was done

**Comment by ryandawsonuk** [comment]
I guess all the pods are up and responding to requests. Would you be able to copy a working and non-working pod's manifest so we can compare?

**Comment by ryandawsonuk** [comment]
FWIW, it has been working for me so just thinking about possible differences - 1) I've been running latest master and 2) I've been installing by cloning the repo and doing a helm install from the local path rather than from the published/hosted version of the chart

**Comment by ericandrewmeadows** [comment]
I end up having this same problem, when using a router; all pods are functional in the graph, when I bash into a bod and run the following, the data is there:
```
from requests import get
get("http://localhost:6000/prometheus")
```
When running non-router models, nothing comes in at all.  This is consistent across all 1.1.0 deployments, using the Helm charts (`seldon-core-operator`, and `seldon-core-analytics` from the 1.1.0 repo tag).

**Comment by Deunitato-sentient** [comment]
This is my deployment.yaml

***Non-working:***

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-metrics
  labels:
    model_name: times2-plus2
    api_type: microservice
    microservice_type: ai
spec:
  annotations:
    seldon.io/executor: "true"
  name: times2-plus2
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: model
          image: <My image 2>
          imagePullPolicy: Always
        - name: transformer
          image: <My image 1>
          imagePullPolicy: Always
        imagePullSecrets: 
          - name: gcr-json-key
    graph:
      name: transformer
      type: TRANSFORMER
      endpoint:
        type: REST
      children: 
      - name: model
        type: MODEL
        endpoint:
          type: REST
    name: t1-t2
    replicas: 1
```

***Working:***
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-model-combiner
  labels:
    model_name: times2-plus2
    api_type: microservice
    microservice_type: ai
spec:
  name: times2-plus2
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: combiner
          image: gcr.io/science-experiments-divya/combiner:0.2.2
          imagePullPolicy: IfNotPresent
        - name: subprocess-times2
          image: <Image 1>
          imagePullPolicy: Always
        - name: subprocess-plus2
          image: <Image 2>
          imagePullPolicy: Always
    graph:
        name: combiner
        type: COMBINER
        endpoint:
          type: REST
        children: 
        - name: subprocess-times2
          type: MODEL
          endpoint:
            type: REST
        - name: subprocess-plus2
          type: MODEL
          endpoint:
            type: REST
    name: times2-plus2-pod
    replicas: 1

```

I did download the seldon-core repo locally in my cloud before using helm install.
