### ISSUE TITLE
Permission denied while reading ./openapi/seldon.json in seldon-container-engine

### ISSUE THREAD

**Issue by aguschin** [SeldonIO/seldon-core#1855]
Hello, guys. First of all, thank you for developing Seldon-core, its fantastic.

I have tried to access `http://<ingress_url>/seldon/<namespace>/<model-name>/api/v1.0/doc/` endpoint to send some requests with UI, as suggested in https://docs.seldon.io/projects/seldon-core/en/latest/workflow/github-readme.html, but stumbled over an error `open ./openapi/seldon.json: permission deniedFailed to embed variables on OpenAPI template` in seldon-container-engine. Here are steps to reproduce the error (assuming kind is already installed).

To save your time here is the MR which introduced this functionality: https://github.com/SeldonIO/seldon-core/pull/1730

1. ```kind create cluster```

2.  installing latest helm chart from repo ```helm install seldon-core ./helm-charts/seldon-core-operator  --namespace seldon-system```

3. Using example from https://github.com/SeldonIO/seldon-core/blob/master/executor/README.md

```
kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-model
spec:
  annotations:
    seldon.io/executor: "true"
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    labels:
      version: v1
    name: example
    replicas: 1
END
```

4. Getting error in logs

```
k logs seldon-model-example-0-classifier-7fd6fc4d74-v7jc5 -c seldon-container-engine 

{"level":"info","ts":1589971301.715907,"logger":"entrypoint","msg":"Flags","transport":"rest"}
{"level":"info","ts":1589971301.7159576,"logger":"entrypoint","msg":"Trying to get predictor from Env"}
time="2020-05-20T10:41:41Z" level=error msg="open ./openapi/seldon.json: permission deniedFailed to embed variables on OpenAPI template" source="main.go:216"
{"level":"info","ts":1589971301.719009,"logger":"entrypoint","msg":"Starting","worker":1}
{"level":"info","ts":1589971301.7190619,"logger":"entrypoint","msg":"Starting","worker":2}
{"level":"info","ts":1589971301.7190707,"logger":"entrypoint","msg":"Starting","worker":3}
{"level":"info","ts":1589971301.7190747,"logger":"entrypoint","msg":"Starting","worker":4}
{"level":"info","ts":1589971301.7190778,"logger":"entrypoint","msg":"Starting","worker":5}
{"level":"info","ts":1589971301.723948,"logger":"entrypoint","msg":"Running http server ","port":8000}
{"level":"info","ts":1589971301.7246838,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}
```
5. Finally, when I try to access `api/v1.0/doc` endpoint, I get "404 page not found". `api/v1.0/predictions` endpoint works as usual.

That said, this may be a bug or it is me doing something wrong. If this is the case, please comment what steps should be taken to successfully access api/v1.0/doc.
