### ISSUE TITLE
curl command on seldon core overview doesn't work

### ISSUE THREAD

**Issue by jhaanuj2108** [SeldonIO/seldon-core#1918]
I am following the sklearn server sample (iris) from the [overview page. ](https://docs.seldon.io/projects/seldon-core/en/v1.1.0/workflow/github-readme.html)

The server is running fine and is available. I have installed Seldon on kubeflow and I have port forwarded Seldon to localhost:8005.

`curl -X POST http://localhost:8005/seldon/seldon/iris-model/api/v1.0/predictions -H 'Content-Type: application/json' -d '{ "data": { "ndarray": [1,2,3,4] } }' | json_pp`
```
'json_pp' is not recognized as an internal or external command,
operable program or batch file.
```

And if I remove json_pp it shows some other error.
`curl -X POST http://localhost:8005/seldon/seldon/iris-model/api/v1.0/predictions -H 'Content-Type: application/json' -d '{ "data": { "ndarray": [1,2,3,4] } }'`
```
curl: (56) Recv failure: Connection was reset
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: data
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Could not resolve host: ndarray
curl: (3) [globbing] bad range in column 2
curl: (3) [globbing] unmatched close brace/bracket in column 1
curl: (3) [globbing] unmatched close brace/bracket in column 1
```

**Comment by cliveseldon** [comment]
Are you compiling the sklearn server yourself?
Which version of Seldon.
Can you show us your yaml if deploying onto a cluster?

**Comment by jhaanuj2108** [comment]
This the yaml file with command that I am using to serve the iris server.
```
kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris
  namespace: seldon
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: classifier
    name: default
    replicas: 1
END

```
