### ISSUE TITLE
Tags created by components inside combiner don't propagate

### ISSUE THREAD

**Issue by gmattar** [SeldonIO/seldon-core#1927]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/1631275/83802400-89124000-a65f-11ea-9da0-8351acb38831.png">

Basically, all models create tags and the Transformer Output needs to read them before forwarding the result of Model 3. I'm using Seldon 1.1 with REST requests.

**The problem is that I can only see the tags from Model 3 inside Transformer.** 
These are the steps I took and what I found after inspecting the components:

- First I included a breakpoint inside `aggregate` but was not able to see the tags, the `meta` parameter was empty. Then, I included an `aggregate_raw` function and was able to see them. meta is not passed to `client_aggregate` in this scenario: https://github.com/SeldonIO/seldon-core/blob/de2dce0388e101196292ed10797c67826ee1f7c4/python/seldon_core/seldon_methods.py#L433

-  I changed SELDON_LOG_LEVEL to DEBUG and checked the response sent by the Combiner component. The tags were passed to executor

- Next, I checked the meta parameter passed to Model 3 and the metas were empty again.

- Last, I checked the tags in Transformer Ouput and only the data of Model 3 was available

_Originally posted by @gmattar in https://github.com/SeldonIO/seldon-core/issues/1474#issuecomment-639208951_

---

@gmattar It seems that aggregate methods are not passing `meta` argument which contain tags.
Could you open a new issue for this and add information what version of wrapper are you using?

_Originally posted by @RafalSkolasinski in https://github.com/SeldonIO/seldon-core/issues/1474#issuecomment-639341594_

---

I'm building my own custom image instead of using a wrapper:

```
FROM continuumio/miniconda3:4.8.2

WORKDIR /microservice

ENV MODEL_NAME BaseComponent
ENV API_TYPE REST
ENV SERVICE_TYPE UNDEFINED
ENV PERSISTENCE 0

RUN pip install seldon-core==1.1.0

EXPOSE 5000

CMD ["sh", "-c", "seldon-core-microservice $MODEL_NAME $API_TYPE --service-type $SERVICE_TYPE --persistence $PERSISTENCE"]
```

**Comment by RafalSkolasinski** [comment]
@gmattar thanks for reporting this - I will look into it and get back to you

**Comment by RafalSkolasinski** [comment]
@gmattar Would you be so kind to provide a `graph` section of your `SeldonDeployment` manifest?

**Comment by RafalSkolasinski** [comment]
The reason I ask is because up to my knowledge the only component that can go in the request flow after `combiner` is `output transformer` and I am not sure if the graph definition would correspond to what you wanted to define.

**Comment by gmattar** [comment]
this is the full graph (I simplified it a bit in the issue description): 

```yaml
graph:
        name: response-generator
        type: OUTPUT_TRANSFORMER
        endpoint:
            type: REST
        children:
        - name: model-a
          type: OUTPUT_TRANSFORMER
          endpoint:
            type: REST
          children:
          - name: to-tensor
            type: OUTPUT_TRANSFORMER
            endpoint:
              type: REST
            children:
            - name: image-crop
              type: COMBINER
              endpoint:
                type: REST
              children:
              - name: downloader-1
                type: TRANSFORMER
                endpoint:
                  type: REST
                children: []
              - name: downloader-2
                type: TRANSFORMER
                endpoint:
                  type: REST
                children:
                - name: to-tensor
                  type: TRANSFORMER
                  endpoint:
                      type: REST
                  children:
                  - name: model-2
                    type: MODEL
                    endpoint:
                      type: REST
                    children: []
```

Also, this thread in Seldon slack channel has a bit more information about my graph:
https://seldondev.slack.com/archives/C8Y9A8G0Y/p1590116481237900
