### ISSUE TITLE
How do I increase timeout of sidecar seldon container?

### ISSUE THREAD

**Issue by codebreach** [SeldonIO/seldon-core#196]
We see the following error as one of our predictors takes a while (10+ sec) 

But it seems that the sidecar that manages these connections has a fixed timeout in the code somewhere. Ideally we should allow this to be configured somewhere?

```json
{
    "code": 203,
    "info": "org.springframework.web.client.ResourceAccessException: I/O error on POST request for \"http://0.0.0.0:9000/predict\": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out",
    "reason": "Microservice error",
    "status": "FAILURE"
}
```

**Comment by codebreach** [comment]
Looking at the code 

It seems that its hardcoded 
https://github.com/SeldonIO/seldon-core/blob/93d875d68ce93f7696d640777472fbd02528a950/api-frontend/src/main/java/io/seldon/apife/service/InternalPredictionService.java#L55

**Comment by cliveseldon** [comment]
Yes, you are right ; we are working on functionality to allow configuration via annotations in the SeldonDeployment CRD so these things can be configurable.

**Comment by codebreach** [comment]
Is there an PR that has the code? we can dogfood it because its preventing us from deploying to production.

we can also help implement if required.

**Comment by codebreach** [comment]
seems that if we can somehow set the property 
`io.seldon.clustermanager.engine-container-image-and-version=${ENGINE_CONTAINER_IMAGE_AND_VERSION}`

it will work.

any guidance?

**Comment by cliveseldon** [comment]
Yes, there are a few things:

 The timeout will be in the API FrontEnd Gateway AND the Seldon Engine (service orchestrator), so you would need to hack both of those. Yes, you can change the engine version from the Helm values.yaml. 
https://github.com/SeldonIO/seldon-core/blob/8b6bf70fd1813881b4b66e5d2c6d02ee26918ea7/helm-charts/seldon-core/values.yaml#L33

I will do a premlinary PR with the code for the annotations as well. Happy to have help on working on this. 

Please contact me on our Slack channel.

**Comment by cliveseldon** [comment]
The PR https://github.com/SeldonIO/seldon-core/pull/197

**Comment by cliveseldon** [comment]
This should be fixed in the latest snapshot development release by the PR #211 
If you use images for 0.2.3-SNAPSHOT you can test. See 
[docs](https://github.com/SeldonIO/seldon-core/blob/master/docs/annotations.md) and 
[example](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/timeouts.ipynb).

Please test and tell us if it fixes your requirements.

**Comment by codebreach** [comment]
This is great!

Will test it out and let you know. It seems that this should cover our
use-case exactly.

Madhav

**Comment by codebreach** [comment]
This doesn't work behind ambassador
`timeout_ms` is not set on the service generated even though we pass the annotations

```
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  seldon_dpa_rest_mapping
      prefix: /seldon/dpa/
      service: dpa:8000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  dpa_grpc_mapping
      grpc: true
      prefix: /seldon.protos.Seldon/
      rewrite: /seldon.protos.Seldon/
      headers:
        seldon: dpa
      service: dpa:5001
```

it should include 
```
      timeout_ms: VALUE_FROM_ANNOTATION
```
