### ISSUE TITLE
AB testing using same inference server

### ISSUE THREAD

**Issue by sreddybr3** [SeldonIO/seldon-core#1960]
I would like to deploy two ML models in a single Tensorflow(TFS) Inference Server and then define a graph that does traffic split between these two models.

I have prebaked two models and config in a TFServing inference server: You can test it locally using 
```docker run -p 8501:8501 -it --rm sreddybr3/tfs-prebaked:0.0.3```

once the container starts, it will serve two models - 
model 1 - `curl -d '{"instances": [1.0, 2.0, 5.0]}' -X POST http://localhost:8501/v1/models/half-plus-two:predict`
model 2 - `curl -d '{"instances": [1.0, 2.0, 5.0]}' -X POST http://localhost:8501/v1/models/half-plus-three:predict`

Now moving to Seldon world:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rest-tfserving
spec:
  name: resttfserving
  protocol: tensorflow
  transport: rest
  predictors:
  - componentSpecs:
    - spec:
        containers:
          image: sreddybr3/tfs-prebaked:0.0.3
          name: half-plus-two
          ports:
          - containerPort: 8501
            name: http
    graph:
      name: half-plus-two
      type: MODEL
      endpoint:
        service_port: 8501
    name: model
    replicas: 1
```

the above works because graph name "half-plus-two" and one of the container name "half-plus-two" in componentSpec matches

**but my end goal is to have a graph which splits traffic between two models running in the same inference server**

failed attempt 1: referencing to a previous/existing services in graph spec
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rest-tfserving-share
spec:
  name: resttfserving-share
  protocol: tensorflow
  transport: rest
  predictors:
  - componentSpecs:
    - spec:
        containers:
          image: sreddybr3/tfs-prebaked:0.0.3
          name: half-plus-two-shared
          ports:
          - containerPort: 8501
            name: http
    graph:
      name: half-plus-two-shared
      type: MODEL
      endpoint:
        service_port: 8501
      traffic: 80
    name: model
    replicas: 1
  - graph:
      endpoint:
        service_host: rest-tfserving-model-half-plus-two-shared
        service_port: 8501
      implementation: UNKNOWN_IMPLEMENTATION
      name: half-plus-two
      type: MODEL
      traffic: 20
```

failed attempt 2: using a router
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: abtest
spec:
  name: abtest
  protocol: tensorflow
  transport: rest
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sreddybr3/tfs-prebaked:0.0.3
          name: half-plus-two
          ports:
          - containerPort: 8501
            name: http
    graph:
      name: random-abtest
      implementation: RANDOM_ABTEST
      parameters:
      - name: ratioA
        value: '0.5'
        type: FLOAT
      children:
      - name: half-plus-two
        endpoint:
          type: REST
          service_host: abtest-model-half-plus-two
          service_port: 8501
        type: MODEL
        children: []
      - name: half-plus-three
        endpoint:
          type: REST
          service_host: abtest-model-half-plus-two
          service_port: 8501
        type: MODEL
        children: []
    name: abtest
    replicas: 1
```

failed attempt 3: 

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rest-tfserving-grph
spec:
  name: resttfserving-grph
  protocol: tensorflow
  transport: rest
  predictors:
  - graph:
      endpoint:
        service_host: rest-tfserving-model-half-plus-two
        service_port: 8501
      implementation: UNKNOWN_IMPLEMENTATION
      name: half-plus-two
      type: MODEL
      traffic: 80
  - graph:
      endpoint:
        service_host: rest-tfserving-model-half-plus-two
        service_port: 8501
      implementation: UNKNOWN_IMPLEMENTATION
      name: half-plus-three
      type: MODEL
      traffic: 20
```

general question: is it possible for graph to reference to other container in the componentSpec.

Currently, the way it works is graph name will be used to lookup container name in the component spec.
