### ISSUE TITLE
executor service not targeting to executor

### ISSUE THREAD

**Issue by chengcheng-pei** [SeldonIO/seldon-core#1975]
## Describe the bug

Below is part of the service of executor:
```
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 5001
```
if executor exposes only 8000 for both rest and grpc, why the grpc targetPort is still 5001?
Is it still a bug?
Or I am doing something wrong?

## To reproduce

btw, I built operator from master branch.
the version of executor is 1.2.0

## Environment

* Kubernetes Version: [e.g. 1.15]
* Cloud Provider: [e.g. GKE, AWS, Bare Metal, Kind, Minikube]
* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]
* Kubernetes Cluster Version [Output of `kubectl version`]

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
@glindsell can you check this?

**Comment by RafalSkolasinski** [comment]
If I am not mistaken it probably should look sth like this 
```
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 8000
    protocol: TCP
    targetPort: 8000
```

**Comment by glindsell** [comment]
@chengcheng-pei thanks for highlighting the bug. It looks like because the operator can create either a java engine which does not multiplex, or an executor which, with the new changes does multiplex - the service has ended up not being changed to reflect the difference between the two options. I have added this issue to be fixed in the [1.2.1 project](https://github.com/SeldonIO/seldon-core/projects/28). I will update with progress.

**Comment by glindsell** [comment]
@chengcheng-pei I have just noticed that the service yaml you pasted is not in line with the executor changes. You should see the following:

```
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 8000
```

I have just submitted a PR to fix the engine ports. If the engine is being used you should see what you pasted above. But if executor is used you should see what I have pasted here.

Please check the version you are running and let me know if you still see the issue with target port.
