### ISSUE TITLE
high memory and cpu usage in deployment of xgboost rest

### ISSUE THREAD

**Issue by chengcheng-pei** [SeldonIO/seldon-core#1986]
## Describe the bug

I deployed XGBoost model with REST. the worker number is by default 1. I saw high cpu usage and memory usage. The memory usage is always growing (I set limit 20 24G for debug):

![Screen Shot 2020-06-02 at 12 26 25 PM](https://user-images.githubusercontent.com/57113014/85167809-44b99f00-b21e-11ea-9cf1-99f8751695d5.png)

but after I set worker number to 3 and gunicorn used, the memory and cpu usage look low and normal.

I added the following ENV:

```
          env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
          - name: GUNICORN_MAX_REQUESTS
            value: "10000"
          - name: GUNICORN_MAX_REQUESTS_JITTER
            value: "1000"
          - name: GUNICORN_WORKERS
            value: "3"
          - name: KMP_AFFINITY
            value: "granularity=fine,verbose,compact,1,0"
          - name: KMP_BLOCKTIME
            value: "1"
          - name: OMP_NUM_THREADS
            value: "8"
```

![Screen Shot 2020-06-04 at 12 03 37 PM](https://user-images.githubusercontent.com/57113014/85167907-729ee380-b21e-11ea-8625-2fcf29ee810e.png)

I guess the problem is around: https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/microservice.py#L336

And xgboost.predict() is not thread safe.

## Environment

* Kubernetes Version: [e.g. 1.15]
* Cloud Provider: [e.g. GKE, AWS, Bare Metal, Kind, Minikube]
* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]
* Kubernetes Cluster Version [Output of `kubectl version`]

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]
