### ISSUE TITLE
Seldon Core operator Crashes when deployment with empty predictor is passed

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2020]
## Describe the bug

When creating a seldon deployment with empty predictors, the operator enters crash loop.

## To reproduce

```
kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: sklearn
spec:
  name: iris
  predictors: []
END
```

## Expected behaviour

The webhook should reject the deployment / patch.

## Environment

* Kubernetes Version: 1.16
* Cloud Provider: Docker Desktop
* Deployed Seldon System Images:
```
          value: docker.io/seldonio/engine:1.2.0
          value: docker.io/seldonio/seldon-core-executor:1.2.0
        image: docker.io/seldonio/seldon-core-operator:1.2.0
```
