### ISSUE TITLE
Unable to view feedback reward on Grafana dashboard

### ISSUE THREAD

**Issue by Nithinbs18** [SeldonIO/seldon-core#2115]
Dear team,

Greetings!
I am currently working with Seldon-analytics and unable to visualize the feedback data on the grafana dashboard.

Please find the below details;
Seldon deployment manifest:
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: test2
spec:
  name: test2
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/b
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: model-test2
      labels:
        test-nithin: nithin2
      replicas: 1
      componentSpecs:
        - spec:
            containers:
              - name: classifier
                env:
                  - name: FOO
                    value: bar
                livenessProbe:
                  failureThreshold: 3
                  initialDelaySeconds: 300
                  periodSeconds: 5
                  successThreshold: 1
                  tcpSocket:
                    port: http
                  timeoutSeconds: 1
```
Helm charts used to install the pre-requisites :

```
helm install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts --set usageMetrics.enabled=true --set ambassador.enabled=true --set executor.defaultEnvSecretRefName=seldon-core-init-container-secret

helm install seldon-core-analytics seldon-core-analytics --repo https://storage.googleapis.com/seldon-charts --set grafana_prom_admin_password=password --set persistence.enabled=false

helm repo add stable https://kubernetes-charts.storage.googleapis.com

helm install ambassador stable/ambassador --set crds.keep=false
```
Client program ;

```
import pandas as pd
import numpy as np
from seldon_core.seldon_client import SeldonClient
import json
import time
import requests
sc = SeldonClient(
    gateway_endpoint="localhost:8003",
    gateway="ambassador",
    namespace="default",
    deployment_name='test2')

df = pd.read_csv("./wine-quality.csv")

def _get_reward(y, y_pred):
    if y == y_pred:
        return 500
    return 1 / np.square(y - y_pred)


def _test_row(row):
    input_features = row[:-1]
    feature_names = input_features.index.to_list()
    X = input_features.values.reshape(1, -1)
    y = row[-1]
    r = sc.predict(
        data=X,
        names=feature_names)
    print(r.request)
    print(r.response)
    y_pred = (r.response['data']['tensor']['values'])
    reward = _get_reward(y, y_pred)
    print((str(y))+"-------"+(str(y_pred))+"-------"+(str(reward)))
    sc.feedback(
        prediction_request=r.request,
        prediction_response=r.response,
        gateway='ambassador',
        gateway_endpoint="localhost:8003",
        namespace="default",
        deployment_name='test2',
        reward=float(reward))
    return reward[0]
df.apply(_test_row, axis=1)
```
 I also tried manually posing the data using;
 with **Request:**
meta {
}
data {
  names: "fixed acidity"
  names: "volatile acidity"
  names: "citric acid"
  names: "residual sugar"
  names: "chlorides"
  names: "free sulfur dioxide"
  names: "total sulfur dioxide"
  names: "density"
  names: "pH"
  names: "sulphates"
  names: "alcohol"
  tensor {
    shape: 1
    shape: 11
    values: 8.3
    values: 0.42
    values: 0.62
    values: 19.25
    values: 0.04
    values: 41.0
    values: 172.0
    values: 1.0002
    values: 2.98
    values: 0.67
    values: 9.7
  }
}
 
**Response**: 
{'data': {'names': [], 'tensor': {'shape': [1], 'values': [5.277768952367847]}}, 'meta': {}}

**Code:**
```
    payload = json.dumps(r.response)
    response_raw = requests.post(
        "http://localhost:8003/seldon/default/test2/api/v1.0/feedback",
        json=payload
     )
    print(response_raw.status_code)
    print(response_raw.text)
```
This returns 400 with below message:

```
{"status":{"code":-1,"info":"Invalid JSON: Message type \"seldon.protos.Feedback\" has no field named \"{\".\n Available Fields(except extensions): ['request', 
'response', 'reward', 'truth']","reason":"MICROSERVICE_BAD_DATA","status":1}}
```

The prediction works absolutely fine but does not return anything in meta eg:

`{'data': {'names': [], 'tensor': {'shape': [1], 'values': [5.277768952367847]}}, 'meta': {}}`

Please find the screenshot:
![image](https://user-images.githubusercontent.com/44024922/87295214-29803d80-c505-11ea-97cf-732f400a9fcf.png)
 
The return value of  feedback function:

```
Success:True message:
Request:
request {
  meta {
  }
  data {
    names: "fixed acidity"
    names: "volatile acidity"
    names: "citric acid"
    names: "residual sugar"
    names: "chlorides"
    names: "free sulfur dioxide"
    names: "total sulfur dioxide"
    names: "density"
    names: "pH"
    names: "sulphates"
    names: "alcohol"
    tensor {
      shape: 1
      shape: 11
      values: 7.0
      values: 0.27
      values: 0.36
      values: 20.7
      values: 0.045
      values: 45.0
      values: 170.0
      values: 1.001
      values: 3.0
      values: 0.45
      values: 8.8
    }
  }
}
response {
  meta {
  }
  data {
    tensor {
      shape: 1
      values: 5.283192947262262
    }
  }
}
reward: 1.9462358

Response:
{'data': {'tensor': {'shape': [0]}}, 'meta': {}}
```

Any help on this will be highly appreciated.
Thanks in advance.
