### ISSUE TITLE
Default user ID is always set to 8888

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#2142]
## Describe the bug

Since `1.2`, the Seldon Core operator will always inject by default a `securityContext` at the pod level which runs every container as user `8888`. This is in line with OpenShift's best practices. The user can always change the default user ID through the `defaultUserID` property of Seldon Core's Helm chart, or by overriding the `securityContext` at the container level.

Seldon Core's images (i.e. executor and Python wrapper) will always run with this user. However when using a custom Docker image the user ID could change, in which case the user would run into permissions problems.

We should document this change, how it can affect the user and how to change it. Alternatively, we could always set the `defaultUserID` to empty and start using the `runAsNonRoot` field. I.e. injecting the following `securityContext` by default:

```yaml
securityContext:
  runAsNonRoot: true
```

That would mean that containers can only be ran as non-root users (unless overriden), and that K8s will use the user ID in the Docker's image metadata. 

## To reproduce

1. Install SC with the default parameters.
2. Deploy a `SeldonDeployment` using SC 1.2.
3. Check that the pod has a `securityContext` with `runAsUser: 8888`.

## Expected behaviour

We should make it clear to the user that containers will run by default as user `8888`. Alternatively, we should change the operator so that it doesn't enforce a particular user ID and instead uses the container's user from the image's metadata (the default if you don't specify a `runAsUser`).

## Environment

- Seldon Core 1.2

**Comment by ramanNarasimhan77** [comment]
@adriangonz 
I am currently facing this issue. My team is trying to change all our docker images to run as a non-root `appuser`

I have a base python image that has USER set to `appuser` with uid 1000 and entry point [tini](https://github.com/krallin/tini)

While wrapping my model using `docker` approach, I was installing `seldon-core`, `tensorflow` etc using `pip` with `--user` flag which would result in the python packages being installed to `/home/appuser/.local/bin`

I was able to build the image and serve locally but everytime I used it in a `seldonDeployment`, it would start and then go into `Crashloopbackoff` state. The pod logs showed `exec seldon-core-microservice permission denied`

After a whole lot of debugging, I found out that the `securityContext` is being defaulted to `8888` and then on searching for `8888` in the repo, I found this issue.

I am using this example [deep-mnist.json](https://github.com/SeldonIO/seldon-core/blob/master/examples/models/deep_mnist/deep_mnist.json) as reference

Can you please share an example showing how to specify security context explicitly in a SeldonDeployment ? In my case, I have to run as 1000.

**Comment by cliveseldon** [comment]
You can add a [securityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#securitycontext-v1-core) to your container, e.g.:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
          securityContext:
            runAsUser: 1000
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: example
    replicas: 1
```
