### ISSUE TITLE
Use http2 as service type for new Executor

### ISSUE THREAD

**Issue by mwm5945** [SeldonIO/seldon-core#2189]
Since the new executor multiplexes HTTP and GRPC over the same port, the k8's service that is created should also only have one port definition using `http2`. `http2` allows regular http1.x traffic to continue un changed, but also allows istio to properly multiplex the different protocols through the sidecar. The Istio virtual services will also need to be updated to point at the same port for both `http` and `grpc`. 

ex:
``` yaml
apiVersion: v1
kind: Service
...
spec:
  clusterIP: xx.xx.xx.xx
  ports:
  - name: http2
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    seldon-app: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

https://github.com/SeldonIO/seldon-core/blob/9d7bc4932ac043e49854fadec7908189265d46dc/operator/controllers/seldondeployment_controller.go#L630
