### ISSUE TITLE
Shadow model gets no traffic

### ISSUE THREAD

**Issue by Nithinbs18** [SeldonIO/seldon-core#2225]
Dear team,

I am currently trying to deploy a shadow model using MLFLOW implementation, the deployment is successful but the shadow model fails to get any traffic into it.

Seldon version 1.2.2

  K8 manifest;
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: shadow-test
spec:
  name:   
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/a
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: default-a
      labels:
        test-nithin: nithin-a
      replicas: 1
      componentSpecs:
        - spec:
            containers:
              - name: classifier
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/b
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: default-b
      labels:
        test-nithin: nithin-b
      replicas: 1
      shadow: true
      componentSpecs:
        - spec:
            containers:
              - name: classifier
```
Sdep;
```
NAME              AGE
shadow-test   125m
```
Pods created;
```
NAME                                                                                     READY   STATUS    RESTARTS   AGE
shadow-test-default-a-0-classifier-75c6f884f5-sgnf8              2/2     Running         0          124m
shadow-test-default-b-0-classifier-6ccb79594b-wm6hf          2/2     Running         0          124m
```

After prediction on endpoint /seldon/default/shadow-test/api/v1.0/predictions;
```
kubectl logs shadow-test-default-a-0-classifier-75c6f884f5-sgnf8 -c classifier | grep "/predict" | wc -l
4899
kubectl logs shadow-test-default-b-0-classifier-6ccb79594b-wm6hf -c classifier | grep "/predict" | wc -l
0
```
Could you please suggest a solution for this.
Thank you very much in advance.

**Comment by cliveseldon** [comment]
Are you using istio or Ambassador as the ingress?
Can you check the created VirtualServices (istio) or Ambassador configuration?

**Comment by Nithinbs18** [comment]
Hi @cliveseldon ,
I use Ambassador I currently port-forward it and test on my dev system.
I installed it using the old stable chart;
```
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm install ambassador stable/ambassador --set crds.keep=false
```
standard and Canary deployment works absolutely fine with this installation I have issues running the shadow deployment.
When you say Ambassador configuration what exactly do you mean?
Thanks.

**Comment by cliveseldon** [comment]
On the old Ambassador there was a diagnostics page at http:/<ambassador-ip>/ambassador/v0/diag/
You can also check the SVCs created by Seldon to check they have the correct Ambassador config in the annotations

**Comment by Nithinbs18** [comment]
Hi @cliveseldon ,
The annotations are created correctly,
Main deployment svc;
```
annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: seldon_default_shadow-test_default-a_rest_mapping
      prefix: /seldon/default/shadow-test/
      rewrite: /
      service: shadow-test-default-a.default:8000
      timeout_ms: 3000
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: seldon_default_shadow-test_default-a_grpc_mapping
      grpc: true
      prefix: /(seldon.protos.*|tensorflow.serving.*)/.*
      prefix_regex: true
      rewrite: ""
      service: shadow-test-default-a.default:5001
      timeout_ms: 3000
```
Shadow model;
```
annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: seldon_default_shadow-test_default-b_rest_mapping
      prefix: /seldon/default/shadow-test/
      rewrite: /
      service: shadow-test-default-b.default:8000
      timeout_ms: 3000
      shadow: true
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: seldon_default_shadow-test_default-b_grpc_mapping
      grpc: true
      prefix: /(seldon.protos.*|tensorflow.serving.*)/.*
      prefix_regex: true
      rewrite: ""
      service: shadow-test-default-b.default:5001
      timeout_ms: 3000
```
But still, the shadow model fails to get any traffic into it. Is there any special method that we must use in case of a shadow deployment from the seldon-core python client?
Thanks.

**Comment by cliveseldon** [comment]
Have you tried curl rather than the python client to check it works there?

**Comment by Nithinbs18** [comment]
Hi @cliveseldon,

Thanks for the suggestion. I was trying the prediction from python client hence the shadow model did not receive the traffic, I tried it out with the postman and also using python-requests it works as expected.

```
import pandas as pd
import numpy as np
import requests
import json

df = pd.read_csv("./wine-quality.csv")


def _get_reward(y, y_pred):
    if y == y_pred:
        return 500
    return 1 / np.square(y - y_pred)


def _test_row(row):
    url = "http://localhost:8003/seldon/default/shadow-test/api/v1.0/predictions"
    headers = {
        'content-type': "application/json"
    }
    input_features = row[:-1]
    feature_names = input_features.index.to_list()
    X = input_features.values.reshape(1, -1)
    y = row[-1]
    payload = json.dumps(
        {"data": {"names": feature_names, "ndarray": X.tolist()}})
    response = requests.request("POST", url, data=payload, headers=headers)
    y_pred = ((json.loads(response.text))['data']['ndarray'])
    reward = _get_reward(y, y_pred)
    print(reward)


df.apply(_test_row, axis=1)
```

**Comment by Nithinbs18** [comment]
Hi @cliveseldon 

Is it possible to add more than one model in the shadow deployment?
Thanks.

**Comment by cliveseldon** [comment]
Yes you should be able to do this.

**Comment by Nithinbs18** [comment]
Hi @cliveseldon 

I tried to do this with 3 models using the below manifest but the traffic is directed to only the top 2 models, can you please suggest if something needs to be changed in the below YAML, 

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: shadow-test
spec:
  name: shadow-test
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/a
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: shadow-model-a
      replicas: 1
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/b
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: shadow-model-b
      replicas: 1
      shadow: true
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/c
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: shadow-model-c
      replicas: 1
      shadow: true
```

Thank you very much.
