### ISSUE TITLE
Authentication support for ELK

### ISSUE THREAD

**Issue by os-virtualretail** [SeldonIO/seldon-core#2298]
Our ELK endpoints are authenticated so  I used a sample sdp like

``` 
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-model-logging
  namespace: seldon-deploy            
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: classifier
      logger: 
        url: https://<USERNAME>:<PASSWORD>@df65d4b2795d481dbe235733219ca518.eu-central-1.aws.cloud.es.io:9243/
        mode: all
    name: default
    replicas: 1
    svcOrchSpec: 
      env: 
        - name: SELDON_LOG_LEVEL 
          value: DEBUG 
```

made a few curl post to Seldon API 

but 

curl  -u user:Pass   "https://df65d4b2795d481dbe235733219ca518.eu-central-1.aws.cloud.es.io:9243/_cat/indices"

does not return anything for seldon so requesting authentication support for ELK Logging.

User/Pass can be taken from a Kubernetes Secret.
