### ISSUE TITLE
TerminationGracePeriodSeconds not respected in CRD

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#2332]
## Describe the bug

TerminationGracePeriodSeconds not respected in CRD

## To reproduce

deploy

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: example
    replicas: 1
```

Pod will have `terminationGracePeriodSeconds: 20`

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

There are two parts of the code that have this hardwired:
https://github.com/SeldonIO/seldon-core/search?l=Go&q=TerminationGracePeriodSeconds
