### ISSUE TITLE
 SeldonCore and random 'upstream connect error or disconnect/reset before headersupstream connect error or disconnect/reset before headers' errors on /predictions

### ISSUE THREAD

**Issue by omerfsen** [SeldonIO/seldon-core#2347]
When using  AWS EKS I get random "upstream connect error or disconnect/reset before headersupstream connect error or disconnect/reset before headers" messages at /predictions 

AWS EKS: 1.17 (eks.2 , latest) 
Istio: 1.6.8 
Seldon: 1.2.3

After a certain period of time i start to get when i try to connect to ( it is random sometimes it happens after 1 day sometimes immediately but if it starts to happen only fix is to delete seldondeployment and redeploy)

```
 https://<URL>/seldon/seldon-deploy/iris-model/api/v1.0/predictions
```
For Example:

```bash
curl  -L -k -s https://<URL>/seldon/seldon-deploy/iris-model-debug/api/v1.0/predictions  -H "Content-Type: application/json" -d '{"data":{"ndarray":[[5.964,4.006,2.081,1.031]]}}'
```
I use 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: seldon-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cloud-serra
      mode: SIMPLE
```

i checked **istio-proxy** but got no error.

**upstream connect error or disconnect/reset before headersupstream connect error or disconnect/reset before headers** for all type of seldondeployment. I have downgraded to 1.2.2 and it worked fine. Yaml file i used is very simple:

```yaml
kind: SeldonDeployment
metadata:
  name: iris-model
  namespace: seldon-deploy            
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: classifier
    name: default
    replicas: 1
```

or just simple

```bash
helm install seldon-single-model seldonio/seldon-single-model -n seldon-deploy --set 'model.image=seldonio/mock_classifier_rest:1.3' --set model.logger.enabled=true  --set model.logger.url="http://seldon-request-logger.seldon-logs"
```

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]
