### ISSUE TITLE
models configured with REST endpoint in SeldonDeployment complex graph does not get an endpoint, only the last model is getting a REST endpoint

### ISSUE THREAD

**Issue by maorlipchuk** [SeldonIO/seldon-core#2375]
When trying to create a complex graph structure with models using a REST endpoint:
   ```
   name: stepone
      endpoint:
        type: REST
      type: MODEL
```

I noticed that only one endpoint is being discovered - The last container that is mentioned.

Here is the graph which I created based on https://docs.seldon.io/projects/seldon-core/en/latest/graph/inference-graph.html?highlight=graph#example-of-graph-with-pre-processor-and-post-processor 

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-model
  namespace: seldon-system
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: steptwo
          image: dockerhub/mymodel:1.0.2.27
        - name: stepone
          image: dockerhub/translator:1.0.0.1
    graph:
      name: stepone
      endpoint:
        type: REST
      type: MODEL
      children:
      - name: steptwo
        **endpoint:
          type: REST
        type: MODEL**
        children: []
    name: example
    replicas: 1

```

In this example you can see that the last container that is mentioned in containers **stepone** is exposed while **steptwo** although defined with REST API does not maintain an endpoint:

```
➜ k get endpoints
NAME                           ENDPOINTS                               AGE
seldon-model-example           xxx.xxx.xxx.xxx:8000,xxx.xxx.xxx.xxx:8000   22s
**seldon-model-example-stepone   xxx.xxx.xxx.xxx:9001                      47s**
seldon-model-example-steptwo   <none>                                  47s

```

**Second Experiment:**
If I switch the containers order you can notice that model steptwo now has a REST endpoint while stepone doesn't
Here is an opposite example when I switch the order of the containers stepone with steptwo in the template:
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-model
  namespace: seldon-system
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: stepone
          image: dockerhub/translator:1.0.0.1
        - name: steptwo
          image: dockerhub/mymodel:1.0.2.27
    graph:
      name: stepone
      endpoint:
        type: REST
      type: MODEL
      children:
      - name: steptwo
        endpoint:
          type: REST
        type: MODEL
        children: []
    name: example
    replicas: 1
```

```
➜ k get endpoints
NAME                           ENDPOINTS                               AGE
seldon-model-example           xxx.xxx.xxx.xxx:8000,xxx.xxx.xxx.xxx:8000   54s
seldon-model-example-stepone   <none>                                  79s
seldon-model-example-steptwo   xxx.xxx.xxx.xxx:9001                      79s
seldon-webhook-service         10.110.66.163:443                       49d
```

 All models defined with REST endpoint should get endpoints

**Comment by yinondn** [comment]
In your `componentSpecs` section try defining a spec for each model, like this:
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: test-replicas
spec:
  replicas: 1
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier2
      replicas: 3
    graph:
      endpoint:
        type: REST
      name: classifier
      type: MODEL
      children:
      - name: classifier2
        type: MODEL
        endpoint:
          type: REST
    name: example
    replicas: 2
    traffic: 50
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier3
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier3
      type: MODEL
    name: example2
    traffic: 50
```
https://docs.seldon.io/projects/seldon-core/en/latest/graph/scaling.html
