### ISSUE TITLE
Unable to add more than one model in shadow deployment

### ISSUE THREAD

**Issue by Nithinbs18** [SeldonIO/seldon-core#2383]
Dear team,

Greetings!!

I am using seldon core 1.2.3 with the ambassador and trying to do a shadow deployment with one initial model and 2 shadow models, but unfortunately, the traffic won't reach other models except for the 1st shadow model for instance if I have a shadow deployment with models A as my initial model and B, C being my shadow model the traffic only is directed to A, B and model C gets no traffic. Could you please suggest me if anything is wrong in the below manifest.

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: shadow-test
spec:
  name: shadow-test
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/a
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: shadow-model-a
      replicas: 1
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/b
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: shadow-model-b
      replicas: 1
      shadow: true
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://seldon/c
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: shadow-model-c
      replicas: 1
      shadow: true
```
I am trying to do a shadow deployment with up to 10 models.

Thank you very much in advance.
