### ISSUE TITLE
requestPath meta missing in new executor

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2505]
Legacy `engine` used to set meta field `request.Path` that is missing in `executor`.
Example of payload differences may be find in this issue: https://github.com/SeldonIO/seldon-core/issues/1474

**Comment by Isaacwhyuenac** [comment]
I would also appreciate adding back the requestPath information which is somehow lost after the engine replaced its Spring boot server to gorilla mux.
https://github.com/SeldonIO/seldon-core/pull/246/files

**Comment by RafalSkolasinski** [comment]
I believe `Spring boot` -> `gorilla mux` is just replacing Java based Engine with Golang based Executor so basically the same as spirit of this issue.

**Comment by RafalSkolasinski** [comment]
On this specific issue, I have the feeling that almost the same functionality can be achieved on model side with a minimal implementation in the model:

model:
```python
import os


UNIT_ID = os.environ.get("PREDICTIVE_UNIT_ID", "???")
MODEL_IMAGE = os.environ.get("PREDICTIVE_UNIT_IMAGE", "???")


class Model:
    def predict(self, features, names=[], meta=[]):
        print(features)
        return features

    def tags(self):
        return {f"requestPath:{UNIT_ID}": MODEL_IMAGE}
```

deployment.yaml:

```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-mock-model
spec:
  name: mock-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: mock-model:latest
          imagePullPolicy: IfNotPresent
          name: model-1

        - image: mock-model:latest
          imagePullPolicy: IfNotPresent
          name: model-2
    graph:
      name: model-1
      type: MODEL
      children:
      - name: model-2
        type: MODEL
    name: default
    replicas: 1
```

test:

```bash
❯❯❯ make request
curl -s -H 'Content-Type: application/json' \
	-d '{"meta": {"tags": {"foo": "bar"}}, "data": {"names": ["input"], "ndarray": ["data"]}}' \
	http://localhost:8003/seldon/seldon/seldon-mock-model/api/v1.0/predictions  | jq .
{
  "data": {
    "names": [],
    "ndarray": [
      "data"
    ]
  },
  "meta": {
    "tags": {
      "foo": "bar",
      "requestPath:model-1": "mock-model:latest",
      "requestPath:model-2": "mock-model:latest"
    }
  }
}
```




This however does not solve problem for prepackaged model servers.
