### ISSUE TITLE
rename service port names to conform istio standarts

### ISSUE THREAD

**Issue by omerfsen** [SeldonIO/seldon-core#2542]
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

Istio supports proxying all TCP traffic by default, but in order to provide additional capabilities, such as routing and rich metrics, the protocol must be determined. This can be done automatically or explicitly specified.

So on a SeldonDeployment like:

```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: test
spec:
  name: deployment-rest
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: TRACING
            value: '1'
          - name: JAEGER_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JAEGER_AGENT_PORT
            value: '5775'
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: '1'
          - name: SELDON_LOG_LEVEL #This is for request/response logging
            value: DEBUG
          image: seldonio/mock_classifier_rest:1.2.2
          name: model1
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      endpoint:
        type: REST
      name: model1
      type: MODEL
      logger: 
        url: http://seldon-request-logger.seldon-logs
        mode: all
    name: tracing
    replicas: 1
    svcOrchSpec:
      env:
      - name: TRACING
        value: '1'
      - name: JAEGER_SAMPLER_TYPE
        value: const
      - name: JAEGER_SAMPLER_PARAM
        value: '1'
      - name: JAEGER_AGENT_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: JAEGER_AGENT_PORT
        value: '5775'
      - name: SELDON_LOG_LEVEL  #This is for request/response logging
        value: DEBUG 

```

We will have 2 services created:

```bash
kubectl get svc -n dev
NAME                  TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
test-tracing          ClusterIP   10.12.16.75   <none>        8000/TCP,5001/TCP   103m
test-tracing-model1   ClusterIP   10.12.24.19   <none>        9000/TCP            105m
```

And their port names are

**kubectl get svc -n dev test-tracing -o yaml**

```yaml
....
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http2
    port: 5001
    protocol: TCP
    targetPort: 8000
....
```

and 

**kubectl get svc -n dev test-tracing-model1 -o yaml**

```yaml
...
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
...
```
