### ISSUE TITLE
An Arch Design issue about the container service

### ISSUE THREAD

**Issue by msyesyan** [SeldonIO/seldon-core#2573]
## Describe the bug

When I was reading the source code of the operator, I found some problems. 

We will generate a service for each container defined in the graph, and use the same serviceKey to bind to the pod, then the latter container service will overwrite the previous service. As a result, the previous service will lose its pod binding relationship, and cannot be directly accessed.

Of course, if you use the executor directly, this does not affect the use, I just think this implementation is problematic. Maybe we can agree in the document that a componentSpecs only defines one container that will appear in the graph?

## To reproduce

an example:

```
# test.yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: msinfcustom
  namespace: inftest
spec:
  predictors:
    - name: v1
      replicas: 1
      componentSpecs:
        - spec:
            containers:
              - name: model
                 image: {anyimage}
              - name: model2
                 image: {anyimage}
      graph:
        name: model
        type: MODEL
        children:
          name: model2
```

when we create such kind of a seldondeployment, you will see there are three the services generated, one executor service and two model service, and the frist model service cannot be used because its matchLabels has been overwrited by the model2 service 

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]
