### ISSUE TITLE
ability to specify init container on per deployment basis

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2611]
Currently init containers can only be specified globally. It would be good if one can specify init container on per deployment basis.

**Comment by cliveseldon** [comment]
You can add your own initContainer in the connected PodSpec. But if you are using a prepackaged server you will still get its initContainer added by default which may conflict.

**Comment by RafalSkolasinski** [comment]
Actually, tested it just now and I only got one init container with prepackaged server. This is most probably because name matched the pattern. The example I came up with is
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: example-test
spec:
  name: iris
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location
            readOnly: true
    
        initContainers:
        - name: classifier-model-initializer
          image: rafalskolasinski/storage-initializer:v0.4.0
          imagePullPolicy: IfNotPresent
          args:
          - s3://sklearn/iris
          - /mnt/models
    
          envFrom:
          - secretRef:
              name: seldon-init-container-secret
    
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
    
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location
    
        volumes:
        - emptyDir: {}
          name: classifier-provision-location
    
    graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: s3://sklearn/iris
      name: classifier
    name: default
    replicas: 1
```

(which only customises the secret and image)

**Comment by RafalSkolasinski** [comment]
Adding above example as part of https://github.com/SeldonIO/seldon-core/issues/2055 should solve this issue.

**Comment by RafalSkolasinski** [comment]
Thinking about it more, we should consider this issue close only when it will be possible to specify image used for initContainer per deployment in a more elegant fashion than above.

**Comment by RafalSkolasinski** [comment]
To be precise, I would like to allow users to be able to specify a following
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: sklearn-default-init-container
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      envSecretRefName: seldon-init-container-secret      
      storageInitializerImage: seldonio/storage-initilizer-image:1.6.0
      name: classifier
    name: default
    replicas: 1
```

With the assumption that all valid init container images provided these way would take two arguments:
- source
- destination
