### ISSUE TITLE
[BUG] NodeSelector not working in SeldonDeployment

### ISSUE THREAD

**Issue by WaterKnight1998** [SeldonIO/seldon-core#2682]
## Describe the bug
I am applying a Deployment that uses NodeSelector to select in which node run the model: gpu or cpu ones.

The yaml looks as follows:
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: deploy-1
  namespace: seldon
  labels:
spec:
  name: deploy-1
  protocol: seldon
  transport: rest
  annotations:
  predictors:
    - name: "default"
      graph:
        name: "model"
        implementation: MLFLOW_SERVER
        serviceAccountName: ****
        modelUri: gs://****
        type: "MODEL"
      componentSpecs:
      - spec:
        containers:
          - name: "model"
            image:
            imagePullPolicy:
            env:
              name: "LOG_LEVEL"
              value: "INFO"
            resources:
              requests:
                memory: 1Mi
        nodeSelector:
          cloud.google.com/gke-nodepool: gpu-node-pool
      replicas: 1
```

## Expected behaviour
The deployment should use NodeSelector. However, it is getting removed!

## Environment

<!-- You Can fill it manually or paste the output of the command below:

* Cloud Provider: [e.g. GKE, AWS, Bare Metal, Kind, Minikube]: GKE
* Kubernetes Cluster Version [Output of `kubectl version`] : 
  ```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
  ```
* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]

  ```
          value: docker.io/seldonio/engine:1.4.0
          value: docker.io/seldonio/seldon-core-executor:1.4.0
        image: docker.io/seldonio/seldon-core-operator:1.4.0
  ````

**Comment by cliveseldon** [comment]
I ran the following against 1.5.0-dev and it worked after labelling one of the nodes to `seldon=true`

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
        nodeSelector:
          seldon: "true"
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: example
    replicas: 1
```
