### ISSUE TITLE
Improve docs in configuring Storage Initialiser using Service Accounts 

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2761]
Current docs on configuring InitContainers to use S3 credentials from secrets via Service Accounts are quite confusing. 
They should be improved  to include:
- example of the secret format (link to kfserving that is [here](https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html#adding-credentials-for-google-cloud) is dead). To see where it lead go to [v0.4.1](https://github.com/kubeflow/kfserving/tree/v0.4.1/docs/samples/s3)
- highlight why using SA would be better / required in favour of just specifying `envSecretRefName`

**Comment by RafalSkolasinski** [comment]
Full exmaple (for in-cluster MinIO)
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-sa
secrets:
  - name: minio-sa-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-sa-secret
  annotations:
     machinelearning.seldon.io/s3-endpoint: minio.minio-system.svc.cluster.local:9000
     machinelearning.seldon.io/s3-usehttps: "0"
type: Opaque
stringData:
  awsAccessKeyID: "minioadmin"
  awsSecretAccessKey: "minioadmin"
```
