### ISSUE TITLE
Allow ambassador from other namespace to access SeldonDeployment

### ISSUE THREAD

**Issue by ChenyuanZ** [SeldonIO/seldon-core#279]
Hi there,

`ambassador` is a popular kubernetes-native API gateway. I would like to use an `ambassador` installed by k8s admin, which locates at a different namespace from `seldon-core` namespace, to route traffic to the `SeldonDeployments`. This is to reduce the number of `ambassadors` we install in the cluster.

To support this feature, we can simply add `namespace` in the service annotation generated by Seldon cluster manager. I have manually tested this change and it works. E.g.
```
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  seldon_seldon-deployment-output-transformer_rest_mapping
      prefix: /seldon/seldon-deployment-output-transformer/
      service: test-output-transformer.seldon:8000
      timeout_ms: 3000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  seldon-deployment-output-transformer_grpc_mapping
      grpc: true
      prefix: /seldon.protos.Seldon/
      rewrite: /seldon.protos.Seldon/
      headers:
        seldon: seldon-deployment-output-transformer
      service: test-output-transformer.seldon:5001
      timeout_ms: 3000
```
This requires source code change at
https://github.com/SeldonIO/seldon-core/blob/master/cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentOperatorImpl.java#L502-L519

Reference: https://www.getambassador.io/reference/mappings/#namespaces-and-mappings

Best,
Chenyuan
