### ISSUE TITLE
ArgoCD OutOfSync if SeldonDeployment includes mountpoint

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2811]
## Describe the bug

In GitOps with `ArgoCD` setup if `SeldonDeployment` contains mountpoint argo reports incorrect `OutOfSync` error.
This goes away if one include
```yaml
  ignoreDifferences:
  - group: machinelearning.seldon.io
    kind: SeldonDeployment
    jsonPointers:
    - /spec/predictors/0/componentSpecs/0/spec/containers/0/volumeMounts
```
in the `Application` definition.

See [argocd diffing customisation](https://argoproj.github.io/argo-cd/user-guide/diffing/).

## To reproduce

1. Install SC and ArgoCD
2. Create following PVC
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: gitops-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```
3. Add following deployment via gitops
```yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: sklearn
spec:
  name: iris
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          resources:
            requests:
              memory: 50Mi
          volumeMounts:
          - name: pvc-storage
            mountPath: /new-pvc-location
        volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: test-pvc

    graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: classifier
    name: default
    replicas: 1
```

Observe incorrect `OutOfSync` state.

## Expected behaviour

ArgoCD does not report diff.

## Environment

SC 1.5.x with ArgoCD 1.7.x or 1.8.x.

## Model Details 

![image](https://user-images.githubusercontent.com/10928117/103575101-0c7f6280-4ec9-11eb-86ec-a3143cf8daeb.png)

**Comment by RafalSkolasinski** [comment]
Temporary workaround is to add
```
  ignoreDifferences:
  - group: machinelearning.seldon.io
    kind: SeldonDeployment
    jsonPointers:
    - /spec/predictors/0/componentSpecs/0/spec/containers/0/volumeMounts
```
to the argo `application` resource as per [argocd documentation](https://argoproj.github.io/argo-cd/user-guide/diffing/).

Problem will be solved by  resolving https://github.com/SeldonIO/seldon-core/issues/2817.
