### ISSUE TITLE
Manual scale doesn't work if hpaSpec is set

### ISSUE THREAD

**Issue by stingshen** [SeldonIO/seldon-core#2816]
## Describe the bug

Manual scale doesn't work if hpaSpec is set.

## To reproduce

Apply the following yaml to k8s:
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  replicas: 5
  predictors:
  - componentSpecs:
    - hpaSpec:
        maxReplicas: 3
        metrics:
        - resource:
            name: cpu
            targetAverageUtilization: 10
          type: Resource
        minReplicas: 1
      replicas: 2
      spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          imagePullPolicy: IfNotPresent
          name: classifier
          resources:
            requests:
              cpu: '0.2'
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: example
```

Manual replica setting doesn't work. There is only one replica created.

## Expected behaviour

There are 2 replicas created.

## Environment

seldon 1.3.0 with K8s 1.18.4
