### ISSUE TITLE
cannot overwrite initContainers image: reconcile error

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2821]
## Describe the bug

Operator fails to create deployments that overwrite image of Storage Initializer: init container.e

```bash
│   Type     Reason         Age                   From                       Message                                                                         │
│   ----     ------         ----                  ----                       -------                                                                         │
│   Normal   CreateService  17m                   seldon-controller-manager  Created Service "custom-init-image-default-classifier"                          │
│   Warning  InternalError  6m28s (x18 over 17m)  seldon-controller-manager  Deployment.apps "custom-init-image-default-0-classifier" is invalid: spec.templ │
│ ate.spec.containers[0].volumeMounts[1].name: Not found: "classifier-provision-location"  
```

## To reproduce
1. Define and apply following model
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: custom-init-image
spec:
  name: iris
  predictors:
  - componentSpecs:
    - spec:
        initContainers:
        - name: classifier-model-initializer
          image: seldonio/storage-initializer:v1.6.0
    graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: classifier
    name: default
    replicas: 1
```

## Expected behaviour

Behaviour equivalent to 
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: sklearn-default-init-container
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      envSecretRefName: seldon-init-container-secret      
      name: classifier
    name: default
    replicas: 1
```

with Seldon installed with following helm value:
```yaml
storageInitializer:
  image: seldonio/rclone-init-container:latest
```

## Environment

* Cloud Provider: [any]
* Kubernetes Cluster Version [any] 
* Deployed Seldon System Images: [current master]

**Comment by RafalSkolasinski** [comment]
Hmmm... Currently it seems that it is explicit design choice 
https://github.com/SeldonIO/seldon-core/blob/23d7dc5a0cf50d3aa642b25161d7e7176b6b9816/operator/controllers/model_initializer_injector.go#L142-L149
to not inject init container if one is already provided. 

Somehow I have the feeling that if people would like to overwrite more than just the image for init containers it was implied that better solution is for them to provide full definition. 

Maybe for now we could extend graph definition to include `storageInitializerImage`:
```yaml
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      envSecretRefName: seldon-init-container-secret      
      storageInitializerImage: init-container-image:latest
      name: classifier
```
that would overwrite helm-provided value  via
```yaml
storageInitializer:
  image: seldonio/rclone-init-container:latest
```
in the same way the `envSecretRefName` overwrites
```yaml
predictiveUnit:
  defaultEnvSecretRefName: ""
```

Just conscious this could be easier/smaller change and avoid introducing complicated merging logic into the https://github.com/SeldonIO/seldon-core/blob/23d7dc5a0cf50d3aa642b25161d7e7176b6b9816/operator/controllers/model_initializer_injector.go#L114
function.

Any thoughts @cliveseldon?
