### ISSUE TITLE
error: a container name must be specified for pod 

### ISSUE THREAD

**Issue by jax79sg** [SeldonIO/seldon-core#2875]
## Describe the bug
My deployment doesn't seem to start and when checking the logs of the pod, i see this.
```
kubectl logs  sklearn-default-0-classifier-bbccfbdf9-d6v8r -n default
error: a container name must be specified for pod sklearn-default-0-classifier-bbccfbdf9-d6v8r, choose one of: [classifier seldon-container-engine] or one of the init containers: [classifier-model-initializer]
```

This is a view of all running pods.
```
kubectl get pods -A
NAMESPACE        NAME                                           READY   STATUS             RESTARTS   AGE
ambassador       ambassador-588f9ff95d-2rkf8                    1/1     Running            4          22h
ambassador       ambassador-redis-584cd89b45-4d49f              1/1     Running            4          22h
cert-manager     cert-manager-744fdd4d96-n9w2d                  1/1     Running            5          22h
cert-manager     cert-manager-cainjector-868b4b477c-zcfj8       1/1     Running            5          22h
cert-manager     cert-manager-webhook-6c88bc4cb8-5mxd6          1/1     Running            4          22h
default          sklearn-default-0-classifier-bbccfbdf9-d6v8r   0/2     Init:0/1           0          5m40s
kube-system      coredns-f9fd979d6-g6wjq                        1/1     Running            11         2d5h
kube-system      coredns-f9fd979d6-j824k                        1/1     Running            11         2d5h
kube-system      etcd-kubenode1                                 1/1     Running            12         2d5h
kube-system      kube-apiserver-kubenode1                       1/1     Running            12         2d5h
kube-system      kube-controller-manager-kubenode1              1/1     Running            13         2d5h
kube-system      kube-flannel-ds-47mc7                          1/1     Running            0          22m
kube-system      kube-flannel-ds-8v5rr                          1/1     Running            15         2d5h
kube-system      kube-proxy-5dk22                               1/1     Running            0          22m
kube-system      kube-proxy-b25wr                               1/1     Running            12         2d5h
kube-system      kube-scheduler-kubenode1                       1/1     Running            13         2d5h
kube-system      nvidia-device-plugin-daemonset-r4zwf           0/1     CrashLoopBackOff   456        2d5h
kube-system      nvidia-device-plugin-daemonset-wbglv           1/1     Running            0          21m
kube-system      seldon-spartakus-volunteer-5b57b95596-mhfd4    1/1     Running            0          13m
metallb-system   controller-b4df945f8-z6mvq                     1/1     Running            4          22h
metallb-system   speaker-8xmtt                                  1/1     Running            5          22h
metallb-system   speaker-hwxsx                                  1/1     Running            0          21m
seldon-system    seldon-controller-manager-7f5d7bbb75-9frrd     1/1     Running            0          13m
```

## To reproduce

1. Create a yaml file with following content.
```
cat sklearn.yaml 
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: sklearn
spec:
  name: digit-predict
  protocol: kfserving
  predictors:
  - graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: s3://192.168.56.109:9000/minio/models/digits.joblib
      name: classifier
      parameters:
        - name: method
          type: STRING
          value: predict
    name: default
    replicas: 1
```
The joblib file is from a trained sklearn model.

## Environment

* Cloud Provider: [Bare Metal]
* Kubernetes Cluster Version [Output of `kubectl version`] 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]
```
          value: docker.io/seldonio/engine:1.5.1
          value: docker.io/seldonio/seldon-core-executor:1.5.1
        image: docker.io/seldonio/seldon-core-operator:1.5.1

```
