### ISSUE TITLE
Ambassador config for rolling updates

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#294]
When doing a rolling update of a model the kubernetes endpoint might change and requests passing through ambassador should handle the new ip-address without service-504 errors. One suggestion from Ambassador Slack channel is to use an Ambassador config like:

```
     timeout_ms: 0
     envoy_override:
       retry_policy:
         retry_on: connect-failure
         num_retries: 4
```

This needs to be tested and if works we should decide if its added by default.
