### ISSUE TITLE
https/ssl issues with kfctl_istio_dex.v1.2.0 on tutorial example

### ISSUE THREAD

**Issue by duyttran** [SeldonIO/seldon-core#3020]
## Describe the bug

More details on [debugging here](https://seldondev.slack.com/archives/C8Y9A8G0Y/p1614954302161200) at a high level I'm having issues with the basic seldon example probably due to some https / authentication issues
 - using kfctl_istio_dex.v1.2.0
 - following [example here](https://www.kubeflow.org/docs/components/serving/seldon/)
 - passing through the cookie through curl from after logging into the kubeflow dashboard

## To reproduce
1. kfctl_istio_dex.v1.2.0 [kubeflow install](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/)
 - note we have it setup with github logins, and the dashboard UI works at this point
 - from here on I've already logged in through the kubeflow dashboard UI and create a namespace duy-tran which is where I'll deploy things
2. apply seldon deployment from [tutorial here](https://www.kubeflow.org/docs/components/serving/seldon/)

```
cat <<EOF | kubectl apply -n duy-tran -f -
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: example
    replicas: 1
EOF
```
3. verified the virtual service is using the correct gateway.

the gateway looks like this

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  generation: 1
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*'
      port:
        number: 443
        name: https-443
        protocol: HTTP
```

the virtual services brought up are using that gateway

```
kubectl get virtualservices -n duy-tran
NAME                         GATEWAYS                      HOSTS   AGE
notebook-duy-tran-duy-test   [kubeflow/kubeflow-gateway]   [*]     2d19h
seldon-model-grpc            [kubeflow/kubeflow-gateway]   [*]     7h46m
seldon-model-http            [kubeflow/kubeflow-gateway]   [*]     7h46m
```

4. I port forward the istio gateway to 8004 per the tutorial

```
kubectl port-forward $(kubectl get pods -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}') -n istio-system 8004:80
```

5. I grab the cookie from my browser as indicated in [tutorial here](https://docs.seldon.io/projects/seldon-core/en/stable/examples/seldon_client.html)

6. I curl and get the following

```
curl -vvv -L -s -d '{"data": {"ndarray":[[1.0, 2.0, 5.0]]}}' \
 -X POST http://localhost:8004/seldon/duy-tran/seldon-model/api/v1.0/predictions \
 -H "Content-Type: application/json" \
 -H 'Cookie: authservice_session=<redacted-cookie>'
*   Trying ::1:8004...
* Connected to localhost (::1) port 8004 (#0)
> POST /seldon/duy-tran/seldon-model/api/v1.0/predictions HTTP/1.1
> Host: localhost:8004
> User-Agent: curl/7.72.0
> Accept: */*
> Content-Type: application/json
> Cookie: authservice_session=<redacted-cookie>
> Content-Length: 39
>
* upload completely sent off: 39 out of 39 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< location: https://localhost:8004/seldon/duy-tran/seldon-model/api/v1.0/predictions
< date: Fri, 05 Mar 2021 17:21:26 GMT
< server: istio-envoy
< connection: close
< content-length: 0
<
* Closing connection 0
* Issue another request to this URL: 'https://localhost:8004/seldon/duy-tran/seldon-model/api/v1.0/predictions'
* Switch from POST to GET
* Hostname localhost was found in DNS cache
*   Trying ::1:8004...
* Connected to localhost (::1) port 8004 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /nix/store/vfwbn4w1swqlhfck34y4s2c1h7yf1hy7-nss-cacert-3.56/etc/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 1
```
7. if I remove the following line from the gateway it seems to work

```
      tls:
        httpsRedirect: true
```

the only other configuration i'd like to note is the ClusterRbacConfiguration i had to turn OFF

```
Name:         default
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  rbac.istio.io/v1alpha1
Kind:         ClusterRbacConfig
Metadata:
  Creation Timestamp:  2021-03-02T18:26:05Z
  Generation:          5
  Resource Version:    30974915
  Self Link:           /apis/rbac.istio.io/v1alpha1/clusterrbacconfigs/default
  UID:                 5b02a5f0-97fe-4b31-bb75-50e6dd8f56ff
Spec:
  Mode:  OFF
Events:  <none>
```

before it was

```
describe ClusterRbacConfig default --all-namespaces
Name:         default
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  rbac.istio.io/v1alpha1
Kind:         ClusterRbacConfig
Metadata:
  Creation Timestamp:  2021-02-19T00:53:54Z
  Generation:          1
  Resource Version:    15047071
  Self Link:           /apis/rbac.istio.io/v1alpha1/clusterrbacconfigs/default
  UID:                 9a4ed728-db13-46d0-baeb-5871e734b0e7
Spec:
  Exclusion:
    Namespaces:
      istio-system
  Mode:  ON_WITH_EXCLUSION
Events:  <none>
```

## Expected behaviour
the curl request in step 6 should return a response with the prediction.

when I portforward the service/pod i can get output, but not through the istio/ingress

## Environment

* Cloud Provider: AWS, k8s self managed (not EKS)
* Kubernetes Cluster Version [Output of `kubectl version`] 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]

Alternatively run `echo "#### Kubernetes version:\n $(kubectl version) \n\n#### Seldon Images:\n$(kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio)"`
-->

^ the seldon version doesn't return things. its the one that should come with kubeflow 1.2

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]
