### ISSUE TITLE
HTTP Port Not Change even after PREDICTIVE_UNIT_SERVICE_PORT set

### ISSUE THREAD

**Issue by fahadh4ilyas** [SeldonIO/seldon-core#3035]
## Describe the bug

I tried to make simple seldon deployment with one transformer and one model. This is how it looks

```yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: "seldon-deployment"
  namespace: test
spec:
  annotations:
    project_name: Sample Pipeline
    deployment_version: v1
  name: "seldon-deployment"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sample_transformer
          imagePullPolicy: IfNotPresent
          name: textmaker
        - image: sample_predictor
          imagePullPolicy: IfNotPresent
          name: modelmaker
        terminationGracePeriodSeconds: 20
    graph:
      children:
      - name: modelmaker
        endpoint:
          type: REST
        type: MODEL
        children: []
      name: textmaker
      endpoint:
        type: REST
      type: TRANSFORMER
    name: single-model
    replicas: 1
    annotations:
      predictor_version: v1
```

Yet, when I deploy it on minikube, the container of `modelmaker` keeps exit with code 1. Here is the log

```
[2021-03-10 01:34:37 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2021-03-10 01:34:37 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2021-03-10 01:34:37 +0000] [1] [ERROR] Retrying in 1 second.
[2021-03-10 01:34:38 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2021-03-10 01:34:38 +0000] [1] [ERROR] Retrying in 1 second.
[2021-03-10 01:34:39 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2021-03-10 01:34:39 +0000] [1] [ERROR] Retrying in 1 second.
[2021-03-10 01:34:40 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2021-03-10 01:34:40 +0000] [1] [ERROR] Retrying in 1 second.
[2021-03-10 01:34:41 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2021-03-10 01:34:41 +0000] [1] [ERROR] Retrying in 1 second.
[2021-03-10 01:34:42 +0000] [1] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2021-03-10 01:34:42 +0000] [41] [INFO] Handling signal: term
[2021-03-10 01:35:12 +0000] [41] [INFO] Shutting down: Master
```

It seems like the container of `modelmaker` keep trying to use port 9000 even though the environment variable `PREDICTIVE_UNIT_SERVICE_PORT` is set to 9001.

## To reproduce

Here is `Dockerfile` of `sample_transformer` and `sample_predictor` image respectively

```
FROM python:3.6-slim
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000

# Define environment variable
ENV MODEL_NAME Transformer
ENV SERVICE_TYPE TRANSFORMER
ENV PERSISTENCE 0

CMD exec seldon-core-microservice $MODEL_NAME --service-type $SERVICE_TYPE --persistence $PERSISTENCE
```
```
FROM python:3.6-slim
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000

# Define environment variable
ENV MODEL_NAME Transformer
ENV SERVICE_TYPE MODEL
ENV PERSISTENCE 0

CMD exec seldon-core-microservice $MODEL_NAME --service-type $SERVICE_TYPE --persistence $PERSISTENCE
```

And here are the inside of Transformer file
```python
class Transformer:

    def __init__(self):

        pass
        

    def transform_input(self, X, names = None, meta = None):

        print('Transformed successfully')
        print('X:', X)
        print('names:', names)
        print('meta:', meta)

        return X

```
```python
class Transformer:

    def __init__(self):

        pass
        

    def predict(self, X, names = None, meta = None):

        print('Predicted successfully')
        print('X:', X)
        print('names:', names)
        print('meta:', meta)

        return X

```

## Expected behaviour

Seldon Deployment running without container's port overlapped.

## Environment

* Cloud Provider: Minikube
* Kubernetes Cluster Version: 1.20
* Deployed Seldon System Images: docker.io/seldonio/seldon-core-operator:1.4.0
