### ISSUE TITLE
Meta parameter did not passed to next model

### ISSUE THREAD

**Issue by fahadh4ilyas** [SeldonIO/seldon-core#3050]
## Describe the bug

I have 2 model, the first one is transformer and the second one is predictor. For the first model, I don't need meta parameter, but the second one must use meta parameter. But, when I send POST request with meta parameter, only the first model receive the parameter and not passed it to second model.

## To reproduce

Here is the inside of python script wrapped in first model
```python
class Transformer:

    def __init__(self):

        pass
        

    def transform_input(self, X, names = None, meta = None):

        print('Transformed successfully')
        print('X:', X)
        print('names:', names)
        print('meta:', meta)

        return X
```
And here is inside second model
```python
class Transformer:

    def __init__(self):

        pass
        

    def predict(self, X, names = None, meta = None):

        print('Predicted successfully')
        print('X:', X)
        print('names:', names)
        print('meta:', meta)

        return X
```

And here is the POST request using curl
```bash
curl -X POST \
-H 'Content-Type: application/json' \
-d '{"data": {"ndarray": [[1,2,3,4]]}, "meta": {"type": "sample"}}'
```

## Expected behaviour

The second model must print like this
```
Predicted succesfully
X: [[1 2 3 4]]
names: ['t:0', 't:1', 't:2', 't:3']
meta: {'type': 'sample'}
```
And the json respond of the request must be like this
```json
{"data":{"names":["t:0","t:1","t:2","t:3"],"ndarray":[[1,2,3,4]]},"meta":{"type":"sample"}}
```

## Environment

* Cloud Provider: Minikube
* Kubernetes Cluster Version: 1.20
* Deployed Seldon System Images: docker.io/seldonio/seldon-core-operator:1.4.0

## Model Details

Here is yaml file of `SeldonDeployment`
```yaml
---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-deployment
spec:
  annotations:
    project_name: Sample Pipeline
    deployment_version: v1
  name: pipeline-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sample_transformer
          imagePullPolicy: IfNotPresent
          name: transformer
        - image: sample_predictor
          imagePullPolicy: IfNotPresent
          name: predictor
    graph:
      name: transformer
      type: TRANSFORMER
      endpoint:
        type: REST
      children:
      - name: predictor
        type: MODEL
        endpoint:
          type: REST
    name: pipeline-deployment
    replicas: 1
    annotations:
      predictor_version: v1
```

Logs of first model
```
Transformed successfully
X: [[1 2 3 4]]
names: []
meta: {'type': 'sample'}
127.0.0.1 - - [12/Mar/2021:07:22:44 +0000] "POST /transform-input HTTP/1.1" 200 77 "-" "curl/7.68.0"
```

Logs of second model
```
Predicted succesfully
X: [[1 2 3 4]]
names: ['t:0', 't:1', 't:2', 't:3']
meta: {}
127.0.0.1 - - [12/Mar/2021:07:22:44 +0000] "POST /predict HTTP/1.1" 200 77 "-" "curl/7.68.0"
```
