### ISSUE TITLE
storageInitializerImage does not work on Kubernetes 1.18

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#3087]
## Describe the bug

Newly added option to specify `storageInitializerImage` directly on the Seldon Deployment does not work on Kubernetes 1.18. 

## To reproduce

1. Install SC 1..7.0 on Kubernetes 1.18
2. Go through custom init container [notebook](https://docs.seldon.io/projects/seldon-core/en/latest/examples/custom_init_container.html)
3. Observe failure when deploying
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rclone-as-default-init-container
spec:
  name: iris
  predictors:
  - name: default
    replicas: 1
    graph:
      name: classifier
      implementation: SKLEARN_SERVER
      modelUri: mys3:sklearn/iris
      storageInitializerImage: seldonio/rclone-init-container-example:0.1
      envSecretRefName: seldon-rclone-secret
```
with error message
```
error: error validating "models/rclone-sklearn.yaml": error validating data: ValidationError(SeldonDeployment.spec.predictors[0].graph): unknown field "storageInitializerImage" in io.seldon.machinelearning.v1.SeldonDeployment.spec.predictors.graph; if you choose to ignore these errors, turn validation off with --validate=false
```

Note: works fine on k8s 1.17.

## Expected behaviour

It also works on k8s 1.18.

## Environment

* Cloud Provider: [Kind]
* Kubernetes Cluster Version [1.18] 
* Deployed Seldon System Images: [1.7.0 images]
