### ISSUE TITLE
Seldon Deployment errors when graph does not have a type field

### ISSUE THREAD

**Issue by kylebluenote** [SeldonIO/seldon-core#3105]
## Describe the bug

Deploying a custom inference image without having `spec.predictors.componentSpecs.graph.endpoint.type` fails with an unhelpful error message (`runtime error: invalid memory address or nil pointer dereference  `)

## To reproduce

(using seldon-core 1.7):
1. Start new minikube env
2. install ambassador oss in ambassador namespace per https://www.getambassador.io/docs/latest/topics/install/install-ambassador-oss/#helm
3. Install seldon with helm: helm install seldon-core seldon-core-operator   --repo https://storage.googleapis.com/seldon-charts   --set usageMetrics.enabled=true   --namespace seldon-system   --set ambassador.enabled=true
4. Build very basic test model:
```
(master) cat MyModel.py 
class MyModel(object):
    def __init__(self)
        print("Initializing")
    def predict(self,X,features_names):
        print("Predict called - will run identity function")
        return X * 2
```
5. Build as image: `s2i build . seldonio/seldon-core-s2i-python3:0.18 doubler:latest`
6. Deploy using the following yaml
```
kind: SeldonDeployment
metadata:
  name: doubler
  namespace: model-namespace
spec:
  name: doubler
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: predictor
          image: doubler:latest
    graph:
      name: predictor
    name: default
    replicas: 1
```

## Expected behaviour

This was solved by modifying the deployment yaml to have a graph type, similar to
```
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier:1.5.0
          name: classifier
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: example
    replicas: 1
```
I would expect the error code to indicate that there is a missing field.

## Environment

* Cloud Provider: Minikube
* Kubernetes Cluster Version [Output of `kubectl version`] 
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```
* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]

Alternatively run `echo "#### Kubernetes version:\n $(kubectl version) \n\n#### Seldon Images:\n$(kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio)"`
```
          value: docker.io/seldonio/engine:1.7.0
          value: docker.io/seldonio/seldon-core-executor:1.7.0
        image: docker.io/seldonio/seldon-core-operator:1.7.0
```

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]
