### ISSUE TITLE
TRITON_SERVER implementation does not support pvc: urls

### ISSUE THREAD

**Issue by oluies** [SeldonIO/seldon-core#3133]
Relates to #1106

TRITON_SERVER implementation does not support pvc: urls

apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: triton-pvc
  namespace: pvctfjob
spec:
  protocol: kfserving
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
  predictors:
  - graph:
      implementation: TRITON_SERVER
      modelUri: "pvc://seldon-mnist-tfjob-m68v5-modelpvc/export"
      name: testmodel
    name: testmodel
    replicas: 1

gives: 

[I 210420 13:42:40 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/export] dest_path[ [/mnt/models] [I 210420 13:42:40 storage:35] Copying contents of /mnt/pvc/export to local Traceback (most recent call last): File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module> kfserving.Storage.download(src_uri, dest_path) File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 58, in download (_GCS_PREFIX, _S3_PREFIX, _LOCAL_PREFIX)) Exception: Cannot recognize storage type for /mnt/pvc/export *'gs://', 's3://', and 'file://' are the current available storage type.  *

**Comment by cliveseldon** [comment]
Just to clarify did you try `file://` and did that not work?

https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/storage.py#L39

**Comment by oluies** [comment]
> Just to clarify did you try `file://` and did that not work?
> 
> https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/storage.py#L39

I tried but I cant get around the init container if I set it to null. Also how to mount something to the init container? 

I guess I can create a custom init container as per https://docs.seldon.io/projects/seldon-core/en/latest/examples/custom_init_container.html

**Comment by cliveseldon** [comment]
I mean did you try:

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: triton-pvc
  namespace: pvctfjob
spec:
  protocol: kfserving
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
  predictors:
  - graph:
      implementation: TRITON_SERVER
      modelUri: "file://seldon-mnist-tfjob-m68v5-modelpvc/export"
      name: testmodel
    name: testmodel
    replicas: 1

```

With an appropriate volume and volumemount specified?

**Comment by oluies** [comment]
Yes 

```
[I 210422 10:07:40 initializer-entrypoint:13] Initializing, args: src_uri [file://seldon-mnist-tfjob-m68v5-modelpvc/export] dest_path[ [/mnt/models]
[I 210422 10:07:40 storage:35] Copying contents of file://seldon-mnist-tfjob-m68v5-modelpvc/export to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 54, in download
    return Storage._download_local(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 192, in _download_local
    raise RuntimeError("Local path %s does not exist." % (uri))
RuntimeError: Local path file://seldon-mnist-tfjob-m68v5-modelpvc/export does not exist.

```
I can mount it like this in the same project: 

```
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: pvctfjob
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: seldon-mnist-tfjob-m68v5-modelpvc
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
# cd "/usr/share/nginx/html"
# tree
sh: 3: tree: not found
# ls -laFAR 
.:
total 0
drwxr-xr-x. 3 root root 23 Apr 22 10:18 export/
drwxr-xr-x. 3 root root 50 Apr 20 13:40 testmodel/

./export:
total 0
drwxr-xr-x. 3 root root 50 Apr 22 10:18 testmodel/

./export/testmodel:
total 12
-rw-r--r--. 1 root root 6148 Apr 22 10:18 .DS_Store
drwxr-xr-x. 3 root root   30 Apr 22 10:18 1/
-rw-r--r--. 1 root root  381 Apr 22 10:18 config.old

./export/testmodel/1:
total 0
drwxr-xr-x. 4 root root 59 Apr 22 10:18 model.savedmodel/

./export/testmodel/1/model.savedmodel:
total 472
drwxr-xr-x. 2 root root      6 Apr 22 10:18 assets/
-rw-r--r--. 1 root root 481071 Apr 22 10:18 saved_model.pb
drwxr-xr-x. 2 root root     83 Apr 22 10:18 variables/

./export/testmodel/1/model.savedmodel/assets:
total 0

./export/testmodel/1/model.savedmodel/variables:
total 5956
-rw-r--r--. 1 root root    6148 Apr 22 10:18 .DS_Store
-rw-r--r--. 1 root root 6083911 Apr 22 10:18 variables.data-00000-of-00001
-rw-r--r--. 1 root root    1473 Apr 22 10:18 variables.index

./testmodel:
total 12
-rw-rw-rw-. 1 root root 6148 Apr 20 13:40 .DS_Store
drwxr-xr-x. 3 root root   30 Apr 20 13:40 1/
-rw-rw-rw-. 1 root root  381 Apr 20 13:40 config.old

./testmodel/1:
total 0
drwxr-xr-x. 4 root root 59 Apr 20 13:40 model.savedmodel/

./testmodel/1/model.savedmodel:
total 472
drwxrwxrwx. 2 root root      6 Apr 20 13:40 assets/
-rw-rw-rw-. 1 root root 481071 Apr 20 13:40 saved_model.pb
drwxr-xr-x. 2 root root     83 Apr 20 13:40 variables/

./testmodel/1/model.savedmodel/assets:
total 0

./testmodel/1/model.savedmodel/variables:
total 5956
-rw-rw-rw-. 1 root root    6148 Apr 20 13:40 .DS_Store
-rw-rw-rw-. 1 root root 6083911 Apr 20 13:40 variables.data-00000-of-00001
-rw-rw-rw-. 1 root root    1473 Apr 20 13:40 variables.index
# 

```

**oc describe**

```
Volumes:
  task-pv-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  seldon-mnist-tfjob-m68v5-modelpvc
    ReadOnly:   false
  default-token-btsjl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-btsjl
    Optional:    false

```

**Comment by oluies** [comment]
Kubeflow 

- https://github.com/kubeflow/kfserving/issues/620
- https://github.com/kubeflow/kfserving/issues/1038

**Comment by oluies** [comment]
"file:///mnt/pvc/export" did not work either 

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: triton-pvc
  namespace: pvctfjob
spec:
  protocol: kfserving
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
  predictors:
  - graph:
      implementation: TRITON_SERVER
      #      modelUri: "file://seldon-mnist-tfjob-m68v5-modelpvc/export"
      modelUri: "file:///mnt/pvc/export"
      name: testmodel
    name: testmodel
    replicas: 1
```

```
[I 210422 10:53:20 initializer-entrypoint:13] Initializing, args: src_uri [file:///mnt/pvc/export] dest_path[ [/mnt/models]
[I 210422 10:53:20 storage:35] Copying contents of file:///mnt/pvc/export to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 54, in download
    return Storage._download_local(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 192, in _download_local
    raise RuntimeError("Local path %s does not exist." % (uri))
RuntimeError: Local path file:///mnt/pvc/export does not exist.
```

**Comment by oluies** [comment]
Ah, looks like modelUri: "pvc://seldon-mnist-tfjob-m68v5-modelpvc/export" works now. "export" directory was not present

**Comment by oluies** [comment]
Any idea what can cause `failed to poll model repository '/mnt/models': failed to stat file /mnt/models/testmodel `

```
[I 210505 12:16:34 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/export] dest_path[ [/mnt/models]
[I 210505 12:16:34 storage:35] Copying contents of /mnt/pvc/export to local
[I 210505 12:16:35 storage:205] Linking: /mnt/pvc/export/testmodel to /mnt/models/testmodel


=============================
== Triton Inference Server ==
=============================

NVIDIA Release 20.08 (build 15533555)

Copyright (c) 2018-2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.
find: '/usr/lib/ssl/private': Permission denied

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .
find: '/etc/ssl/private': Permission denied
find: '/mnt/pvc': Permission denied
find: '/proc/tty/driver': Permission denied
find: '/root': Permission denied

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for the inference server.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 ...

I0505 12:51:55.549189 1 server.cc:119] Initializing Triton Inference Server
E0505 12:51:55.549392 1 pinned_memory_manager.cc:192] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version
E0505 12:51:55.559899 1 model_repository_manager.cc:1477] failed to poll model repository '/mnt/models': failed to stat file /mnt/models/testmodel
error: creating server: Internal - failed to load all models
E0505 12:51:55.561386 1 cuda_memory_manager.cc:65] Failed to finalize CUDA memory manager: [3] CNMEM_STATUS_NOT_INITIALIZED
```

**Comment by oluies** [comment]
https://github.com/triton-inference-server/server/blob/44792579438f39cca96f7b698188aca787e756b3/src/core/model_repository_manager.cc#L1477

**Comment by cliveseldon** [comment]
Are you sure the folder is visible to Triton. Have you exec-ed into the container to check?

**Comment by oluies** [comment]
> Are you sure the folder is visible to Triton. Have you exec-ed into the container to check?

With debug ? I will try 

I was thinking 

1. the init container finds the file
[I 210505 12:16:34 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/export] dest_path[ [/mnt/models]
[I 210505 12:16:34 storage:35] Copying contents of /mnt/pvc/export to local
[I 210505 12:16:35 storage:205] Linking: /mnt/pvc/export/testmodel to /mnt/models/testmodel

2. TRITON IMAGE cant see it, permissions or something like that. Due to PVC type?  
E0505 12:51:55.559899 1 model_repository_manager.cc:1477] failed to poll model repository '/mnt/models': failed to stat file /mnt/models/testmodel

**Comment by cliveseldon** [comment]
Please reopen if still an issue

**Comment by Atakey** [comment]
TENSORFLOW_SERVER implementation does not support pvc.
When I followed with the guide: https://docs.seldon.io/projects/seldon-core/en/latest/servers/tensorflow.html about 'gRPC MNIST Example', just replace 'modelUri: gs://seldon-models/tfserving/mnist-model' to 'modelUri: pvc://pvc-name/model_path'.
The pods describe shows that

Warning  FailedMount  13s (x2 over 4m45s)  kubelet, cn-xxx.x.x.x.xx  Unable to attach or mount volumes: unmounted volumes=[kfserving-pvc-source], unattached volumes=[kfserving-pvc-source tfserving-provision-location default-token-c7kqq seldon-podinfo]: timed out waiting for the condition

**Comment by cliveseldon** [comment]
How is the PVC mounted? I would have assumed you would need to add Volume specification and use it in the Triton container explicitly for this to possibly work rather than using just a default Server with modelUri.

**Comment by Atakey** [comment]
> kfserving-pvc-source

PVC info:
```
Name:          basic-nas
Namespace:     default
StorageClass:  nas
Status:        Bound
Volume:        basic-nas
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2000Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    example-tfserving-model-0-multi-56bc4cd96c-h2v9r
Events:        <none>
```
I also try to add Volume specification in container or initcontainer , both do not work.
Example likes this:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: example-tfserving
spec:
  nodeSelector:
    workload_type: cpu
  protocol: tensorflow
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - args:
          - --port=8500
          - --rest_api_port=8501
          - --model_config_file=/mnt/models/models.config
          image: tensorflow/serving
          imagePullPolicy: IfNotPresent
          name: multi
          ports:
          - containerPort: 8501
            name: http
            protocol: TCP
          - containerPort: 8500
            name: grpc
            protocol: TCP
          volumeMounts: 
            - mountPath: /mnt/pvc
              name: kfserving-pvc-source
    graph:
      name: multi
      type: MODEL
      implementation: TENSORFLOW_SERVER
      modelUri: pvc://basic-nas/model_path
      endpoint:
        httpPort: 8501
        grpcPort: 8500
    name: model
    replicas: 1
```

**Comment by Atakey** [comment]
If I add volume spec like below:
```
        volumes:
        - downwardAPI:
            defaultMode: 420
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations
              path: annotations
          name: seldon-podinfo
        - name: kfserving-pvc-source
          persistentVolumeClaim:
            claimName: basic-nas
        - emptyDir: {}
          name: multi-provision-location
        - name: default-token-c7kqq
          secret:
            defaultMode: 420
            secretName: default-token-c7kqq
```
yaml file describe shows that:
Deployment.apps "example-tfserving-model-0-multi" is invalid: [spec.template.spec.volumes[4].name: Duplicate value: "kfserving-pvc-source", spec.template.spec.volumes[5].name: Duplicate value: "multi-provision-location"]
