### ISSUE TITLE
The /aggregate endpoint is wrongly called if we have a COMBINER with SEND_FEEDBACK method activated

### ISSUE THREAD

**Issue by fernandocamargoti** [SeldonIO/seldon-core#3139]
I have a COMBINER in which I want to have the /send-feedback endpoint. So, I have the following configuration:

```
graph:
        children:
          - children: [ ]
            name: recommender
            type: MODEL
            endpoint:
              type: REST
        endpoint:
          type: REST
        name: cold-start-recommender
        type: COMBINER
        methods: ["AGGREGATE", "SEND_FEEDBACK"]
```

Then, I've noticed that when I send feedback, the /send-feedback of my `recommender` is invoked and then the /aggregate of `cold-start-recommender` is called (and an error is raised because the message is unexpected) instead of the /send-feedback. It can be seen in the following log (in which I've sent a prediction and a feedback request):

```
{"level":"debug","ts":1619211214.6164505,"logger":"JSONRestClient","msg":"Calling HTTP","URL":"http://localhost:9000/predict"}
{"level":"debug","ts":1619211214.749554,"logger":"JSONRestClient","msg":"Calling HTTP","URL":"http://localhost:9001/aggregate"}
{"level":"debug","ts":1619211239.8898373,"logger":"JSONRestClient","msg":"Calling HTTP","URL":"http://localhost:9000/send-feedback"}
{"level":"debug","ts":1619211239.9361725,"logger":"JSONRestClient","msg":"Calling HTTP","URL":"http://localhost:9001/aggregate"}
{"level":"info","ts":1619211239.947629,"logger":"JSONRestClient","msg":"httpPost failed","response code":500}
```

After talking to @cliveseldon on Slack, he said that it's probably because of [this line](https://github.com/SeldonIO/seldon-core/blob/2a09a8da682bba6c9600947e311dcbc2c8bbeb3f/executor/predictor/predictor_process.go#L312).
