### ISSUE TITLE
Deploy python model without java router

### ISSUE THREAD

**Issue by epa095** [SeldonIO/seldon-core#314]
We want to deploy a large number of models (modelling different things, not different versions of the same thing) using the python wrapper, and in many cases we just want the model, not any transformer or fancy AB routing. In our case we see that the Python model takes roughly 200Mb of memory, while the Java Spring application which is also deployed takes roughly 700 Mb. Is it possible to write a seldondeployment which does not deploy the java application for the cases when we just want to deploy a "naked" model? The relevant part of our seldondeployment is:

```yaml
predictors: 
  - 
    annotations: 
      predictor_version: "v1"
    componentSpecs: 
      - spec: 
          containers: 
            - image: "..some-docker-image"
              name: "modelserver-{{auto-generated-name}}"
    graph: 
      children: []
      endpoint: 
        type: "REST"
      name: "modelserver-{{auto-generated-name}}"
      type: "MODEL"
    name: "modelserver-{{auto-generated-name}}"
    replicas: 1
```
