### ISSUE TITLE
HPA support for autoscaling/v2beta2 API

### ISSUE THREAD

**Issue by SanjayJosh** [SeldonIO/seldon-core#3143]
Added support for v2beta2 autoscaling api.
This can enhance autoscaling with the following benefits.

- Support for multiple metrics which will change hpa specs to : 
```
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi      
```  
- Support for custom metrics from `custom.metrics.k8s.io` API
- Customisable Scaling Policies
