### ISSUE TITLE
Higher level replicas act as default but not scale factor

### ISSUE THREAD

**Issue by cksac** [SeldonIO/seldon-core#3150]
## Describe the bug
Replica Settings
    .spec.replicas
    .spec.predictors[].replicas
    .spec.predictors[].componentSpecs[].replicas

Higher level replicas only act as default but not scale factor.

## To reproduce
set .spec.replicas: 0
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: test-replicas
  namespace: dscoe
  labels:
    seldon.io/controller-id: seldon-operator-1
spec:
  replicas: 0
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier2
      replicas: 3
    graph:
      endpoint:
        type: REST
      name: classifier
      type: MODEL
      children:
      - name: classifier2
        type: MODEL
        endpoint:
          type: REST
    name: example
    replicas: 2
    traffic: 50
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier3
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier3
      type: MODEL
    name: example2
    traffic: 50
```

## Current behavious
Higher level replicas act as default value
`if .spec.replicas: 1`
2 classifier, 3 classifier2, 1 classifier3
`if .spec.replicas: 0`
2 classifier, 3 classifier2, 0 classifier3

## Expected behaviour
Higher level replicas act as scale factor
`if .spec.replicas: 1`
2 classifier, 6 classifier2, 1 classifier3
`if .spec.replicas: 0`
0 classifier, 0 classifier2, 0 classifier3
