### ISSUE TITLE
V2 Inference Compliance

### ISSUE THREAD

**Issue by awcchungster** [SeldonIO/seldon-core#3156]
## Describe the bug

When I apply a XGB model using the Seldon-Core XGB server, the V2 Inference returns a non standard response. The outputs.data tensor should be a flattened array. Seldon currently responds with a np tensor.

## To reproduce

According to the spec, inference request examples should be return the shape of the data. However[ the data itself is a flattened array.](https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md#inference-request-examples) 

My data object should be [0.005064773838967085, 0.007540544960647821, 0.9873946905136108, 0.9904587268829346, 0.005667048040777445, 0.00387418526224792]

With Seldon right now, the array is a multidimensional np data frame.

{'model_name': 'classifier', 'model_version': 'v1', 'id': '0', 'parameters': None, 'outputs': [{'name': 'predict', 'shape': [2, 3], 'datatype': 'FP32', 'parameters': None, 'data': [[0.005064773838967085, 0.007540544960647821, 0.9873946905136108], [0.9904587268829346, 0.005667048040777445, 0.00387418526224792]]}]}

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Can you provide the yaml of your SeldonDeployment?

**Comment by awcchungster** [comment]
Thanks for the fast response! It's near identical to the documentation. Here it is: 
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: xgboost
  labels: 
    mlctl_name: seldon-xgb-iris
    mlctl_type: model_deployment
spec:
  name: iris
  protocol: kfserving # Activate the V2 protocol
  predictors:
  - graph:
      children: []
      implementation: XGBOOST_SERVER
      modelUri: s3://iris
      envSecretRefName: seldon-init-container-secret
      name: classifier
    name: default
    replicas: 1
```
