### ISSUE TITLE
explainer don't repect the spec.replicas 

### ISSUE THREAD

**Issue by cksac** [SeldonIO/seldon-core#3241]
## Describe the bug
explainer don't repect the spec.replicas 

## To reproduce
1. deploy the model
```yaml 
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: income
  namespace: dscoe
spec:
  name: income
  replicas: 1
  predictors:
  - graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/income/model-0.23.2
      name: classifier
    explainer:
      type: AnchorTabular
      modelUri: gs://seldon-models/sklearn/income/explainer-py36-0.5.2
    name: default
```
2. update the income seldondeployment's spec.replicas = 0

## Current behaviour
Only classifer pods are terminated, explainer pods still running.

## Expected behaviour
Both classifer and explainer pods are terminated.
