### ISSUE TITLE
seldon-core 1.8.0 helm chart CRD error

### ISSUE THREAD

**Issue by boniek83** [SeldonIO/seldon-core#3254]
## Describe the bug
When 
`CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

## To reproduce
1. Create new argocd project or use  helm template using 1.8.0 seldon chart
2. Try to deploy resulting yamls to kubernetes

## Expected behaviour
It should work.

## Environment
seldon-core 1.8.0
kubernetes 1.19.8
argocd 2.0.3
helm 3.6.0

**Comment by ellisvalentiner** [comment]
For what it's worth, this affects the CRDs for multiple Seldon versions. We're still on 1.6 and see the same thing.

You can add an `ignoreDifferences` statement in your Argo CD application yaml:

```
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: seldondeployments.machinelearning.seldon.io
    jsonPointers:
    - /spec
    - /status
    - /metadata/labels
```
