### ISSUE TITLE
Drastically Lower Performance when predictors.componentSpecs.graph.type is Transformer

### ISSUE THREAD

**Issue by ntorba** [SeldonIO/seldon-core#3272]
## Describe the bug

This bug is mysterious to me. 

Within the graph section of the seldon deployment yaml, each node has a required `type` field. 

I am creating a deployment with a single transformer node, so naturally I put this type as TRANSFORMER. 

While doing distributed load tests of my application on kubernetes with locust, I accidentally flipped this field to MODEL and my application was able to serve many, many more requests per second. 
**When the value is TRANSFORMER, it can serve ~10 req/s, but when the field is MODEL (or any other string), it serves 180 req/s (with the same nodeSelector and resource limits set for both).** 

Can someone please help me debug this? 

## To reproduce

I am creating a custom transformer_input_raw component, with the following dockerfile: 
```bash
FROM python:3.7-slim
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000

# Define environment variable
ENV MODEL_NAME SeldonTransformerInputRaw
ENV API_TYPE REST
ENV SERVICE_TYPE TRANSFORMER
ENV PERSISTENCE 0
ENV LOG_LEVEL DEBUG

CMD exec seldon-core-microservice $MODEL_NAME --service-type $SERVICE_TYPE --persistence $PERSISTENCE --log-level $LOG_LEVEL
```
(not using s2i to build image). 

The requirements are 
```text
scikit_learn==0.24.1
seldon_core==1.5.1
cloudpickle==1.6.0
```

My python component, in a file named `SeldonTransformerInputRaw.py`:
```python
from datetime import datetime
import seldon_core

from sklearn.ensemble import IsolationForest

iso = IsolationForest()
iso.fit([[1], [2]])


def transform_serve(msg, iso_model=iso, **kwargs):
    # Load profile map from profiles in request
    data = msg["data"]
    for i_record in data:
        binary_pred = iso_model.predict([[i_record["value"]]]).tolist()
        prediction_score = iso_model.decision_function([[i_record["value"]]]).tolist()
        i_record["binary_prediction"] = binary_pred
        i_record["prediction_score"] = prediction_score
    return {"meta": {}, "results": data}


request = {
    "data": [
        {
            "value": 52831577.0,
        }
    ]
}


class SeldonTransformerInputRaw:
    HEAD = True

    @staticmethod
    def transform_input_raw(msg, **kwargs):
        """
        Important to note that seldon only speaks in, at most, numpy arrays.. not pandas dataframes.
        Need to decide how the ADT is going to return data from the functions to lend itself well to seldon
        """
        msg = request
        return transform_serve(msg, **kwargs)

```

The yaml for the deployment is here: 
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: endpoint-slim
spec:
  name: deploy
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - env:
                  - name: SELDON_LOG_LEVEL
                    value: DEBUG
                image: private-dockerhub/endpoint-slim:0.1
                imagePullPolicy: Always
                name: transform-serve
                resources:
                  requests:
                    memory: 64Mi
                    cpu: 250m
                  limits:
                    memory: 2000Mi
                    cpu: 2000m
            nodeSelector:
              app: "true" 
          hpaSpec:
            minReplicas: 1
            maxReplicas: 1
            metrics:
              - type: Resource
                resource:
                  name: cpu
                  targetAverageUtilization: 60
      graph:
        amp_component_type: predict_raw
        children: []
        endpoint:
          type: REST
        name: transform-serve
        # type: MODEL
        # type: TRANSFORMER
        type: FAKE
      name: predictor
      svcOrchSpec:
        env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
      traffic: 100
```

As you can see, I have a couple of different values commented out for the `predictors.componentSpecs.graph.type` field. 

When this value is TRANSFORMER, the performance of my application is much lower. However, even when I put a different component (like `MODEL` or `COMBINER`) or even a fake value (in this case, the string `FAKE`), the performance is much better. 

## Expected behaviour

I would expect that seldon would throw an error if this component does not match the type of component that is actually deployed. 
After that, I would expect all components to have the same performance. 

## Environment

Kubernetes is running seldon-container-engine 1.6.0

I tried to reproduce this with the sklearn example here: https://docs.seldon.io/projects/seldon-core/en/v1.6.0/examples/iris.html but was not able to. 

AWS EKS 1.17
