### ISSUE TITLE
Cannot apply Seldon Deployment from Kubernetes Python API

### ISSUE THREAD

**Issue by YannickLecroart** [SeldonIO/seldon-core#3375]
## Describe the bug

I can deploy my Seldon custom model via the Google Cloud Shell SDK on GCP using the following command:

`
kubectl apply -n seldon-system -f rf_seldon_deployment.yaml
`

But when using the Kubernetes API I get the followring error message.

````
kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '92db1368-f014-4e62-b157-15aa876250d5', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 06 Jul 2021 15:05:41 GMT', 'Content-Length': '338'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"SeldonDeployment in version \"v1\" cannot be handled as a Deployment: no kind \"SeldonDeployment\" is registered for version \"machinelearning.seldon.io/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30\"","reason":"BadRequest","code":400}
````

## To reproduce

````
from kubernetes import client
import yaml

v1 = client.AppsV1Api()


with open("rf_seldon_deployment.yaml", 'rb') as f:
    dep = yaml.load(f)
    resp = v1.create_namespaced_deployment(
        body=dep, namespace="seldon-system")

    print("Deployment created. status='%s'" % str(resp.status))

````

## Expected behaviour

````
kubectl get deployment -n seldon-system

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
randomforest-model-0-classifier      1/1     1            1           4d3h
````

## Environment

````
kubectl version --short

Client Version: v1.20.2
Server Version: v1.18.17-gke.1901
````

````
pip list

kubernetes                         12.0.1
````

## Model Details 

The content of the yaml file is as followed:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: randomforestxai
spec:
  name: rest_random_forest
  protocol: seldon
  transport: rest
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: ylecroart/sc_random_forest_pmr
          name: classifier
    graph:
      name: classifier
      type: MODEL
    name: model
    replicas: 1
```
