### ISSUE TITLE
Seldon + Istio: Custom URI re-write in VirtualService configuration

### ISSUE THREAD

**Issue by senthilrch** [SeldonIO/seldon-core#3470]
I have deployed seldon-core with Istio enabled. i.e. Istio Ingress gateway is used to route the model invoking request to seldon. Model invocation works fine if I hit the endpoint:-
```
https://<hostname>/seldon/<namespace>/<deployment>/api/v1.0/predictions
```

I need the ability to invoke models without the trailing path "/api/v1.0/predictions" i.e. like this:-
```
https://<hostname>/seldon/<namespace>/<deployment>/
```

The virtual service created by seldon controller is as follows:-
```yaml
spec:
  gateways:
  - mxe-senthil/gateway-mxe-csr
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /seldon/<namepsace>/<deployment>/
    rewrite:
      uri: /
    route:
    - destination:
        host: single-stateless-manual-main
        port:
          number: 8000
        subset: main
```

Request to allow user to configure re-write rules when deploying seldon, so that it creates a virtual service supporting custom uri re-write:-
```yaml
spec:
  gateways:
  - mxe-senthil/gateway-mxe-csr
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /model-endpoints/single-stateless-manual-main
    rewrite:
      uri: /api/v1.0/predictions
    route:
    - destination:
        host: single-stateless-manual-main
        port:
          number: 8000
        subset: main
```
