### ISSUE TITLE
GPU memory consumption very high fwithin chained seldon components

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3497]
Hi @cliveseldon @RafalSkolasinski 

## Describe the bug
I am using seldon core v1.1.0 in Google Kubernetes engine. I have a seldon graph where I have chained 6 components which inlcudes transformers, , routers, models  and output transformers. Among the 6 components, I have three model components (model1, model2, errorhandler)among which only one model requires GPU ram. During a load test on accessing the endpoint using model2, I noticed that the gpu ram consumption becomes too high and throws an out of memory issue. The overall response time and latency seems to be around 10-13s which is quite high. For further understanding, I even deployed a small seldon graph of 2 components with the same model component using gpu  and 1 output transformer. During load test , there was no issue with gpu ram consumption and a max of 1GB was used out of the 15GB. Moreover the overall latency and response time was in few milliseconds.
I feel this could be a bug and would like you to help me understand this issue and suggest some quick solutions. I would also like to know whether this bug or performance issue has been solved in any of the latest seldon core releases.

## To reproduce
Deployed the below seldon graph with 6 components. Here the flow is simple
Input --> Inputtransformer(basic preprocessing work)-->model2-->outputtransformer(basic postprocessing work).
This flow shouldnt cause much latency and gpu performance issue, but unfortunately it does
```
name: outtr
endpoint:
  type: REST
type: OUTPUT_TRANSFORMER
children:
- name: inputtr
  endpoint:
      type: REST
  type: TRANSFORMER
  children:
  - endpoint:
      type: REST
    name: rout
    type: ROUTER
    parameters:
    - name: n_branches
      type: INT
      value: '3'
    children: 
    - name: model1
      endpoint:
        type: REST
      type: MODEL
      children: []   
    - name: model2
      endpoint:
        type: REST
      type: MODEL
      children: [] 
    - name: errorhandler
      endpoint:
        type: REST
      type: MODEL
      children: [] 
```

Seldon graph with 2 components. Here the flow is simple and direct and works as expected
input --> model2--> output transformer(basic post processing work)
```
name: outr
endpoint:
  type: REST
type: OUTPUT_TRANSFORMER
children:
- name: model2
  endpoint:
      type: REST
  type: MODEL
  children: []
```

## Expected behaviour
Gpu consumption should not be high since model 2 alone is using the gpu, but it looks as if all the graph components is using the gpu ram where by it goes out of memory. 

The expected behaviour is achieved in a seldon graph of 2 components, but not in complex graphs.

Kindly help to solve this issue.
