### ISSUE TITLE
Add support for user defined OpenAPI Spec

### ISSUE THREAD

**Issue by meftasadat** [SeldonIO/seldon-core#3641]
As a user of Seldon Custom Python Wrapper, 
* I can view a [Swagger UI](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/openapi.html?highlight=swagger#viewing-testing-via-swagger-ui) of my SeldonDeployment 
* This Swagger UI renders the OpenAPI spec defined in this [file](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/openapi/seldon.json) I think.
* However, the user of Custom Python Wrapper can have their own Request/Response Data Models that are different from the above-mentioned file.
* Can you please add support to pass a user-defined OpenAPI spec JSON/YAML file to Seldon? It could be something as simple as an environment variable `USER_DEFINED_OPENAPI_SPEC_FILE_LOCATION` accessible to the prediction container under the SeldonDeployment. 
For example:

```YAML
kind: SeldonDeployment
metadata:
  name: iris-model
  namespace: model-namespace
spec:
  name: iris
  predictors:
  - componentSpecs:
    - spec:
      containers:
      - name: classifier
        image: sklearn_iris:0.1
        env:
        - name: GUNICORN_WORKERS
          value: 4
        - name: USER_DEFINED_OPENAPI_SPEC_FILE_LOCATION
          value: "/app/my_swagger_spec.json"
  - graph:
      name: classifier
    name: default
    replicas: 1
```
