### ISSUE TITLE
Service "seldon-webhook-service" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset

### ISSUE THREAD

**Issue by bartcode** [SeldonIO/seldon-core#3721]
## Describe the bug
When deploying the `seldon-core-operator` to a Kubernetes cluster with ArgoCD, the seldon-webhook-service fails to be deployed properly.

```
error when replacing "/dev/shm/907754144": Service "seldon-webhook-service" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset
```

![image](https://user-images.githubusercontent.com/24415187/140192435-651f6584-e08c-4b00-94f5-81d9e9fdb072.png)

## To reproduce
1. Deploy Seldon Core Helm chart using the configuration below in ArgoCD.

## Expected behaviour

Successful deployment.

## Environment

The application is created with this file:

### `application.yml`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon
spec:
  destination:
    name: ''
    namespace: seldon-system
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/seldon
    repoURL: 'https://github.com/xxxxxx/xxxxx'
    targetRevision: main
  project: default
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: seldondeployments.machinelearning.seldon.io
      jsonPointers:
        - /spec
        - /status
        - /metadata/labels
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: seldon-validating-webhook-configuration-seldon-system
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
    - kind: Service
      namespace: seldon-system
      name: seldon-webhook-service
      jsonPointers:
        - /spec/clusterIPs
        - /spec/clusterIP
    - kind: Secret
      namespace: seldon-system
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - Validate=false
```

The source path points to a directory with the `kustomization.yml` below in it.

### `kustomization.yml`
```yaml
helmCharts:
- name: seldon-core-operator
  includeCRDs: true
  namespace: seldon-system
  valuesInline:
    image:
      pullPolicy: IfNotPresent
    usageMetrics:
      enabled: true
    ambassador:
      enabled: true
    crd:
      create: true
  version: 1.11.2
  releaseName: seldon-core-operator
  repo: https://storage.googleapis.com/seldon-charts
```

* Cloud Provider: Azure
* Kubernetes Cluster Version [Output of `kubectl version`]: `Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"ed93e7ea8f833824d05578765c2ad3efbebbfebe", GitTreeState:"clean", BuildDate:"2021-10-21T03:31:08Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}`
* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]
```
docker.io/seldonio/engine:1.11.2
docker.io/seldonio/seldon-core-executor:1.11.2
docker.io/seldonio/seldon-core-operator:1.11.2
```

**Comment by cliveseldon** [comment]
could this be related to https://github.com/helm/helm/issues/6378#issuecomment-557746499

clusterIP should only be set by kubernetes to an actual value.

**Comment by bartcode** [comment]
The behaviour is the same, indeed. But in the Seldon Helm chart there's no such thing as `omitClusterIP`. I was hoping that this part in the `ignoreDifferences` section would therefore fix it:

```yaml
    - kind: Service
      namespace: seldon-system
      name: seldon-webhook-service
      jsonPointers:
        - /spec/clusterIPs
        - /spec/clusterIP
```

Do you have any suggestions on how to fix it for Seldon?
