### ISSUE TITLE
hap - no behaviour functionality

### ISSUE THREAD

**Issue by wallies** [SeldonIO/seldon-core#3761]
## Describe the bug
Kubeflow version: 1.4.0
Seldon-core: 1.11.2

We run with the following manifest

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: roberta
  namespace: seldon
  labels:
    app: plumeria
    channel: production
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/prometheus'
    prometheus.io/port: "8000"
spec:
  name: roberta
  transport: rest
  protocol: tensorflow
  predictors:
  - componentSpecs:
    - hpaSpec:
        minReplicas: 1
        maxReplicas: 9
        metrics:
        - type: External
          external:
            metricName: kubernetes.io|container|accelerator|duty_cycle
            metricSelector:
              matchLabels:
                resource.labels.container_name: roberta
            targetAverageValue: 40
    - spec:
        containers:
        - name: roberta
          env:
          - name: MODEL_NAME
            value: 'roberta'
          args:
            - --port=9500
            - --rest_api_port=9000
          image: tensorflow/serving:2.6.0-gpu
          resources:
            requests:
              nvidia.com/gpu: '1'
            limits:
              nvidia.com/gpu: '1'
```

This seemed to scale before, but for some reason we see in the logs scalereplicaset "Scale to 0" from deployment controller.
Then when a scaling event comes it says scaledreplica set "Scaled to 2", but there will only be 1 pod.

I created a hpa like this

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: plumeria
  namespace: seldon
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
      - type: Percent
        value: 80
        periodSeconds: 600
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: roberta-default-0-roberta
  minReplicas: 1
  maxReplicas: 9
  metrics:
  - type: External
    external:
      metric:
        name: kubernetes.io|container|accelerator|duty_cycle
        selector:
          matchLabels:
            resource.labels.container_name: roberta
      target:
        type: AverageValue
        averageValue: 40
```
and turned the deployment controller off, and all scaling events and runtime work perfectly. 

## Expected behaviour
When deploying the seldon deployment, with hpaspec, i would expect it to create a HPA config

* Cloud Provider: GKE 
* Kubernetes Cluster Version  1.20.10-gke.1600 
* Deployed Seldon System Images: 
          value: docker.io/seldonio/engine:1.11.2
          value: docker.io/seldonio/seldon-core-executor:1.11.2
        image: docker.io/seldonio/seldon-core-operator:1.11.2

Deployed on a burstage gpu nvidia node pool

## Model Details
* Images of your model: image: tensorflow/serving:2.6.0-gpu

**Comment by cliveseldon** [comment]
The operator will create an HPA. So can you compare the one created by Seldon to the one hand crafted by yourself and see if there are any differences?

**Comment by wallies** [comment]
@cliveseldon the operator doesn't seem to be creating a hpa, I think that is the problem

**Comment by cliveseldon** [comment]
I think your yaml is not correct
 -  are missing a graph section.
 - the spec section starts a new list rather than being part of the same level as hpa

see [here](https://docs.seldon.io/projects/seldon-core/en/latest/examples/autoscaling_example.html)

Something like:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: roberta
  namespace: seldon
  labels:
    app: plumeria
    channel: production
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/prometheus'
    prometheus.io/port: "8000"
spec:
  name: roberta
  transport: rest
  protocol: tensorflow
  predictors:
  - name: roberta
    componentSpecs:
    - hpaSpec:
        minReplicas: 1
        maxReplicas: 9
        metrics:
        - type: External
          external:
            metricName: kubernetes.io|container|accelerator|duty_cycle
            metricSelector:
              matchLabels:
                resource.labels.container_name: roberta
            targetAverageValue: 40
      spec:
        containers:
        - name: roberta
          env:
          - name: MODEL_NAME
            value: 'roberta'
          args:
            - --port=9500
            - --rest_api_port=9000
          image: tensorflow/serving:2.6.0-gpu
          resources:
            requests:
              nvidia.com/gpu: '1'
            limits:
              nvidia.com/gpu: '1'
    graph:
      name: roberta
      type: MODEL
```

**Comment by wallies** [comment]
wow, how did i get that so so wrong. Thank you so so much @cliveseldon

**Comment by wallies** [comment]
@cliveseldon i forgot to ask, the scaledown functionality i couldnt get to work, and couldnt find any examples on the website, as i was trying to get something like this 

```
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
      - type: Percent
        value: 80
        periodSeconds: 600
```
