### ISSUE TITLE
Prediction requests via Kafka not detected for MLServer model

### ISSUE THREAD

**Issue by ashrafgt** [SeldonIO/seldon-core#3817]
## Describe the bug
I'm trying to test the Kafka integration with a SeldonDeployment for my MLServer model, but I can't seem to get predictions triggered when I send payloads to the Kafka input topic (no logs or messages written to the output topic). Could this be because of the `seldon.io/no-engine: "true"` annotation?

## To reproduce
1. Deploy Kafka using helm (with auto topic creation enabled):
    ```bash
    helm upgrade --install kafka bitnami/kafka --set autoCreateTopicsEnable=true
    ```
2. Create a SeldonDeployment to serve the model:
    ```bash
    kubectl apply -f seldon-deployment.yaml
    ```
    With `seldon-deployment.yaml` containing:
    ```yaml
    apiVersion: machinelearning.seldon.io/v1
    kind: SeldonDeployment
    metadata:
      name: mlserver-example
    spec:
      transport: rest
      serverType: kafka
      predictors:
        - name: default
          annotations:
            seldon.io/no-engine: "true"
          graph:
            name: mlserver-example
            implementation: SKLEARN_SERVER
            type: MODEL
            modelUri: s3://models
            endpoint:
              service_port: 8080
          componentSpecs:
            - spec:
                containers:
                  - name: mlserver-example
                    image: ashguitouni/mlserver-example:latest
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 8080
                        name: http
                        protocol: TCP
          svcOrchSpec:
            env:
            - name: KAFKA_BROKER
              value: kafka.default.svc.cluster.local:9092
            - name: KAFKA_INPUT_TOPIC
              value: mlserver-example-input
            - name: KAFKA_OUTPUT_TOPIC
              value: mlserver-example-output
    ```
    Which responds correctly to REST prediction requests:
    ```bash
    $ kubectl logs svc/mlserver-example-default-mlserver-example 
    INFO:     Started server process [7]
    INFO:     Waiting for application startup.
    INFO:     Application startup complete.
    INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
    INFO:     127.0.0.1:55652 - "POST /v2/models/mlserver-example/infer HTTP/1.1" 200 OK
    ```
3. Produce a prediction payload from inside the cluster using python and the `kafka-python==2.0.2` package:
    ```python
    import json
      from kafka import KafkaProducer
      from kafka.errors import KafkaError
      from kafka import KafkaConsumer
      
      producer = KafkaProducer(
        bootstrap_servers="kafka.default.svc.cluster.local:9092",
        value_serializer=lambda m: json.dumps(m).encode("utf-8"),
    )
    
    inputs = [5, 3, 11, -2]
    inference_request = {
        "inputs": [
            { 
                "name": "data_points", "shape": [len(inputs)], "datatype": "int", "data": inputs,
            }
        ]
    }
    
    future = producer.send("mlserver-example-input", inference_request)
    print(future.get(timeout=5))
    ```
    Which writes the record correctly:
    ```python
    >>> RecordMetadata(topic='mlserver-example-input', partition=0, topic_partition=TopicPartition(topic='mlserver-example-input', partition=0), offset=3, timestamp=1640601943990, log_start_offset=0, checksum=None, serialized_key_size=-1, serialized_value_size=94, serialized_header_size=-1)
    ```

## Expected behaviour
Prediction results printed when consuming the output artifact:
```python
import json
from kafka import KafkaConsumer


consumer = KafkaConsumer(
    "mlserver-example-output",
    bootstrap_servers="kafka.default.svc.cluster.local:9092",
    auto_offset_reset="earliest",
    enable_auto_commit=True,
    value_deserializer=lambda x: json.loads(x.decode("utf-8")),
)

for message in consumer:
    print(message.value)
```
Or a trace of prediction requests (success or error) when viewing model logs:
```yaml
$ kubectl logs svc/mlserver-example-default-mlserver-example
```

## Environment

* Cloud Provider: None (using k3d)
* Kubernetes Cluster Version:
  ```bash
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```
* Deployed Seldon Chart: `seldon-core-operator-1.12.0`
