### ISSUE TITLE
Support using SSL with PEM strings

### ISSUE THREAD

**Issue by stephen37** [SeldonIO/seldon-core#3867]
## Describe the bug

It is not possible to add CA certificate by PEM string when using SSL with Kafka when using the configuration `ssl.ca.pem`. This is because it has been added in the version [v1.8.2 of librdkafka](https://github.com/edenhill/librdkafka/releases/tag/v1.8.2) which has been released in October 2021. 
The executor is using the version [v1.4.2](https://github.com/SeldonIO/seldon-core/blob/master/executor/go.mod#L7) which has been released in May 2020. 

## To reproduce
Try to define `ssl.ca.pem` in the ConfigMap used by Kafka, e.g.
```yaml
kafkaConfig: kafka.ConfigMap{
    "security.protocol":   "SSL",
    "ssl.ca.pem":          caPEM,
    "ssl.key.pem":         keyPEM,
    "ssl.certificate.pem": certPEM,
    "ssl.key.password":    keyPassword,
},
```
it will result in an error saying `"No such configuration property: "ssl.ca.pem\",`. You can make it crash easily by changing the `worker_test.go` configuration https://github.com/SeldonIO/seldon-core/blob/master/executor/logger/worker_test.go#L140-L146
## Expected behaviour

It should be possible to define that option in the configuration, it is defined in [librdkafka](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) which is what confluent-kafka-go is using behind the scene.

We have to wait for this issue to be addressed until we can make that possible: https://github.com/SeldonIO/seldon-core/issues/3866

**PR** to solve this issue: https://github.com/SeldonIO/seldon-core/pull/3868
