### ISSUE TITLE
Unable to query any metrics in prometheus

### ISSUE THREAD

**Issue by gandharv-kapoor** [SeldonIO/seldon-core#3881]
## Describe the bug
@cliveseldon I am not seeing any results when querying prometheus or grafana following this documentation https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html

## To reproduce
- deploy onnx model using the following deployment file
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: ensemble-model
spec:
  protocol: kfserving
  predictors:
    - name: default
      graph:
        name: ensemble-model
        implementation: TRITON_SERVER
        logger:
          mode: all
        modelUri: s3://ensemble-models/
        envSecretRefName: seldon-init-container-secret
        type: MODEL
      componentSpecs:
        - spec:
            volumes:
            - name: dshm
              emptyDir:
                medium: Memory
            containers:
            - name: ensemble-model
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
```
2. install helm analytics chart with:
```
helm install seldon-core-analytics seldon-core-analytics \
   --repo https://storage.googleapis.com/seldon-charts \
   --namespace seldon-system
  ```
  
## Expected behaviour
running the following query should return some results
**seldon_api_executor_server_requests_seconds_count**
![image](https://user-images.githubusercontent.com/86222489/150746755-7ec7f7f7-a18f-49d4-bc32-8c1da23903f1.png)

## Environment

* Cloud Provider: Minikube local
* Kubernetes Cluster Version: ‎V1.16
* Istio

## Model Details 
onnx model on triton ensemble using minio s3 bucket
