### ISSUE TITLE
How to use kube-prometheus instead of seldon-core-analytics

### ISSUE THREAD

**Issue by passerbyflutter** [SeldonIO/seldon-core#3980]
## Describe the bug
I want to push metric of seldon core to ready kube-prometheus in kubernetes. Now I can check metric endpoint of seldon core in targets of prometheus, but it loss some labels and information compare with seldon-core-analytics, like below.

![image](https://user-images.githubusercontent.com/9139212/158102397-721d051e-b1ec-4a6f-b314-2714df7bec8f.png)

I import Prediction Analytics Dashboard into grafana of  kube-prometheus. That can show `reqs/sec`, but not `reward` and  `latency`, like below.

![image](https://user-images.githubusercontent.com/9139212/158102947-44694b45-cb84-4953-848c-5c90a403c548.png)

## To reproduce
1. Add ServiceMonitor for seldon-core
    ```yaml
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: seldon-core-monitor
      namespace: monitoring
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/managed-by: seldon-core
      endpoints:
      - targetPort: 8000
        path: /prometheus
      - targetPort: 6000
        path: /prometheus
      namespaceSelector:
        any: true
    ```
2. Edit ClusterRole `prometheus-k8s` for role of getting service, pod, etc.
    ```yaml
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
      name: prometheus-k8s
    rules:
    - apiGroups:
      - ""
      resources:
      - nodes/metrics
      verbs:
      - get
    - nonResourceURLs:
      - /metrics
      verbs:
      - get
    - apiGroups:
      - ""
      resources:
      - nodes
      - services
      - endpoints
      - pods
      verbs:
      - get
      - list
      - watch
    ```
3. Deploy
    ```yaml
    apiVersion: machinelearning.seldon.io/v1
    kind: SeldonDeployment
    metadata:
      name: iris-model
      namespace: seldon
    spec:
      name: iris
      predictors:
      - graph:
          implementation: SKLEARN_SERVER
          modelUri: gs://seldon-models/v1.14.0-dev/sklearn/iris
          name: classifier
        name: default
        replicas: 1
    ```
4. Call predictions api and check monitor information in promethus

## Expected behaviour

Prediction Analytics Dashboard into grafana of  kube-prometheus is the same as seldon-core-analytics.

## Environment
- Cloud Provider: On-premises
- Kubernetes Cluster Version: 
    ```
    Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:05:33Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:00:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
    ```
- Seldon Images:
    ```
    value: docker.io/seldonio/seldon-core-executor:1.13.1
    image: docker.io/seldonio/seldon-core-operator:1.13.1
    ```
- kube-prometheus: release-8.0

**Comment by cliveseldon** [comment]
Thanks @passerbyflutter for starting this. It would be great to have a PR for kube-prometheus integration.
I think you might need to use PodMonitor as the metrics path is not exposed. Also it would be `/metrics` I think.

@RafalSkolasinski any further comments?

**Comment by agrski** [comment]
As-is, `seldon-core-analytics` is pretty much just a thin wrapper around the standard, non-operator Prometheus Helm charts.
The main differences it introduces are:
* Some extra rules (available in the Helm charts)
* Using ports named `metrics` to get around the limitation that Prometheus scrape annotations are designed for only a single port _per pod_ providing metrics

The latter should be straightforward to change to use pod monitors, as @cliveseldon suggests.  For the former, it's just a case of checking what extra rules we do define and porting those across into the native kube-prometheus rules resources.

**Comment by RafalSkolasinski** [comment]
Yes, I did not have lack with `ServiceMonitor` when working on OpenShift recently, the `PodMonitor` did work quite well
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-podmonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: seldon-core
  podMetricsEndpoints:
    - port: metrics
      path: /prometheus
```

**Comment by agrski** [comment]
> Yes, I did not have lack with `ServiceMonitor` when working on OpenShift recently, the `PodMonitor` did work quite well

That's expected, as only the inference endpoints are exposed via `service`s

**Comment by passerbyflutter** [comment]
I try PodMonitor to monitor `seldon-controller-manager`, but still loss reward and latency on Prediction Analytics Dashboard in grafana of kube-prometheus

![image](https://user-images.githubusercontent.com/9139212/158152261-ad9c9218-56c1-446a-9c06-39da1ae9a472.png)

![image](https://user-images.githubusercontent.com/9139212/158152392-c37e1ae3-baec-4822-a64e-86ff8811f72e.png)

**Comment by RafalSkolasinski** [comment]
You need to add PodMonitor in namespace that you deploy your models, on the targets screen I only see it picking up the controller (operator) pod.

**Comment by passerbyflutter** [comment]
I try use PodMonitor to get metrics. Great! That works. Thx all.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-podmonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: seldon-core
  podMetricsEndpoints:
    - port: metrics
      path: /prometheus
  namespaceSelector:
    any: true
```

![image](https://user-images.githubusercontent.com/9139212/158305457-1fe28b07-5553-48b2-bae1-4c68178bc8b3.png)

![image](https://user-images.githubusercontent.com/9139212/158305410-c0e601ba-1bff-4ead-8085-12e6859c5a6a.png)

But I can't understand the difference between PodMonitor and ServiceMonitor. The both get metrics by the same endpoint of targets in prometheus. The endpoint is `http://{pod-ip}:6000/prometheus` or  `http://{pod-ip}:8000/prometheus` .
