### ISSUE TITLE
Possibility to use IAM roles for S3 storage initializer

### ISSUE THREAD

**Issue by igor-stranjanac** [SeldonIO/seldon-core#4015]
Is there a possibility to use IAM roles for S3 bucket storage initializers?

I have seen [here ](https://docs.seldon.io/projects/seldon-core/en/latest/reference/seldon-deployment.html#seldon-deployment-reference-types) that there is a serviceAccountName field and [here ](https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html?#example-aws-s3-with-iam-roles-configuration) that a secret should be added.

But even though I have added a serviceAccount with annotated role with appropriate permissions to the S3 bucket, the storage initializer is not copying model artifacts.

Am I missing something?

**Comment by axsaucedo** [comment]
Currently the provided examples are not configured to work with IAM roles, only leveraging username and secret - there may be a way to enable IAM roles as we use rclone which has quite a broad support, but you would have to explore this further through the rclone documentation, as it would be a challenge more on those capabilities as opposed to specifically seldon features https://rclone.org/s3/

**Comment by axsaucedo** [comment]
Closing as this seems to be a more rclone specific question

**Comment by igor-stranjanac** [comment]
@axsaucedo , thanks for the response. I have one extra question: I am trying to test by using the docu from [here](https://docs.seldon.io/projects/seldon-core/en/latest/examples/custom_init_container.html#Custom-Init-Container-(full-inline-definition)). I am trying something like this:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: test-deployment
  namespace: test-ns
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        serviceAccountName: seldon-service-account
        containers:
        - name: classifier
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location
            readOnly: true

        initContainers:
        - name: classifier-model-initializer
          image: rclone/rclone:latest
          imagePullPolicy: IfNotPresent

          args:
            - "copy"
            - "<s3 model uri>"
            - "/mnt/models"

          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          - name: config
            mountPath: "/config/rclone"
            readOnly: true

        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        - name: config
          secret:
            secretName: mysecret

    graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: <s3 model uri>
      name: classifier
      parameters:
      - name: xtype
        type: STRING
        value: DataFrame
    name: default
    replicas: 1
```
The problem is that it is asking for me the image for the 'classifier' container. How to use the MLFLOW_SERVER implementation in this example? Is this the good way on how to approach this kind customization of the init container?
Of course, in the next probably if this works, I would create an image for the init container of my own, but this I'm just now trying to use in order to debug.
