### ISSUE TITLE
Input datatype mismatch for TENSORFLOW_SERVER model

### ISSUE THREAD

**Issue by souravmaitra2** [SeldonIO/seldon-core#4019]
Hi,
I am trying to deploy a tf-serve model trained in nvtabular. The input datatypes are of INT64 and FLOAT32 type. While calling the inference server I am getting the following error:
   **"error": "[_Derived_]{{function_node __inference_signature_wrapper_1152148}} {{function_node __inference_signature_wrapper_1152148}} input segment_ids[0] expected type int32 != int64, the type of model/dense_features/adid_embedding/adid_embedding_weights/embedding_lookup_sparse/strided_slice:output:0[0]\n\tIn {{node model/dense_features/adid_embedding/adid_embedding_weights/embedding_lookup_sparse}}\n\t [[StatefulPartitionedCall]]\n\t [[StatefulPartitionedCall]]"**

the yaml file I am using:
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: ctrnvtlf
  namespace: seldon
spec:
  name: ctrads
  predictors:
  - graph:
      children: []
      implementation: TENSORFLOW_SERVER
      modelUri: gs://seldon-models-sourav/tf-serve/REAL_TIME_V1
      name: ctrnvtlf
      parameters:
        - name: signature_name
          type: STRING
          value: predict_images
        - name: model_name
          type: STRING
          value: ctrnvtlf
    name: default
    replicas: 2
```
the above gcs destination has the model file present
