### ISSUE TITLE
Is it possible to disable creation of service for each PU container in the inference graph

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#4036]
I have an inference graph like

```yaml
    graph:
      name: output-transformer
      type: OUTPUT_TRANSFORMER
      endpoint:
        type: GRPC
      children:
        - name: input-transformer
          type: TRANSFORMER
          endpoint:
            type: GRPC
          children:
            - name: model
              type: MODEL
              endpoint:
                type: GRPC
```

it looks seldon will create a service for each PU.

But I notice not all PU services can find the pod because the pod selector in the service definition are like

```yaml
...
selector:
  seldon-app-svc: myapp-myapp-myapp-output-transformer
...
selector:
  seldon-app-svc: myapp-myapp-myapp-input-transformer
...
selector:
  seldon-app-svc: myapp-myapp-myapp-model
...
```

But in the pod created, the labels only include

```
seldon-app-svc: myapp-myapp-myapp-output-transformer
```

as the output-transformer is the root (I guess). So only the output transformer container service works. The other two PU service won't find the running pod for them.

Questions:
1. is this a bug?
2. why is it necessary to create a service for each PU as only the seldon executor (aka. engine, orchestrator) container is exposed to external applications? Is it possible to disable the creation of the PU services, they appear to create confusion in `k get svc`.
