### ISSUE TITLE
Seldon Core Integration with Triton Inference Server and Kafka

### ISSUE THREAD

**Issue by SwathiAunooru-wavelabs** [SeldonIO/seldon-core#4057]
I would like to know if there is a reference guide for deploying a Tensorflow model that uses Triton Inference Protocol and also runs with Kafka. I have been trying this and facing a few internal errors.

This is the YAML I'm using
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: ktserver
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: ktserver
    graph:
      implementation: TRITON_SERVER
      modelUri: gs://modde/model
      name: ktserver
    name: default
    svcOrchSpec:
      env:
      - name: KAFKA_BROKER
        value: my-cluster-kafka-brokers.default.svc.cluster.local:9092
      - name: KAFKA_INPUT_TOPIC
        value: model-input
      - name: KAFKA_OUTPUT_TOPIC
        value: model-output
    replicas: 1
  protocol: v2
```
And I could send the messages to the input topic and while checking the messages at the output topic this is the error I'm facing.
```
Container is in Exited State
```
All references or suggestions will be appreciated. 
Thank you.

**Comment by SwathiAunooru-wavelabs** [comment]
I'm trying to read the messages from the Kafka output topic.
```
kubectl run --quiet=true -it --rm kafkaproducer --image=bitnami/kafka:2.6.0 --restart=Never --command -- \
    kafka-console-consumer.sh --bootstrap-server *.*.*.*:9094 --topic model-output \
        --from-beginning --timeout-ms 10000 
```
 This is the actual error I'm getting 
```
E0415 12:33:06.340966   52762 v3.go:79] EOF
                                           E0415 12:33:06.341098   52762 v3.go:79] EOF
                                                                                      Error attaching, falling back to logs: Internal error occurred: error attaching to container: container is in CONTAINER_EXITED state
[2022-04-15 07:03:05,002] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.errors.TimeoutException
Processed a total of 0 messages
```

**Comment by SwathiAunooru-wavelabs** [comment]
hi, @seldondev I have resolved the and here we need to make sure to give the deployment name the same as a model name. 
The yaml configuration that worked for me is below.
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rul2
spec:
  serverType : kafka
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: rul2
          resources:
            requests:
              cpu: 5
            limits:
              cpu: 5
    graph:
      implementation: TRITON_SERVER
      modelUri: gs://modde/RUL2
      name: rul2
    name: default
    svcOrchSpec:
      env:
      - name: KAFKA_BROKER
        value: my-cluster-kafka-brokers.default.svc.cluster.local:9092
      - name: KAFKA_INPUT_TOPIC
        value: model-input
      - name: KAFKA_OUTPUT_TOPIC
        value: model-output
    replicas: 1
  protocol: kfserving
  ```
