### ISSUE TITLE
set canary traffic with 100:0 but got 50:50

### ISSUE THREAD

**Issue by shuaiyy** [SeldonIO/seldon-core#4067]
## Describe the bug

Im running the canary demo with ambassador, and i found if set the new version's traffic to 0, and base trafic 100,  two version get 50% 50% traffic.

is this a feature or bug?  should i just delete the new version when perform rollback?

by the way, set base version traffic =0 and new traffic = 100 is ok

## To reproduce

```yaml
---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-model-canary
spec:
  name: model-canary
  annotations:
    sidecar.istio.io/inject: "false"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier:1.11.0
          imagePullPolicy: IfNotPresent
          name: classifier
          resources:
            requests:
              memory: 1Mi
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      name: classifier
      endpoint:
        type: REST
      type: MODEL
    name: main
    replicas: 1
    traffic: 100
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier:1.12.0
          imagePullPolicy: IfNotPresent
          name: mean-classifier
          resources:
            requests:
              memory: 1Mi
    graph:
      children: []
      name: mean-classifier
      endpoint:
        type: REST
      type: MODEL
    name: canary
    replicas: 1
    traffic: 0
```

```python
payload={"data": {"ndarray":[[1.0, 2.0, 5.0, 6.0]]}}
a=0
b=0
for i in range(1000):
    resp = requests.post(url, json=payload)
    if b"1.11.0" in resp.content:
        a += 1
    if b"1.12.0" in resp.content:
        b += 1
    time.sleep(0.001)
print(a, b, a+b)
```

## Expected behaviour

i hope new version will receive 0% traffic, but got 50% 
521 479 1000

#### Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"d966b365d87fb2783deab0d244047d340f1be146", GitTreeState:"clean", BuildDate:"2022-01-19T01:10:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"} \n\n

#### Seldon Images:
        value: docker.io/seldonio/seldon-core-executor:1.13.1
        image: docker.io/seldonio/seldon-core-operator:1.13.1
