### ISSUE TITLE
typo in "Pretrained GPT2 Model Deployment Example" notebook

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/seldon-core#4080]
## Describe the bug
I think there is a typo in the following notebook [Pretrained GPT2 Model Deployment Example](https://docs.seldon.io/projects/seldon-core/en/latest/examples/triton_gpt2_example.html)

```
!mc mb minio-seldon/onnx-gpt2 -p
!mc cp ./model.onnx minio-seldon/onnx-gpt2/gpt2/1/
```

Should be
```
!mc mb minio-seldon/onnx-gpt2 -p
!mc cp ./model.onnx minio-seldon/onnx-gpt2
```

as in the:

```
%%writefile gpt2-deploy.yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: gpt2
spec:
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: s3://onnx-gpt2
      envSecretRefName: seldon-init-container-secret
      name: gpt2
      type: MODEL
    name: default
    replicas: 1
  protocol: kfserving
```

In the current format in the website init container was not able to find the model from Minio but putting the model in the root directory of the minio bucket solved the problem.
