### ISSUE TITLE
How to use images from private repos?

### ISSUE THREAD

**Issue by karolmigo** [SeldonIO/seldon-core#4087]
## Describe the bug

No matter what I do, I can't make seldon to pull from a private repository

## To reproduce

Use a manifest below:

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: example-model
  namespace: default
spec:
  name: example-model-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: model-router
          image: myrepo/seldon:model-router1
          imagePullPolicy: Always
          env:
            - name: MODEL_MAPPING
              value: |-
                ---
                ganymede-a: 0
                ganymede-b: 1
        - name: ganymede-a
          image: myrepo/seldon:example-model
          imagePullPolicy: Always
        - name: ganymede-b
          image: myrepo/seldon:example-model
          imagePullPolicy: Always
        imagePullSecrets:
          - name: docker-creds
    graph:
      name: model-router
      type: ROUTER
      children:
      - name: ganymede-a
        type: MODEL
        endpoint:
          type: REST
        children: []
      - name: ganymede-b
        type: MODEL
        endpoint:
          type: REST
        children: []
    name: graph
    replicas: 1
```

## Expected behaviour
I'd expect seldon to be able to pull from a private repo

## Environment
* Cloud Provider: AWS/EKS
* Kubernetes Cluster Version: 1.21
* Deployed Seldon System Images: only seldon-core-operator in latest version
