### ISSUE TITLE
Adding separate pod/deployment option to documentation

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/seldon-core#4092]
Hi Seldon team,

I followed the https://docs.seldon.io/projects/seldon-core/en/latest/examples/transformers-v2-protocol.html and https://docs.seldon.io/projects/seldon-core/en/latest/examples/graph-metadata.html to make a simple inference graph and I first ended up with the following scheme:
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: linear-pipeline-single-pod
spec:
  name: linear-pipeline
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/linearmodel:nodeone
          name: node-one
        - image: sdghafouri/linearmodel:nodetwo
          name: node-two
        - image: sdghafouri/linearmodel:nodethree
          name: node-three
    graph:
      name: node-one
      type: MODEL
      children:
      - name: node-two
        type: MODEL
        children:
        - name: node-three
          type: MODEL
          children: []
    labels:
      sidecar.istio.io/inject: "true"
    name: example
```
which was pretty similar to most of the examples in the documentation, however, for my usecase I needed to have three different pods for each nodes instead of having them in the same pod and I struggled to find a solution to this, I finally ended up with the following which I think is doing what I need:
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: linear-pipeline-separate-pods
spec:
  name: linear-pipeline
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/linearmodel:nodeone
          name: node-one
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/linearmodel:nodetwo
          name: node-two
          imagePullPolicy: Always
    - spec:
        containers:
          - image: sdghafouri/linearmodel:nodethree
            name: node-three
            imagePullPolicy: Always
    graph:
      name: node-one
      type: MODEL
      children:
      - name: node-two
        type: MODEL
        children:
        - name: node-three
          type: MODEL
          children: []
    labels:
      sidecar.istio.io/inject: "true"
    name: example
```

I couldn't find a solid explanation of the differences between the two cases in the documentation and the availability of the second method (separate pods) and I accidentally find my answer when I was checking how to replicate each node in the https://docs.seldon.io/projects/seldon-core/en/latest/graph/scaling.html Therefore I think it would be nice to add some explanation somewhere in the document about the distinction and availability of both options and maybe the pros and cons (e.g. I think the per node scaling is only available in the separated pod options).

Thank you!
