### ISSUE TITLE
Unable to send input to the model which is ochestrates in graph format

### ISSUE THREAD

**Issue by SwathiAunooru-wavelabs** [SeldonIO/seldon-core#4173]
Hello @cliveseldon, I have followed this document for creating a tokenizer https://docs.seldon.io/projects/seldon-core/en/latest/examples/transformers-v2-protocol.html and I have given input in v2 protocol format only
Below is the YAML file I'm using for it, I have modified the above YAML file

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rul2
spec:
  protocol: v2
  predictors:
    - name: default
      graph:
        name: preprocess
        type: MODEL
        endpoint:
          type: REST        
        children:
          - name: rul2
            implementation: TRITON_SERVER
            modelUri: gs://modde/RUL2
      componentSpecs:
        - spec:
            containers:
              - name: preprocess
                image: <image>
                env:
                    -  name: TRANSFORMERS_CACHE
                       value: /opt/mlserver/.cache
                    -  name: MLSERVER_MODEL_NAME 
                        value: "preprocess"
```

When I run above YAML I could see the successful deployment in the GKE console. and in this use case, I have been running a model which was a TensorFlow-based saved_model.
Here is the sample input followed by its output

```
curl --location --request POST 'http://localhost:8000/seldon/default/graph-metadata-input/v2/models/infer' \ --header 'Content-Type: application/json' \
  --data-raw '{
  "inputs": [ {
  "name": "dense_10_input",
  "datatype": "FP32",
  "shape": [1,24],
  "data": [<input-data>]
  } ]
  }'
```

Output Response:

```
404 page not found
```
