### ISSUE TITLE
bug: rclone fails to download resources from `us-west-2` region with S3 bucket key

### ISSUE THREAD

**Issue by brightsparc** [SeldonIO/seldon-core#4204]
## Describe the bug

When testing `rclone-storage-initializer` to download models from a `us-west-2` bucket, I am seeing an error due to the default region appearing to be `us-east-1` and the bucket files to be encrypted with a bucket key that is not accessible.

Is there a way to set the default `AWS_DEFAULT_REGION` env variable when download models?

### Step to reproduce

1. create secret config for s3 access key and secret that can read `YOUR_BUCKET`

```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: "s3"
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"
EOF
```

2. Create the a pod to test storage initializer

```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: rclone-pod
spec:
  containers:
  - name: rclone
    image: seldonio/rclone-storage-initializer:1.15.0-dev
    command: [ "/bin/sh", "-c", "--", "sleep 3600"]
    envFrom:
    - secretRef:
        name: seldon-rclone-secret
EOF
```

3. Attempt to copy the `model_repository` folder from `YOUR_BUCKET` to the container.

```
kubectl exec -it rclone-pod -- rclone -v copy s3:YOUR_BUCKET/model_repository/ .
```

The following error is returned

```
2022/07/04 05:53:34 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2022/07/04 05:53:36 NOTICE: S3 bucket <<<YOUR_BUCKET>>> path model_repository: Switched region to "us-west-2" from "us-east-1"
2022/07/04 05:53:38 ERROR : <<<model_repository/YOUR_FILE>>>: Failed to copy: failed to open source object: AccessDenied: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
    status code: 403, request id: MM0Y02XCFD3YCPJV, host id: hZcD/6yDs8Ml5tv8DeJ39RBg+ubNr1+IQqF6d0GgiGQF2+I6+GrJOIKmGJZcu5O+pMHpJ8+T5nE=
```

## Expected behaviour
I attempted to set an environment variable when creating the `rclone-pod`, but this didn't seem to propogate eg:

```
    env:
    - name: AWS_DEFAULT_REGION
      value: "us-west-2"
```

I get no output when running this

```
kubectl exec -it rclone-pod -- echo $AWS_DEFAULT_REGION
```

I experience the same error when running `rclone` as part of seldon-operator deployment.

## Environment

* Cloud Provider: `k3d` (local)

#### Kubernetes version:
 Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:29:46Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/arm64"} 

#### Seldon Images:
          value: docker.io/seldonio/seldon-core-executor:1.14.0
        image: docker.io/seldonio/seldon-core-operator:1.14.0
