### ISSUE TITLE
Status value Long duration Creating

### ISSUE THREAD

**Issue by chijunqing** [SeldonIO/seldon-core#4224]
**version**
seldon core version  1.13.1

**doubt**
at seldon core , deploy seldonployment  on kubernetes；
1、 How do I set the timeout period, other than the long time Creating state？
2、Undo the last deploy？ Similar kubernetes  ； _kubectl rollout undo_

 **at kubernetes website** 
Your Deployment may get stuck trying to deploy its newest ReplicaSet without ever completing. This can occur due to some of the following factors:

- Insufficient quota
- Readiness probe failures
- Image pull errors
- Insufficient permissions
- Limit ranges
- Application runtime misconfiguration

One way you can detect this condition is to specify a deadline parameter in your Deployment spec: ([.**spec.progressDeadlineSeconds**](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progress-deadline-seconds)). .spec.progressDeadlineSeconds denotes the number of seconds the Deployment controller waits before indicating (in the Deployment status) that the Deployment progress has stalled.

Once the deadline has been exceeded, the Deployment controller adds a DeploymentCondition with the following attributes to the Deployment's .status.conditions:
```

type: Progressing
status: "False"
reason: ProgressDeadlineExceeded

```

**at seldon core ,  The state is always  creating。**
if seldondeployment.yaml file ,add  progressDeadlineSeconds  properties  ， **unknown field "progressDeadlineSeconds"**  

For example,
 ```

kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: canary-example2
  namespace: default
spec:
  predictors:
  - componentSpecs:
    - spec:
        progressDeadlineSeconds: 60
        containers:
        - name: classifier
          resources:
            requests:
              cpu: 2000m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 512Mi
    name: baseline1
    replicas: 1 
    traffic: 100
    graph:
      name: classifier
      modelUri: gs://seldon-models/v1.14.0-dev/sklearn/iris
      implementation: SKLEARN_SERVER
  
END

```
error message:  unknown field 
`"progressDeadlineSeconds" in io.seldon.machinelearning.v1.SeldonDeployment.spec.predictors.componentSpecs.spec;`

Thank you very much for your help
