### ISSUE TITLE
model service  Update the deployment ,old svc will not be deleted

### ISSUE THREAD

**Issue by chijunqing** [SeldonIO/seldon-core#4253]
> describe：update model name,  redeploy ,old svc will not be deleted 
seldon core version 1.13.1

### First Deployment
name is v1 
```
kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: canary-example
  namespace: default
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          resources:
            requests:
              cpu: 2000m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 512Mi
    name: v1
    replicas: 1 
    traffic: 100
    graph:
      name: classifier
      modelUri: gs://seldon-models/v1.14.0-dev/sklearn/iris
      implementation: SKLEARN_SERVER
  
END
```
POD：Only the v1
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/4150209/182589734-0ec3898b-6eb0-4847-8546-23b6af487f22.png">

SVC：Only the v1
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/4150209/182589454-cdcf2cf9-ce93-4b88-9911-5c8ca95f6d0f.png">

### redeploy 
update name, to v2 ;
```
kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: canary-example
  namespace: default
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          resources:
            requests:
              cpu: 2000m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 512Mi
    name: v2
    replicas: 1 
    traffic: 100
    graph:
      name: classifier
      modelUri: gs://seldon-models/v1.14.0-dev/sklearn/iris
      implementation: SKLEARN_SERVER
  
END
```

POD：Only the v2
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/4150209/182591342-f0d4c189-ef24-43b1-a802-6ce634afbe42.png">

SVC： v1 and v2 exist simultaneously 
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/4150209/182591860-e115125b-ca1a-4567-93f6-2d070bfd0f1a.png">
