### ISSUE TITLE
Problem in the adding metedata to Seldon graph following the documentaiton

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/seldon-core#4303]
## Describe the bug
As per our conversation over [Slack](https://seldondev.slack.com/archives/C03DQFTFXMX/p1661526920540159?thread_ts=1661438086.861089&cid=C03DQFTFXMX) the metaata example in the documentation does not have the expected behavior and result in a microservice error.

## To reproduce
using following minimal example from [doc](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#returning-tags).
```python
from seldon_core.user_model import SeldonResponse


class Model:
    def predict(self, X, names=[], meta={}):
        runtime_metrics = {"type": "COUNTER", "key": "instance_counter", "value": len(X)},
        runtime_tags = {"runtime": "tag", "shared": "right one"}
        return SeldonResponse(data=X, metrics=runtime_metrics, tags=runtime_tags)

    def metrics(self):
        return [{"type": "COUNTER", "key": "requests_counter", "value": 1}]

    def tags(self):
        return {"static": "tag", "shared": "not right one"}
```
with dockerfile:
```Docerfile
FROM python:3.8-slim
WORKDIR /app

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000
EXPOSE 9000

ENV MODEL_NAME test.Model
ENV SERVICE_TYPE MODEL
# ENV FLASK_DEBUG True
ENV TORCH_HOME /app/.torch
# ENV FLASK_SINGLE_THREADED 1
# ENV GUNICORN_WORKERS 0
# ENV GUNICORN_THREADS 0
# ENV GRPC_WORKERS 0
# ENV SELDON_DEBUG 1

RUN chown -R 8888 /app

# CMD exec python cascade_resnet.py
CMD exec seldon-core-microservice $MODEL_NAME --service-type $SERVICE_TYPE
```
and yaml:
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: testmeta
spec:
  name: testmeta
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/testmeta:latest
          name: testmeta
          imagePullPolicy: Always
    graph:
      name: testmeta
      type: MODEL
      children: []
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
```
The follwing client:
```python
from seldon_core.seldon_client import SeldonClient
from pprint import PrettyPrinter
pp = PrettyPrinter(indent=4)

# single node inferline
gateway_endpoint="localhost:32000"
deployment_name = 'testmeta'
namespace = "default"
sc = SeldonClient(
    gateway_endpoint=gateway_endpoint,
    gateway="istio",
    transport="rest",
    deployment_name=deployment_name,
    namespace=namespace)

# image = np.array(image)
response = sc.predict(
    str_data="sample input"
)

pp.pprint(response.response)
```
results in:
```bash
{   'status': {   'code': -1,
                  'info': 'Bad metric created during request: [{"type": '
                          '"COUNTER", "key": "instance_counter", "value": 12}]',
                  'reason': 'MICROSERVICE_BAD_METRIC',
                  'status': 1}}
```

## Expected behavior

not returning an error.

## Environment

* Cloud Provider: Bare Metal
* Kubernetes Cluster Version
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-2+59bbb3530b6769", GitCommit:"59bbb3530b6769e4935a05ac0e13c9910c79253e", GitTreeState:"clean", BuildDate:"2022-05-13T06:41:13Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```
* Deployed Seldon System Images:
```
value: docker.io/seldonio/seldon-core-executor:1.14.0
image: docker.io/seldonio/seldon-core-operator:1.14.0
```
