### ISSUE TITLE
Seldon container engine fails to start

### ISSUE THREAD

**Issue by RyanZgmzpn** [SeldonIO/seldon-core#4380]
seldon-core-operator:1.7.0-dev
seldon-core-executor:1.9.1

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: distri-image1
  namespace: seldon
spec:
  annotations:
    seldon.io/engine-seldon-log-messages-externally: "true"
    seldon.io/grpc-timeout: "100000"
    seldon.io/rest-timeout: "100000"
  name: distri-image1
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: "1"
          - name: GUNICORN_THREADS
            value: "10"
          - name: SELDON_LOG_LEVEL
            value: INFO
          image: seldonio/metadata-generic-node:1.14.0-dev
          imagePullPolicy: Always
          name: b
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 512m
          securityContext:
            runAsUser: 0
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: "1"
          - name: GUNICORN_THREADS
            value: "10"
          - name: SELDON_LOG_LEVEL
            value: INFO
          image: seldonio/metadata-generic-node:1.14.0-dev
          imagePullPolicy: Always
          name: c
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 512m
          securityContext:
            runAsUser: 0

        - env:
          - name: GUNICORN_WORKERS
            value: "1"
          - name: GUNICORN_THREADS
            value: "10"
          - name: SELDON_LOG_LEVEL
            value: INFO
          image: seldonio/metadata-generic-node:1.14.0-dev
          imagePullPolicy: Always
          name: a
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 512m
          securityContext:
            runAsUser: 0

    engineResources: {}
    graph:
      children:
      - endpoint:
          type: REST
        logger:
          mode: all
        name: b
        type: MODEL
      - endpoint:
          type: REST
        logger:
          mode: all
        name: c
        type: MODEL
      endpoint:
        type: REST
      logger:
        mode: all
      name: a
      type: COMBINER
    name: default
    replicas: 1
    svcOrchSpec: {}
    traffic: 100
  protocol: seldon
```

Hi, Team:

Above is the sdep yaml file we use to create an seldon deployment, but the seldon container engine failed to start.

Could you help to check whether inference graph on several pods like this is supported?
