### ISSUE TITLE
Change container image of TENSORFLOW_SERVER with seldon protocol in SeldonDeployment not work

### ISSUE THREAD

**Issue by duychu** [SeldonIO/seldon-core#4403]
## Describe the bug

I want to customize the TfServingProxy to have some custom metrics, so I try to test custom manifest that specify image of tfserving-proxy, 

But when checking the deployment, Pod still uses the default image configured in helm chart

## To reproduce
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: enm-4g-6d022256c473291a-proxy-custom
  namespace: analytics-ml-serving
spec:
  name: enm-4g-6d022256c473291a-proxy-custom
  protocol: seldon  #seldon proxy tensorflow protocol
  transport: rest
  predictors:
  - graph:
      children: []
      implementation: TENSORFLOW_SERVER
      modelUri: s3://***/tensorflow-serve/0a88c407-f7e7-444c-ab03-06b6c99ed1f7
      name:  tfmodel
      envSecretRefName: seldon-rclone-secret-external
      parameters:
        - name: model_name
          type: STRING
          value: tfmodel
    name: default
    replicas: 1
    componentSpecs:
      - spec:
          containers:
            - name: tfmodel
              image: seldonio/tfserving-proxy:1.14.0    # <=== THIS

```

Note that version I put here is `1.14.0`

Pod is up and running

```
kubectl get pod -n analytics-ml-serving
NAME                                                              READY   STATUS    RESTARTS   AGE
enm-4g-6d022256c473291a-proxy-custom-default-0-tfmodel-f4dfdsjd   4/4     Running   0          33m
```

but what I get from Pod describe is still `1.13.1`

```
kubectl describe pod -n analytics-ml-serving enm-4g-6d022256c473291a-proxy-custom-default-0-tfmodel-f4dfdsjd | grep Image:
    Image:         seldonio/rclone-storage-initializer:1.13.1
    Image:         istio/proxyv2:1.13.2
    Image:          seldonio/tfserving-proxy:1.13.1
    Image:         tensorflow/serving:2.1.0
    Image:         seldonio/seldon-core-executor:1.13.1
    Image:         istio/proxyv2:1.13.2
```

This is helm chart configuration

```
predictor_servers:
...
  TENSORFLOW_SERVER:
    protocols:
      seldon:
        defaultImageVersion: "1.13.1"
        image: "{{ docker_registry }}/seldonio/tfserving-proxy"
      tensorflow: 
        defaultImageVersion: 2.1.0
        image:  "{{ docker_registry }}/tensorflow/serving"
...
```

## Expected behaviour
It is expected that we can change tfserving-proxy image in SeldonDeployment manifest 

## Environment
I run it on k8s 

```
NAME                      STATUS   ROLES                                AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION     CONTAINER-RUNTIME
analytics-control-plane   Ready    control-plane,master                 45h   v1.21.1   172.19.0.5    <none>        Ubuntu 21.04   5.4.0-90-generic   containerd://1.5.2
analytics-worker          Ready    compute_node,database_node           45h   v1.21.1   172.19.0.3    <none>        Ubuntu 21.04   5.4.0-90-generic   containerd://1.5.2
analytics-worker2         Ready    compute_node,database_node,ml_node   45h   v1.21.1   172.19.0.4    <none>        Ubuntu 21.04   5.4.0-90-generic   containerd://1.5.2
analytics-worker3         Ready    compute_node,ml_node                 45h   v1.21.1   172.19.0.2    <none>        Ubuntu 21.04   5.4.0-90-generic   containerd://1.5.2
```

```
helm list -n analytics-ml-serving
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
seldon-core-operator    analytics-ml-serving    1               2022-10-24 08:01:09.081029983 +0000 UTC deployed        seldon-core-operator-1.13.1     1.13.1  
```
