### ISSUE TITLE
v2 model load with an uri that is invalid (not existent path) fails with unhelpful message

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#4479]
e.g.

```
piVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: iris
spec:
  storageUri: "gs://seldon-models/scv2/xyz"
  requirements:
  - sklearn

```

```
time="2022-12-05T15:46:03Z" level=info msg="Calling Rclone server: /sync/copy with {\"srcFs\":\"gs://seldon-models/scv2/xyz\",\"dstFs\":\"/mnt/agent/rclone/1495806312\",\"createEmptySrcDirs\":true}" Source=RCloneClient
time="2022-12-05T15:46:04Z" level=info msg="rclone response: {}\n" Source=RCloneClient
time="2022-12-05T15:46:04Z" level=error msg="Failed to handle load model iris:1" Name=Client error="lstat /mnt/agent/rclone/1495806312: no such file or directory"
```

```
seldon model list
model	state		reason
-----	-----		------
iris	ModelFailed	lstat /mnt/agent/rclone/1495806312: no such file or directory
```
