### ISSUE TITLE
Problem with Payload Logger set up for ROUTER model

### ISSUE THREAD

**Issue by krishadhithya** [SeldonIO/seldon-core#4489]
In the helm chart for my `SeldonDeployment`, when I specify it in the parent ROUTER model , no logs are sent (code snippet 1)
I need to specify (code snippet 2) to get it to work

Is there a better way to configure the logger to be called for the entire graph instead of specifying the logger in each of the children?

Reason here is that when specifying inference graphs of increasing complexity, ideally, I'd like to be able to log payloads for request and response payload going into/out of the entire graph. Not individual components.

*Code snippet 1:*
```
graph:
      children: 
        - name: <model_A>
          type: MODEL
        - name: <model_B>
          type: MODEL
      name: <router_name>
      type: ROUTER
      logger:
            url: <url>
            mode: all
      endpoint:
        type: REST
```
*Code snippet 2:*
```
graph:
      children: 
        - name: <model_A>
          type: MODEL
          logger:
            url: <url>
            mode: all
        - name: <model_B>
          type: MODEL
          logger:
            url: <url>
            mode: all
      name: <router_name>
      type: ROUTER
      endpoint:
        type: REST
```
