### ISSUE TITLE
Query: Support for R models

### ISSUE THREAD

**Issue by that-rahul-guy** [SeldonIO/seldon-core#4601]
Hello,
Currently we are using the Seldon Core to serve models trained in python by logging and storing the model artifacts in Minio S3 via MlFlow. Then passing the s3 uri containing model artifacts to create a SeldonDeployment in Kubernetes as follows:
```
graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: <S3_model_uri>
      envSecretRefName: seldon-init-container-secret
      name: serving-container
      type: MODEL
```

### Queries:
- Is there support for deploying R models (RDS or crate) in the similar manner as above?
- When looking for references, I could find 2 methods:
      a. [Using Docker](https://docs.seldon.io/projects/seldon-core/en/latest/R/r_wrapping_docker.html) 
      b. [Using S2I](https://docs.seldon.io/projects/seldon-core/en/latest/R/README.html)
    But in both these, we are building the images ourselves.
    Can Seldon directly pick the model artifacts from S3?
- Also, any references for providing the custom `preprocess` and `postprocess` function to the deployment for models in R?

Please point me to the refences. It'll be very helpful.
Thanks!
