### ISSUE TITLE
Controller does not update Servers (statefulsets) after ServerConfig changes

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#4615]
When updating the `ServerConfig` the V2 operator does not pick up changes and reconciles `Server` instances as expected. 

Can be reproduced by on `2.1.0` installation (with values given bellow)
```
seldon-core-v2-components	seldon   	1       	2023-01-23 11:09:06.741068369 +0000 UTC	deployed	seldon-core-v2-setup-2.1.0  	2.1.0      
seldon-core-v2-servers   	seldon   	1       	2023-01-23 11:11:16.706295475 +0000 UTC	deployed	seldon-core-v2-servers-2.1.0	2.1.0   
```

1. Verify MLServer image to be 1.2.3 with 
   ```
   kubectl get statefulsets -n seldon mlserver -o json | jq .spec.template.spec.containers[].image
   "docker.io/seldonio/seldon-rclone:2.1.0"
   "docker.io/seldonio/seldon-agent:2.1.0"
   "docker.io/seldonio/mlserver:1.2.3"
   ```

2. `kubectl edit serverconfig -n seldon mlserver` to set mlserver image to 1.2.2
3. observe that operator does not reconcile statefulsets to the new image definition
4. after restarting `seldon-controller-manager-xxx` pod statefulsets get reconciled.

## Extra details:
<details><summary>Components Helm Values</summary>
<p>

```
USER-SUPPLIED VALUES:
dataflow:
  resources:
    cpu: 500m
envoy:
  service:
    type: ClusterIP
kafka:
  bootstrap: seldon-kafka-bootstrap.kafka:9092
  topics:
    numPartitions: 4
opentelemetry:
  enable: false
scheduler:
  service:
    type: ClusterIP
serverConfig:
  mlserver:
    resources:
      cpu: 1
      memory: 1Gi
  triton:
    resources:
      cpu: 1
      memory: 1Gi
serviceGRPCPrefix: http2-
```

</p>
</details>

<details><summary>Servers Helm Values</summary>
<p>

```
USER-SUPPLIED VALUES:
mlserver:
  replicas: 1
triton:
  replicas: 1
```

</p>
</details>
