### ISSUE TITLE
"Failed to convert kfserving response so it could be chained to new input"

### ISSUE THREAD

**Issue by EvangMM** [SeldonIO/seldon-core#4620]
## Describe the bug
I deployed a Tensorflow model, saved (logged) with MLFlow on a Minio storage, in a Minikube installation.
When I send a request to endpoint "http://localhost:8004/seldon/<namespace\>/<sdep-name\>/v2/models/<model-name\>/infer",  I recieve back an error reposonse:
```json
{
  "status": {
    "code": 500,
    "info": "Failed to convert kfserving response so it could be chained to new input",
    "status": "FAILURE"
  }
}
```
The model recieve as input a numpy array of shape (n, 2, 979). I'm using python to handle the request:
```python
from seldon_core.seldon_client import SeldonClient
sc = SeldonClient(deployment_name="serving",
                  namespace="default",
                  gateway_endpoint="localhost:8004",
                  gateway="istio")
array = [
                [
                    [1..979],
                    [1..979]
                ]
]
r = sc.predict(data=array, transport="rest", http_path="/v2/models/serving/infer", payload_type="ndarray")
```

## To reproduce
I'm using a Seldon Deployment like that:
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: test
  namespace: default
spec:
  protocol: kfserving
  name: test
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://mlflow/1/<run-id>/artifacts/fl_model
        envSecretRefName: seldon-minio-secret
        name: seldon-serve
      name: default
      replicas: 1
```

## Expected behaviour
Recieve back an array of shape (n, 2, 979)

## Environment
minikube
docker.io/seldonio/seldon-core-executor:1.15.0 
docker.io/seldonio/seldon-core-operator:1.15.0

## Model Details

From istio-proxy log
```bash
[2023-01-25T11:38:15.918Z] "POST /seldon/default/serving/v2/models/serving/infer HTTP/1.1" 500 - via_upstream - "-" 224938 124 5 4 "172.17.0.3" "python-requests/2.28.1" "a784a210-82bf-9f64-9ecf-af4919ae5ca2" "localhost:8004" "172.17.0.15:8000" inbound|8000|| 127.0.0.6:46733 172.17.0.15:8000 172.17.0.3:0 outbound_.8000_.serving_.serving-serving.default.svc.cluster.local default
```
