### ISSUE TITLE
Can the HTTP service port be changed from '8000' after `engine.port` was deprecated?

### ISSUE THREAD

**Issue by kencieszykowski** [SeldonIO/seldon-core#4622]
A little background;

We are currently pushing upgrades for SeldonCore from 1.6 -> 1.14; and hit a little stumbling block when hitting 1.13.  We are deploying via Helm charts.

1.13 [deprecates all mentions](https://github.com/SeldonIO/seldon-core/tree/v1.13.0/helm-charts/seldon-core-operator#values) of the `engine` keys in the `Values`, as the engine has been fully moved over to the new Orchestrator.  The issue is that we had previously been setting the `engine.port` ( and the executor.port ) to different values than the default one.

Here is a resultant service on < 1.12:

```
...
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: [arbitrary-port-number]
    protocol: TCP
    targetPort: [arbitrary-port-number]
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 5001
...
```

After upgrading the Seldon CRD and core up to 1.13; the object above gets remade with the updated Core/CRD and the result is below:

```
...
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 5001
...
```

We are still setting the `executor.port` to [arbitrary-port-number], but due to the change in the service above we're hitting a port conflict when querying `localhost:8000` inside of the pod (we have an additional sidecar listening on 8000).

Not sure if this is now going to be set on the `SeldonDeployment` level, or (ideally) if we can set this as a global default in the Core spec as it is currently halting our progress.  Any advice would be much appreciated.  

Currently running Kubernetes v1.21.
Appreciate any and all comments.  Thank you!
