### ISSUE TITLE
Seldon-operator create wrong virtualService 

### ISSUE THREAD

**Issue by mkoshevoi** [SeldonIO/seldon-core#4627]
## Describe the bug

Seldon-operator create wrong virtualService
the virtualService only leads to the provodki-test-karpov-provodkiseldon (seldon-core-extractor container in pod) service on 8000, not to the provodki-test-karpov-provodkiseldon-provodki (model container in pod) service on 9000 port
```
NAME                                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
provodki-test-karpov-provodkiseldon            ClusterIP   172.30.223.220   <none>        8000/TCP,5001/TCP   70m
provodki-test-karpov-provodkiseldon-provodki   ClusterIP   172.30.74.18     <none>        9000/TCP,9500/TCP   70m
seldon-webhook-service                         ClusterIP   172.30.255.45    <none>        443/TCP             41d
```
virtualService
```
spec:
  gateways:
  - seldon-system/seldon-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /seldon/seldon-system/provodki-test-karpov/
    rewrite:
      uri: /
    route:
    - destination:
        host: provodki-test-karpov-provodkiseldon
        port:
          number: 8000
        subset: provodkiseldon
  - match:
    - headers:
        namespace:
          exact: seldon-system
        seldon:
          exact: provodki-test-karpov
      uri:
        regex: .*tensorflow.*|.*seldon.protos.*|.*inference.*
    route:
    - destination:
        host: provodki-test-karpov-provodkiseldon
        port:
          number: 5001
        subset: provodkiseldon

```

## To reproduce

We install helm chart seldon-core-operator in seldon-system namespace
```
istio:
  enabled: true
  gateway: seldon-system/seldon-gateway
  tlsMode: ""

```

then, my colleague followed the instructions  https://docs.seldon.io/projects/seldon-core/en/latest/python/python_wrapping_docker.html
and expose 9000 port for model in docker container

```FROM python:3.7-slim
WORKDIR /app

# Install python packages
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy source code
COPY . .

# Port for GRPC
EXPOSE 5000
# Port for REST
EXPOSE 9000

# Define environment variables
ENV MODEL_NAME MyModel
ENV SERVICE_TYPE MODEL

# Changing folder to default user
RUN chown -R 8888 /app

CMD exec seldon-core-microservice $MODEL_NAME --service-type $SERVICE_TYPE
```
than create sdep yaml
```
apiVersion: v1
items:
- apiVersion: machinelearning.seldon.io/v1
  kind: SeldonDeployment
  metadata:
    name: provodki-test-karpov
    namespace: seldon-system
  spec:
    annotations:
      prometheus.io/port: "6000"
      sidecar.istio.io/inject: "true"
    name: provodkiseldon
    predictors:
    - componentSpecs:
      - spec:
          containers:
          - env:
            - name: SELDON_LOG_LEVEL
              value: DEBUG
            image: harbor.rencredit.ru/nlp/provodki:seldon-test
            name: provodki
      graph:
        endpoint:
          service_host: localhost
          service_port: 9000
          type: REST
        name: provodki
      name: provodkiseldon
      replicas: 1

```
and simple gw
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: seldon-gateway
  namespace: seldon-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP

```

```

```

## Expected behaviour

seldon operator create virtualService like that

```
spec:
  gateways:
  - seldon-system/seldon-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /seldon/seldon-system/provodki-test-karpov/
    rewrite:
      uri: /
    route:
    - destination:
        host: provodki-test-karpov-provodkiseldon
        port:
          number: 9000

```

The virtualService that the operator creates is attached above in the description of the problem
in pod i see 3 containers
and all traffic routes to seldon-container-engine, but no to provodki 
```
istio-proxy             registry.redhat.io/openshift-service-mesh/proxyv2 rhel8@sha256:5ca0ef369e5a9c50fd78272adb58b391c5a6a8eabc918855e67bd8a6d32bd8c8 

provodki                harbor.rencredit.ru/nlp/provodki:seldon-test   

seldon-container-engine  harbor.rencredit.ru/nlp/seldonio/seldon-core-executor:1.15.0                              
```

I dont understand what going wrong

## Environment

Openshift 4.9.18  bare metall installation with OCP ServiceMesh 2.2.2 (Istio 1.12.7)

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]
