### ISSUE TITLE
404 not found in Seldon deployment logs

### ISSUE THREAD

**Issue by samuel-sujith** [SeldonIO/seldon-core#4692]
## Describe the bug
I am following the example model deployment of the sklearn iris classifier using the below deployment yaml

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-deployment-example
  namespace: nmlp
spec:
  name: sklearn-iris-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/sklearn-iris:0.3
          imagePullPolicy: IfNotPresent
          name: sklearn-iris-classifier
    graph:
      endpoint:
        type: REST
      name: sklearn-iris-classifier
      type: MODEL
    name: sklearn-iris-predictor
    replicas: 1
```

## Expected behaviour
No errors in the k8s logs

## Environment
K8s 

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
seldonio/sklearn-iris:0.3
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
2023-02-27 18:21:34,689 - seldon_core.microservice:main:463 - INFO:  REST gunicorn microservice running on port 9000
2023-02-27 18:21:34,689 - seldon_core.microservice:main:557 - INFO:  REST metrics microservice running on port 6000
2023-02-27 18:21:34,689 - seldon_core.microservice:main:567 - INFO:  Starting servers
2023-02-27 18:21:34,693 - seldon_core.microservice:rest_prediction_server:448 - INFO:  Gunicorn Config:  {'bind': '0.0.0.0:9000', 'accesslog': None, 'loglevel': 'info', 'timeout': 5000, 'threads': 1, 'workers': 1, 'max_requests': 0, 'max_requests_jitter': 0, 'post_worker_init': <function post_worker_init at 0x7fabe8027200>, 'worker_exit': functools.partial(<function worker_exit at 0x7fabe803ed40>, seldon_metrics=<seldon_core.metrics.SeldonMetrics object at 0x7fabe7dce710>), 'keepalive': 2}
2023-02-27 18:21:34,693 - seldon_core.microservice:grpc_prediction_server:520 - INFO:  GRPC Server Binding to '%s' 0.0.0.0:9500 with 1 processes
2023-02-27 18:21:34,696 - seldon_core.wrapper:_set_flask_app_configs:224 - INFO:  App Config:  <Config {'ENV': 'production', 'DEBUG': False, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(seconds=43200), 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': False, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093}>
2023-02-27 18:21:34,697 - seldon_core.microservice:_run_grpc_server:475 - INFO:  Starting new GRPC server with 1.
2023-02-27 18:21:34,697 - seldon_core.wrapper:_set_flask_app_configs:224 - INFO:  App Config:  <Config {'ENV': 'production', 'DEBUG': False, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(seconds=43200), 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': False, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093}>
[2023-02-27 18:21:34 +0000] [92] [INFO] Starting gunicorn 20.1.0
[2023-02-27 18:21:34 +0000] [92] [INFO] Listening at: http://0.0.0.0:6000 (92)
[2023-02-27 18:21:34 +0000] [92] [INFO] Using worker: sync
[2023-02-27 18:21:34 +0000] [103] [INFO] Booting worker with pid: 103
[2023-02-27 18:21:34 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-02-27 18:21:34 +0000] [7] [INFO] Listening at: http://0.0.0.0:9000 (7)
[2023-02-27 18:21:34 +0000] [7] [INFO] Using worker: sync
[2023-02-27 18:21:34 +0000] [104] [INFO] Booting worker with pid: 104
2023-02-27 18:21:34,749 - seldon_core.gunicorn_utils:load:103 - INFO:  Tracing not active
2023-02-27 18:21:45,237 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}
2023-02-27 18:22:00,236 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}
2023-02-27 18:22:00,267 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}
2023-02-27 18:22:15,236 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}
2023-02-27 18:22:26,161 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}

**Comment by samuel-sujith** [comment]
Upon adding debug, this is what I get.

Looks like metrics collect from /prometheus is broken

2023-02-27 18:38:03,226 - seldon_core.wrapper:Metrics:185 - DEBUG:  REST Metrics Request
2023-02-27 18:38:03,226 - seldon_core.metrics:collect:151 - DEBUG:  SeldonMetrics.collect called
2023-02-27 18:38:03,227 - seldon_core.metrics:collect:154 - DEBUG:  Read current metrics data from shared memory
2023-02-27 18:38:03,228 - werkzeug:_log:113 - INFO:  10.254.9.95 - - [27/Feb/2023 18:38:03] "GET /prometheus HTTP/1.1" 200 -
2023-02-27 18:38:08,740 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}
2023-02-27 18:38:08,741 - werkzeug:_log:113 - INFO:  10.254.9.95 - - [27/Feb/2023 18:38:08] "GET /prometheus HTTP/1.1" 500 -
2023-02-27 18:38:18,255 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}
2023-02-27 18:38:18,255 - werkzeug:_log:113 - INFO:  10.254.9.95 - - [27/Feb/2023 18:38:18] "GET /prometheus HTTP/1.1" 500 -

**Comment by RafalSkolasinski** [comment]
You have a Prometheus instance in the cluster trying to scrape wrong endpoints.  Try setting 
```
prometheus.io/scrape: "false"
```
annotation and see if the errors go away. We recommend to configure metrics using Prom Operator.

**Comment by RafalSkolasinski** [comment]
Try
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-deployment-example
  namespace: nmlp
spec:
  annotations:
    prometheus.io/scrape: "false"
  name: sklearn-iris-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
            - env:
              - name: SELDON_LOG_LEVEL
                value: DEBUG
              - name: SELDON_DEBUG
                value: 'True'
              - name: FLASK_DEBUG
                value: 'True'
              image: seldonio/sklearn-iris:0.3
              imagePullPolicy: IfNotPresent
              name: sklearn-iris-classifier
    graph:
      endpoint:
        type: REST
      name: sklearn-iris-classifier
      type: MODEL
    name: sklearn-iris-predictor
    replicas: 1
```

I do not think there is any helm value for it yet to set it globally
