### ISSUE TITLE
Running A/A Test: "engine not separate and no pu with localhost service - not clear where to inject engine"

### ISSUE THREAD

**Issue by rfalke** [SeldonIO/seldon-core#4710]
## Describe the bug

We want to do an A/A test with an existing setup. We just duplicate the predictor but the SeldonDeployment doesn't load and the controller manager spits out an error:
```
{
  "level": "error",
  "ts": 1678177057.4379308,
  "logger": "controller.seldon-controller-manager",
  "msg": "Reconciler error",
  "reconciler group": "machinelearning.seldon.io",
  "reconciler kind": "SeldonDeployment",
  "name": "XXX",
  "namespace": "seldon-serving",
  "error": "engine not separate and no pu with localhost service - not clear where to inject engine",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"
}
```

Note: if  seldon.io/engine-separate-pod is switched to "true"  (below) it works.

## To reproduce

`kubectl apply -f example.yaml`

example.yaml:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-for-testing
  labels:
    'istio-injection': 'enabled'
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: testing-separate-engine
  namespace: ns-for-testing
spec:
  annotations:
    seldon.io/engine-separate-pod: "false"
  predictors:
  - componentSpecs:
    - spec:
        containers:
          - image: seldonio/mock_classifier:1.9.0-dev
            name: query
    graph:
      name: query
    name: baseline
    replicas: 1
    traffic: 70
  - componentSpecs:
    - spec:
        containers:
          - image: seldonio/mock_classifier:1.9.0-dev
            name: query
    graph:
      name: query
    name: variant
    replicas: 1
    traffic: 30
  protocol: v2
```

## Expected behaviour

The same behaviour as with  seldon.io/engine-separate-pod = true but without the extra pod.

## Environment

* Cloud Provider: GKE
* Kubernetes Cluster Version: `Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9-gke.3200", GitCommit:"92ea556d4e7418d0e7b5db1ee576a73f8fc47e91", GitTreeState:"clean", BuildDate:"2023-01-20T09:29:29Z", GoVersion:"go1.18.9b7", Compiler:"gc", Platform:"linux/amd64"}`
* Deployed Seldon System Images: `value: docker.io/seldonio/seldon-core-executor:1.15.0 image: docker.io/seldonio/seldon-core-operator:1.15.0`
