### ISSUE TITLE
Pod Security Context is ignored

### ISSUE THREAD

**Issue by shaahmed115** [SeldonIO/seldon-core#4711]
<!-- Welcome and thank you for helping us make Seldon Core better!

## Describe the bug

I am applying a Pod Level Security Context to a SeldonDeployment using some custom Docker images. But I am facing this issue for this as well:

https://github.com/SeldonIO/seldon-core/blob/master/examples/graph_examples/combiner.yaml

## To reproduce

Modify the[ Seldon Deployment ](https://github.com/SeldonIO/seldon-core/blob/master/examples/graph_examples/combiner.yaml) and add a pod level security Context such as:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: test
  namespace:  NS_NAME
spec:
  name: test
  predictors:
  - componentSpecs:
    - spec:
        securityContext:
          runAsUser: USER_ID_OTHER_THAN_8888
```

## Expected behaviour

The Security Context should be applied to all the containers in the K8s pod

## Environment

Openshift version:  4.10.47 (K8s: 1.24)
Am also able to reproduce it in an EKS cluster (1.21)
