### ISSUE TITLE
Defining custom Ambassador mapping raises error in Ambassador

### ISSUE THREAD

**Issue by franco-bocci** [SeldonIO/seldon-core#4759]
## Describe the bug
When defining a SeldonDeployment with multiple predictors, and defining a custom ambassador config through the `seldon.io/ambassador-config` annotation:
- the defined mapping works okay
- the complete mapping is defined in the annotations for every pod, causing redundant mapping errors in ambassador

K8s Manifest being used (image and model path are fake):
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: single-model
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: single-model-common
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    seldon.io/engine-separate-pod: "true"
spec:
  name: single-model-common
  protocol: v2
  annotations:
    seldon.io/ambassador-config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: single-model-common-a_rest_mapping
      namespace: analytics
      prefix: /seldon/analytics/single-model-common/
      service: single-model-common-a.analytics:8000
      rewrite: /
      headers:
        version: a
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: single-model-common-b_rest_mapping
      namespace: analytics
      prefix: /seldon/analytics/single-model-common/
      service: single-model-common-b.analytics:8000
      rewrite: /
      headers:
        version: b

  predictors:
    - name: a
      traffic: 50

      graph:
        logger:
          mode: all
        children: []
        name: model
        type: MODEL

      componentSpecs:
        - spec:

            serviceAccountName: single-model

            volumes:
              - name: model-volume
                emptyDir: {}

            initContainers:
              - name: model-downloader
                image: seldonio/rclone-storage-initializer:1.16.0-dev
                imagePullPolicy: IfNotPresent
                args:
                  - "s3://bucket/prefix"
                  - "/mnt/models"
                volumeMounts:
                  - mountPath: /mnt/models
                    name: model-volume
                envFrom:
                  - secretRef:
                      name: seldon-rclone-secret

            containers:
              - name: model
                image: docker-image
                resources:
                  requests:
                    memory: 1Gi
                    cpu: 1
                  limits:
                    memory: 1Gi
                    cpu: 1
                volumeMounts:
                  - mountPath: /mnt/models
                    name: model-volume
                    readOnly: true

          hpaSpec:
            minReplicas: 2
            maxReplicas: 2
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 50
                type: Resource
              - resource:
                  name: memory
                  targetAverageUtilization: 50
                type: Resource

    - name: b
      traffic: 50

      graph:
        logger:
          mode: all
        children: []
        name: model
        type: MODEL

      componentSpecs:
        - spec:

            serviceAccountName: single-model

            volumes:
              - name: model-volume
                emptyDir: {}

            initContainers:
              - name: model-downloader
                image: seldonio/rclone-storage-initializer:1.16.0-dev
                imagePullPolicy: IfNotPresent
                args:
                  - "s3://bucket/prefix"
                  - "/mnt/models"
                volumeMounts:
                  - mountPath: /mnt/models
                    name: model-volume
                envFrom:
                  - secretRef:
                      name: seldon-rclone-secret

            containers:
              - name: model
                image: docker-image
                resources:
                  requests:
                    memory: 1Gi
                    cpu: 1
                  limits:
                    memory: 1Gi
                    cpu: 1
                volumeMounts:
                  - mountPath: /mnt/models
                    name: model-volume
                    readOnly: true

          hpaSpec:
            minReplicas: 2
            maxReplicas: 2
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 50
                type: Resource
              - resource:
                  name: memory
                  targetAverageUtilization: 50
                type: Resource
```
![image](https://user-images.githubusercontent.com/121866694/227590795-f9dbed89-2cf4-4e83-bb4f-925d2736e64a.png)

## Expected behaviour
There should be way of defining these mapping for each predictor so the mapping is not repeated.

## Environment
Ambassador version: 1.14
