### ISSUE TITLE
model autoscaling not working

### ISSUE THREAD

**Issue by Maksim-Siniugin** [SeldonIO/seldon-core#4861]
## Describe the bug

if model autoscaling triggered, i have error message:
level=debug msg="Could not scale model jcfogve:1, type: 0" error="failed to schedule model jcfogve. []" func=ModelScalingTrigger source=AgentServer"

## To reproduce
1. Create sample server like this
```
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: jcfogve-server
  namespace: seldon-mesh
spec:
  podSpec:
    containers:
    - name: mlserver
      resources:
        limits:
          cpu: 2000m
          memory: 4096Mi
        requests:
          cpu: 2000m
          memory: 4096Mi
  replicas: 1
  serverConfig: mlserver
```
2. Create sample model that be scheduled on this server like this:
```
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: jcfogve
  namespace: seldon-mesh
spec:
  storageUri: s3://path/to/model
  requirements:
  - mlflow
  server: jcfogve-server
  minReplicas: 1
  maxReplicas: 4
```
3. simulate load with requests to /v2/models/iris/infer
4. see triggered scaling and error on scheduller logs:
```
time="2023-05-23T14:20:22Z" level=debug msg="Received scaling event 0 from server jcfogve-server:0 for model jcfogve:1" func=ModelScalingTrigger source=AgentServer
time="2023-05-23T14:20:22Z" level=debug msg="Model jcfogve deployment spec differs - updating latest model version with new spec" func=UpdateModel source=MemoryStore
time="2023-05-23T14:20:22Z" level=debug msg="Schedule model jcfogve" Name=SimpleScheduler func=scheduleToServer
time="2023-05-23T14:20:22Z" level=debug msg="Model jcfogve candidate servers [jcfogve-server]" Name=SimpleScheduler func=scheduleToServer
time="2023-05-23T14:20:22Z" level=debug msg="Received event on model.event from memory.status.scheduling.failed (ID: 6, TxID: 5)" func=handleModelEventMessage source=pipelineStore
time="2023-05-23T14:20:22Z" level=debug msg="Received event on model.event from memory.status.scheduling.failed (ID: 6, TxID: 5)" func=handleModelEventMessage source=experimentServer
time="2023-05-23T14:20:22Z" level=debug msg="Received event on model.event from memory.status.scheduling.failed (ID: 6, TxID: 5)" func=handleModelEventMessage source=EnvoyServer
time="2023-05-23T14:20:22Z" level=debug msg="Received event on model.event from memory.status.scheduling.failed (ID: 6, TxID: 5)" func=handleModelEventMessage source=AgentServer
time="2023-05-23T14:20:22Z" level=debug msg="Received event on model.event from memory.status.scheduling.failed (ID: 6, TxID: 5)" func=handleModelEventMessage source=SchedulerServer
time="2023-05-23T14:20:22Z" level=debug msg="Received event on model.event from memory.status.scheduling.failed (ID: 6, TxID: 5)" func=handleModelEventMessage source=SchedulerServer
time="2023-05-23T14:20:22Z" level=info msg="Received event jcfogve:1" func=handleModelEvents source=pipelineStore
time="2023-05-23T14:20:22Z" level=debug msg="Could not scale model jcfogve:1, type: 0" error="failed to schedule model jcfogve. []" func=ModelScalingTrigger source=AgentServer
```
5. see error in model status:
```
Status:
  Conditions:
    Last Transition Time:  2023-05-23T18:05:58Z
    Reason:                failed to schedule model jcfogve. []
    Status:                False
    Type:                  ModelReady
    Last Transition Time:  2023-05-23T18:05:58Z
    Reason:                failed to schedule model jcfogve. []
    Status:                False
    Type:                  Ready
  Replicas:                2
Events:
  Type     Reason         Age   From              Message
  ----     ------         ----  ----              -------
  Normal   ModelReady     16m   scheduler-client  Model [jcfogve] is Ready
  Warning  ModelNotReady  54s   scheduler-client  Model [jcfogve] is no longer Ready
```

## Expected behaviour
2 replicas of model jcfogve must be scheduled on mlserver named jcfogve-server

## Environment
* Cloud Provider: AWS EKS
* Kubernetes Cluster Version: v1.26.4-eks-0a21954
* Deployed Seldon System Images:
  - docker.io/seldonio/seldonv2-controller:2.4.0
  - docker.io/seldonio/seldon-dataflow-engine:2.4.0
  - docker.io/seldonio/seldon-envoy:2.4.0
  - docker.io/seldonio/seldon-hodometer:2.4.0
  - docker.io/seldonio/seldon-modelgateway:2.4.0
  - docker.io/seldonio/seldon-pipelinegateway:2.4.0
  - docker.io/seldonio/seldon-scheduler:2.4.0
also try docker.io/seldonio/seldon-scheduler:2.5.0 with no changes
