### ISSUE TITLE
Use of protobuffers for resource parsing cause inconsistencies

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#489]
There are examples where using the official Kubernetes protobuffers to parse the incomming Seldon Deployment resource causes issues as the protobuffers to not match exactly what `kubectl` allows. One example: 

The need to use verbose `localObjectReference` for `envFrom`

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - name: classifier
                image: seldonio/mock_classifier:1.0
                envFrom:
                  - configMapRef:
                      localObjectReference:
                        name: ttng-classifier-config
      graph:
        children: []
        endpoint:
          type: REST
        name: classifier
        type: MODEL
      name: example
      replicas: 1
```
