### ISSUE TITLE
Duplicate ports defined in seldon-container-engine container

### ISSUE THREAD

**Issue by mts-dyt** [SeldonIO/seldon-core#4890]
## Describe the bug

port 8000 is defined twice in the seldon-container-engine spec, as in the following example:
```
      name: seldon-container-engine
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8000
          name: metrics
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
```

This is no more compatible with Kubernetes > 1.26
see issue: https://github.com/kubernetes/kubernetes/issues/118261

## To reproduce
1. Create a Kubernetes cluster > 1.26
2. Deploy a model
3. Delete the pod model
4. The pod get never deleted and stuck into Terminating state

## Expected behaviour
We should be able to customize metrics port on deployed models (not only portName)

## Environment

Kubernetes 1.26.3
Seldon 1.16.0
