### ISSUE TITLE
Seldon core 1.16.0 HPA fails to reconcile and keeps trying infinitely 

### ISSUE THREAD

**Issue by adarshkp23** [SeldonIO/seldon-core#4922]
## Describe the bug
While using Seldon core v1 **1.16.0** version, I noticed that whenever I update the seldonDeployment resource with HPA enabled, reconcile fails and the manager keeps trying continuously. This also results in huge amount of logs and manager being busy.

## To reproduce

- setup controller using https://github.com/SeldonIO/seldon-core/blob/f9d39508c1957c7aacd09b0a46e73e7171dcbee4/notebooks/seldon_core_setup.ipynb. 
- Use kubernetes version  1.26.0 and deploy using istio
- Use the below mentioned seldon deployment and apply it.

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-deployment-example
spec:
  name: sklearn-iris-deployment
  predictors:
  - componentSpecs:
    - hpaSpec:
        maxReplicas: 3
        metrics:
        - resource:
            name: cpu
            targetAverageUtilization: 40
          type: Resource
        minReplicas: 1
      spec:
        containers:
        - image: seldonio/sklearn-iris:0.3
          imagePullPolicy: IfNotPresent
          name: sklearn-iris-classifier
    graph:
      children: []
      endpoint:
        type: REST
      name: sklearn-iris-classifier
      type: MODEL
    name: sklearn-iris-predictor
    replicas: 1
```

- Once this is deployed, just update the resource using:
```kubectl edit sdep```

- change maxReplicas to 4 from 3 or change targetAverageUtilization to 60% and save it. 
- Once sdep is redeployed, check seldon manager logs and you should see these logs and this never stops

<img width="1349" alt="Screenshot 2023-06-14 at 4 02 50 PM" src="https://github.com/SeldonIO/seldon-core/assets/132311616/410bb504-6a59-4e5c-87cf-f61d753bb354">

## Environment

* Cloud Provider:  Minikube
* Kubernetes Cluster Version: 1.26.0

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]
