### ISSUE TITLE
Seldon V2 - Agent fails to download model from cloud storage

### ISSUE THREAD

**Issue by Kolajik** [SeldonIO/seldon-core#4947]
## Describe the bug
This issue is regarding [thread by Chorong. K in Seldon Community Slack](https://seldondev.slack.com/archives/C03DQFTFXMX/p1686495143193769). I am currently unable to make a configuration (secret + model) that works and downloads the model from cloud storage (AWS S3 in my case).

I am 100% sure this configuration has worked with Seldon V2 sometime in the early April 2023.

## To reproduce
1. Install Seldon V2 as per [helm k8s configuration in docs](https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/kubernetes-installation/helm.html)
   * Deploy the Seldon V2 runtime environment **without** dataflow and pipelinegateway
   * `helm install seldon-v2-runtime ../seldon-core/k8s/helm-charts/seldon-core-v2-runtime/ --namespace=${SELDON_NS_CORE} --set pipelinegateway.disable=true --set dataflow.disable=true`
2. Deploy custom mlserver image (definition down below)
3. Deploy your secret with AWS S3 configuration (definition down below)
4. Deploy model with `storageUri` defined as path to s3 folder (definition down below)
5. Delete the deployed model to unload it from server
6. Deploy model with `storageUri` defined as <secret_name>://<path_to_model_in_s3> (definition down below)

## Expected behaviour
Model is downloaded from AWS S3 cloud storage and loaded onto the custom mlserver.

## Actual behaviour
If I deploy the model with `storageUri` as defined in step 4, `agent` container gives me log output:
```
agent time="2023-06-27T15:37:07Z" level=debug msg="running with model <custom-model>_1:1 srcUri s3://path/to/model" Name=V2ModelRepository func=DownloadModelVersion                                                                                                                                                                                                                                     
agent time="2023-06-27T15:37:07Z" level=error msg="Failed to handle load model <custom-model>:1" Name=Client error="name from URI (s3) does not match secret (aws-s3-models-secret); are you using the right storage config?"
```
 * _**❗️ After this error I have noticed agent is looking for the secret not from `secretName` value, but from `storageUri` in Model definition file**_ - you can actually see this also in the Slack thread and the output Chorong. K has given:
   ```
   name from URI (https) does not match secret (azureml); are you using the right storage config?
   ```

If I deploy the model with `storageUri` as defined in step 6, `agent` container gives me log output:
```
agent time="2023-06-27T15:48:23Z" level=debug msg="running with model <custom-model>_1:1 srcUri aws-s3-models-secret://path/to/model" Name=V2ModelRepository func=DownloadModelVersion                                                                                                                                                                                                                   
agent time="2023-06-27T15:48:23Z" level=info msg="Copy from :s3,region=eu-west-1,location_constraint=eu-west-1,provider=AWS,env_auth=false,access_key_id=<my_access_key_id>,secret_access_key=<my_secret_access_key>://path/to/model (original aws-s3-models-secret://path/to/model) to /mnt/agent/rclone/4202258250" Source=RCloneClient                                                                                                                                                                                                            
agent time="2023-06-27T15:48:23Z" level=error msg="Failed to handle load model <custom-model>:1" Name=Client error="Failed to download from aws-s3-models-secret://path/to/model any files"
```
 * notice that the `agent` container outputs the whole secret to log

## Environment
 * Cloud Provider: AWS
 * Kubernetes Cluster Version: v1.21.14

## Server/Secret/Model Details
#### Server definition
```
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver-custom
spec:
  serverConfig: mlserver
  replicas: 1
  podSpec:
    containers:
    - image: <private_image_from_our_ECR>
      name: mlserver
      resources:
        limits:
          cpu: 1
          memory: 3Gi
        requests:
          cpu: 1
          memory: 3Gi
```
#### Secret definition
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-models-secret
type: Opaque
stringData:
  s3: |
    type: s3
    name: aws-s3-models-secret
    parameters:
      provider: AWS
      env_auth: false
      access_key_id: <my_access_key_id>
      secret_access_key: <my_secret_access_key>
      region: eu-west-1
      location_constraint: eu-west-1
```
#### Model definition from step 4
```
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: custom-model
spec:
  storageUri: "s3://path/to/model"
  secretName: "aws-s3-models-secret"
  requirements:
  - mlflow
  - python
```
#### Model definition from step 6
```
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: custom-model
spec:
  storageUri: "aws-s3-models-secret://path/to/model"
  secretName: "aws-s3-models-secret"
  requirements:
  - mlflow
  - python
```

**Comment by cliveseldon** [comment]
The issue is the config.name needs to match the uri name. This is the code:
https://github.com/SeldonIO/seldon-core/blob/7a4c7549608b4b7931aa0a01a42003408c4b5217/scheduler/pkg/agent/rclone/rclone.go#L232-L247
This is the PR that made it more strict: https://github.com/SeldonIO/seldon-core/pull/4780

**Comment by Kolajik** [comment]
@cliveseldon It still does not work. If I understood it correctly, you say that I should match the Secret's data (which is an rclone config) parameter `name` to match the beginning of `storageUri` in Model object, like so:

#### secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
 name: aws-s3-models-secret
type: Opaque
stringData:
 s3: |
   type: s3
   name: s3
   parameters:
     provider: AWS
     env_auth: false
     access_key_id: ...
     secret_access_key: ...
     region: eu-west-1
     location_constraint: eu-west-1
```

#### custom-model.yaml
```
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: custom-model
spec:
  storageUri: "s3://path/to/my/model"
  secretName: "aws-s3-models-secret"
  requirements:
  - mlflow
  - python
```

Now this gives me the same error as I said in the original description from **step 6** (outputs an error and the raw config into log). I really don't understand which values should I provide and to which variables. It was clear to me how it was before the PR #4780.

**Comment by Kolajik** [comment]
Oh... I am just dumb and haven't properly checked the S3 URI I use 🫠. I've been accessing folder which doesn't exist anymore. Sorry for that, my mistake.

As written in the comment above, it does work. Rclone config `name` property has to match the given `storageUri`:
#### secret.yaml
```
...
metadata:
 name: aws-s3-models-secret
...
stringData:
 s3: |
   type: s3
   name: s3
```
#### custom-model.yaml
```
...
  storageUri: "s3-custom-model:path/to/my/model"
  secretName: "aws-s3-models-secret"
```

I also **recommend not to give two backslashes to the storageUri** or name the rclone config it somewhat differently so that you aren't fooled that it is indeed an official S3 URI...
