### ISSUE TITLE
Simplify workflow for adding "capabilities" to a Server resource

### ISSUE THREAD

**Issue by andwilson** [SeldonIO/seldon-core#4968]
Currently, when a Server is defined, the user must define their custom image, an existing ServerConfig, and define the "extraCapabilities."  This works, and it appends the extraCapabilities onto the existing ones from the ServerConfig (as defined in the SELDON_SERVER_CAPABILITIES environment variable on the agent container).

This becomes problematic when someone builds a custom Server, as it may not necessarily contain all of the capabilities as defined in the ServerConfig.  Regular models (e.g. sklearn, xgboost, etc.) are then loaded on the the custom Server, which will fail to run them.

The best way to instead deploy a server is to manually define the SELDON_SERVER_CAPABILITIES on the agent when creating the Server resource, instead of using the "extraCapabilities."  Otherwise, a user would have to create a slight variation of the ServerConfig in order to deploy a Server without the excess capabilities.

Here is an example of a typical custom Server:

```
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver-cellpose
  namespace: seldon
spec:
  serverConfig: mlserver
#   extraCapabilities:
#     - cellpose
  podSpec:
    containers:
    - name: mlserver
      image: anddwilson/mlserver-cellpose:0.2
    - name: agent
      env:
      - name: SELDON_SERVER_CAPABILITIES
        value: "mlserver,cellpose"
```
