### ISSUE TITLE
Pipeline and Model fails when number of Server replicas is smaller than number of Model replicas

### ISSUE THREAD

**Issue by bobcchen** [SeldonIO/seldon-core#4970]
Starting with 2 Triton Server pods, and deploying the following example pipeline:

```
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: tfsimple1
spec:
  storageUri: "gs://seldon-models/triton/simple"
  requirements:
  - tensorflow
  memory: 100Ki
  replicas: 2
-----
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: tfsimple2
spec:
  storageUri: "gs://seldon-models/triton/simple"
  requirements:
  - tensorflow
  memory: 100Ki
  replicas: 2
-----
apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: tfsimples
spec:
  steps:
    - name: tfsimple1
    - name: tfsimple2
      inputs:
      - tfsimple1
      tensorMap:
        tfsimple1.outputs.OUTPUT0: INPUT0
        tfsimple1.outputs.OUTPUT1: INPUT1
  output:
    steps:
    - tfsimple2
```

Subsequently when the number of Triton Server pods is decreased to 1, either manually or automatically (using HPA), both models fail, become unready with the following error message. The pipeline fails as a result.
![image](https://github.com/SeldonIO/seldon-core/assets/47989178/1296a313-7a78-4cfd-8709-3bdc6f70e31d)

The scheduler attempts to server the tf model on mlserver pods which results in requirement issues.

When model scaling is configured `minReplicas: 1 maxReplicas: 2`, the pipeline recovers after long downtime after the Model is scaled down to have 1 replica.
