### ISSUE TITLE
Document how to configure service accounts to grant access to storage resources

### ISSUE THREAD

**Issue by edshee** [SeldonIO/seldon-core#4978]
Details in this thread:
https://seldondev.slack.com/archives/C03DQFTFXMX/p1688551276390389

In short, there is a need to document the steps required to set up using a service account to connect to a storage provider.

**Comment by Abhinavfreecodecamp** [comment]
@edshee I have gone through the thread but I feel this is more of cloud specific issue not much related to seldon correct me If I am wrong. For explanation (using GCP)  using Workload identity federation we can inject SA into any upcoming pods also configure policy for different  namespaces then if GCloud authentication is working properly all we need is k8s SA and role and rolebinding we can even have ClusterRole and ClusterRole bindings for different different use cases. For more standardised approach we can also have terraform.

**Comment by edshee** [comment]
@Abhinavfreecodecamp You make a good point, this is pretty cloud specific but it's also something I've seen asked multiple times so it makes sense to document it.

I think maybe the issue should've been broader to encompass "better documentation around configuring storage providers" since that was my aim.

**Comment by Abhinavfreecodecamp** [comment]
@edshee Thanks for responding, just a suggestion rather than building a documentation for configuring around storage providers, a generic way would be to document. 😅

- How to create SA 
- Using Workload Identity Federation
- Creating k8s SA [this would be straight forward]
- Creating custom role and rolebinding for access. [This might be little confusing as rbac is complex]

**Comment by edfincham** [comment]
So the issue I posted in that original thread was resolved. The issue ultimately was the version of `rclone` being shipped with Seldon V2 `2.1.0`. Bumping that to `2.5.0` worked for me, but I still needed to add a role binding for my custom service account:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seldon-sa-rolebinding
  namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-role
subjects:
- kind: ServiceAccount
  name: $SERVICE_ACCOUNT
  namespace: $NAMESPACE
```
