### ISSUE TITLE
Consistent naming of pipeline resource sections

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#5028]
## What
This issues is a proposal for updating the naming of sections in pipeline resources to be more consistent.

## Why
Lessen user confusion and increase ergonomics by using the same keywords in a pipeline resource for both internal and external (to the pipeline) data streams.

Currently almost all our docs regarding handling of inputs and triggers are specifically for pipeline-internal data streams rather than external. Trying to adapt these examples to pipeline-external data streams leads to errors as users (such as myself) assume that the names are consistent.

## Proposed changes
 - change `joinType` keyword to `inputsJoinType` for external pipeline inputs
 - change `triggersJoin` to `triggersJoinType` for external pipeline triggers
 - change `input` to `inputs` section name under `spec` for external inputs

## Impact
This is a breaking change, but the impact should be minimal. Specifically, this would only impact pipelines which take any kind of external input (from other pipelines). Using our current docs as a guide:

- no occurrences of `joinType` (i.e. no examples of joining on pipeline-external inputs)
- no occurrences of `triggersJoin`, however 2 "misleading" occurrences when reading pipeline status:
  -  [pipeline-examples](https://docs.seldon.io/projects/seldon-core/en/v2.6.0/contents/examples/pipeline-examples.html#trigger-joins) - although internal `triggersJoinType` is used, the pipeline status printout shows it as `triggerJoin`
  - [trigger-joins notebook - unpublished](https://github.com/SeldonIO/seldon-core/blob/v2/samples/trigger_joins.md) - same as above, only internal `triggersJoinType` is used but pipeline status shows it as `triggerJoin`
 - 12 occurences of `input:` demonstrating pipeline-to-pipeline inputs:
    - [11 occurences](https://docs.seldon.io/projects/seldon-core/en/v2.6.0/contents/examples/pipeline-to-pipeline.html)
    - [1 occurence cli-tests - unpublished](https://github.com/SeldonIO/seldon-core/blob/v2/samples/cli-tests.md)

### Additional discussion
In addition to the above, it would be worthwhile to review consistency of external and internal pipeline input specification. Currently this is done as follows:

```yaml
# internal inputs
apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  steps:
    - name: my-model-1
    - name: my-model-2
      inputs:
      - my-model-1.inputs.INPUT-TENSOR
      # truncated
```

```yaml
# external inputs
apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  input:
    externalInputs:
    - my-other-pipeline.inputs-INPUT-TENSOR
   steps:
   # truncated

```
The main difference between these (apart from the `inputs:` vs `input:` already discussed) is that the pipeline-external inputs definition requires 2 indentation levels since the section `input:` is a catch-all for everything that's external to the pipeline (and thus requires another section called `externalInputs`), whereas in the pipeline-internal example `inputs:` is singly indented as it only concerns itself about inputs (and not e.g. triggers, as those have a separate section). It may be worthwhile to consider consistency here too. For example, reworking the 2nd example to be consistent with pipeline-internal definitions might look like this (essentially removing one level of indentation):

```yaml
# external inputs - reworked consistently with internal inputs by removing a level of indentation
apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  inputs:
    - my-other-pipeline.inputs-INPUT-TENSOR
   steps:
   # truncated
