### ISSUE TITLE
Unimplemented error when making gRPC requests

### ISSUE THREAD

**Issue by edfincham** [SeldonIO/seldon-core#5049]
## Describe the bug
- I was previously able to make gRPC requests to models deployed on mlserver. I was using k6 to run load testing at production levels, but found that:
   - The envoy pod was performing zero load balancing
   - The target server would get OOM killed
- Following [this slack thread](https://seldondev.slack.com/archives/C03DQFTFXMX/p1689849502790239), I updated my helm charts to specify larger resource allocation for the envoy (I'm installing directly from the v2 branch). However, my gRPC requests subsequently returned `UNIMPLEMENTED` errors. I then pinned the docker tag to `2.6.0` (previously `latest`) which seemed to fix the issue, but it has since returned when I try to edit resource requests/limit on the envoy.
- This issue is occurring locally (with tritonclient and via the CLI) and on the EKS cluster (via k6)

## To reproduce
1. Install the helm charts direct from seldon-core repo (v2 branch, [commit](https://github.com/SeldonIO/seldon-core/commit/ea5f5d424ce8e95186530c8b116fcddd3ff34eac))
2. Use the values in this [gist](https://gist.github.com/edfincham/61061f48e982f4c202e9f34780e22e8c)
3. I am using a custom environment tarball loaded by an mlserver:

```yaml
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver-test
  namespace: seldon-v2
spec:
  serverConfig: mlserver
  replicas: 3
  podSpec:
    serviceAccountName: seldon-v2-sa
    containers:
    - name: mlserver
      env:
      - name: MLSERVER_PARALLEL_WORKERS
        value: "5"
      - name: SELDON_LOG_LEVEL
        value: DEBUG
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: test-model
  namespace: seldon-v2
spec:
  replicas: 3
  storageUri: "s3://artifact-storage-bucket/model_name/model_version"
  secretName: "seldon-rclone-secret"
  server: mlserver-test
```

## Tritonclient
- I'm using the following script to send a gRPC request to the server
- This uses the tritonclient library (2.35.0)
- Also involves port-forwarding to the seldon-mesh service: `kubectl port-forward svc/seldon-mesh -n seldon-v2 8080:80`
 ```python
import tritonclient.grpc as grpcclient
import numpy as np

 def run_grpc(host, port, model_name, data):
    grpc_triton_client = grpcclient.InferenceServerClient(
        url=f"{host}:{port}",
        verbose=False,
    )
    headers = {"seldon-model": model_name}
    inputs = [
        grpcclient.InferInput("X", data.shape, "UINT8"),
    ]
    inputs[0].set_data_from_numpy(data)
    result = grpc_triton_client.infer(model_name, inputs, headers=headers)
    grpc_triton_client.close()
    return result

res = run_grpc("localhost", 8080, "test-model", np.random.random((192, 156)).astype(np.uint8))
```

This results in:
- `tritonclient.utils.InferenceServerException: [StatusCode.UNIMPLEMENTED]` on the client
- `[2023-07-21T13:10:58.514Z] "POST /inference.GRPCInferenceService/ModelInfer HTTP/2" 200 NR 0 0 0 - "-" "grpc-python/1.56.0 grpc-c/33.0.0 (linux; chttp2)" "-" "localhost:8080" "-"` on the server (`/tmp/envoy-accesslog.txt` on the envoy pod)

## K6
- My k6 setup is defined in [this gist](https://gist.github.com/edfincham/4b7e33a2685e8350e74dae3be54937bb)
- I run this on a pod using the ` grafana/k6:latest` docker image
- When adding the `--http-debug="full"` flag to the standard `k6 run ...` command, I get the following headers and payloads, which look correct to me:
```txt
INFO[0001] Out Header:
Full Method: /inference.GRPCInferenceService/ModelInfer
Remote Address: 172.20.52.6:80
seldon-model: test-model
user-agent: grpc-go/1.55.0
  source=http-debug
INFO[0001] Out Payload:
Wire Length: 181
Sent Time: 2023-07-21 14:16:34.880307621 +0000 UTC m=+1.241949258
model_name: "test-model"
inputs: {
  name: "input__0"
  datatype: "FP32"
  shape: 2
  shape: 4
  shape: 4
  contents: {
    fp32_contents: 0.1
    ...
    fp32_contents: 0.1
  }
}

  source=http-debug
INFO[0001] In Trailer:
Wire Length: 57
server: envoy
content-type: application/grpc
date: Fri, 21 Jul 2023 14:16:34 GMT
```

## Seldon CLI
I've tried the CLI and have the following setup:
```
kubectl port-forward svc/seldon-mesh -n seldon-v2 8080:80
kubectl port-forward svc/seldon-scheduler -n seldon-v2 8081:9004
kubectl port-forward svc/seldon-kafka-brokers -n seldon-v2 8082:9093

export SELDON_INFER_HOST=localhost:8080
export SELDON_SCHEDULE_HOST=localhost:8081
export SELDON_KAFKA_BROKER=localhost:8082
```

The following command results in: `Error: rpc error: code = Unimplemented desc =`
```
./bin/seldon model infer test-model --inference-mode grpc '{"model_name":" test-model","inputs":[{"name":"input","contents":{"fp32_contents":[1,2,3,4,1,2,3,4]},"datatype":"FP32","shape":[2, 1,4]}]}'
```

The main issue here was the envoy not performing any load balancing for incoming requests. However, in the process of debugging that, I've ended up with a setup which does not handle _any_ requests.

## Environment
* Cloud Provider: AWS EKS
* Kubernetes Cluster Version: 1.21+
