### ISSUE TITLE
 requests and responses are logged double times in Combiner node

### ISSUE THREAD

**Issue by caozhuozi** [SeldonIO/seldon-core#5116]
We recently upgraded Seldon-core from 1.14 to 1,16. However we found some issues with payload logging.

## Describe the bug

This is our graph structure:
```
    graph:
      children:
      - endpoint:
          type: REST
        name: b
        type: MODEL
      - endpoint:
          type: REST
        name: c
        type: MODEL
      - endpoint:
          type: REST
        name: d
        type: MODEL
      - endpoint:
          type: REST
        name: e
        type: MODEL
      endpoint:
        type: REST
      logger:
        mode: all
        url: <URL>
      name: a
      type: COMBINER
    name: default
```

We have a combiner with 4 children. we only need to log the combiner(entry)'s requests and responses. 
However, requests and responses are logged double times in Combiner.

## To reproduce

If the seldon-core >= 1.16 and there is a combiner in the graph with logger enabled, the payloads of the combiner will be logged twice.

## Expected behaviour

each request and response should be only logged once in Combiner.
