### ISSUE TITLE
GCS `rclone` failed request

### ISSUE THREAD

**Issue by JulesBelveze** [SeldonIO/seldon-core#5139]
## Describe the bug

Hey all, I have been trying to deploy a custom model to my GKE using `mlserver` and Seldon Core V2. My GCS bucket isn't public so I have been following the tutorial [here](https://docs.seldon.io/projects/seldon-core/en/v2/contents/kubernetes/storage-secrets/index.html).
However, it seems like `rclone` is still not able to download the bucket as I hit the following issue:
```
Failed to sync/copy gcs://test/models/embedder/v0/ to /mnt/agent/rclone/1136191405 Failed rclone request to host:0.0.0.0 port:5572 path:/sync/copy
```

## To reproduce
<details>
<summary> 1. created the serviceaccout key using `gcloud` cli </summary>

```
gcloud iam service-accounts keys create \
  gcloud-application-credentials-rw.json \
  --iam-account cloud-storage-writer@MY_PROJECT.iam.gserviceaccount.com
```

</details>

<details>
<summary> 2.  applied the k8s secret </summary>

```
apiVersion: v1
kind: Secret
metadata:
  name: gcs-bucket
  namespace: seldon-mesh
type: Opaque
stringData:
  gcs: |
    type: gcs
    name: gcs
    parameters:
      service_account_credentials: '<gcloud-application-credentials-rw.json>'
```

</details>

<details>
<summary> 3. referenced the secret to my `Model` </summary>

```
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  labels:
    app: seldon
  name: interaction-embedder
  namespace: seldon-mesh
spec:
  server: mlserver
  storageUri: "gcs://test/models/embedder/v0/"
  secretName: "gcs-bucket"
```

</details>

I made sure that the bucket is in the same zone than the cluster and that the serviceaccount has read/write access to GCS.

## Environment

* Cloud Provider: GKE
* Kubernetes Cluster Version: 
```
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3-gke.100", GitCommit:"6466b51b762a5c49ae3fb6c2c7233ffe1c96e48c", GitTreeState:"clean", BuildDate:"2023-06-23T09:27:28Z", GoVersion:"go1.20.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
* Deployed Seldon System Images: 2.6.0
* pods running:
```
seldon-mesh   hodometer-6946f6d879-7jxlj                                       1/1     Running            0               13h
seldon-mesh   mlserver-0                                                       3/3     Running            0               13h
seldon-mesh   seldon-controller-manager-6785d56575-hm2tt                       1/1     Running            0               14h
seldon-mesh   seldon-dataflow-engine-77d8b64c54-fbvln                          0/1     CrashLoopBackOff   166 (88s ago)   13h
seldon-mesh   seldon-envoy-7957bfcd6d-mmqs7                                    1/1     Running            0               13h
seldon-mesh   seldon-modelgateway-7d8d78dbbf-qf7xh                             1/1     Running            0               13h
seldon-mesh   seldon-pipelinegateway-86458ff8b5-7xpzq                          1/1     Running            0               13h
seldon-mesh   seldon-scheduler-0                                               1/1     Running            0               13h
```

## Model Details

<details>
<summary> Model definition </summary>

```
import logging
from typing import List

import numpy as np
from mlserver import MLModel
from mlserver.codecs import decode_args
from sentence_transformers import SentenceTransformer


class InteractionEmbedder(MLModel):
    """Wrapper around SentenceTransformer object"""

    async def load(self) -> bool:
        logging.info("Logging model...")
        self.model = SentenceTransformer("myModel")
        return True

    @decode_args
    async def predict(self, docs: List[str]) -> np.ndarray:
        """"""
        embeddings = self.model.encode(docs)
        return embeddings
```

</summary>
