### ISSUE TITLE
Mlserver runtime metrics port is not exposed in pod

### ISSUE THREAD

**Issue by yaliqin** [SeldonIO/seldon-core#5166]
I deployed model with Mlserver runtime  and WITHOUT seldon-container-engine and defined the metrics port in sdep yaml as below. But after the pod is up, the metrics port definition is removed.

definition in sdep:
```    image: dockerhub.paypalcorp.com/aiplatform/mlserver:20231201.4191da0.huggingface_llm.dev
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 6000
            name: metrics
            protocol: TCP
          - containerPort: 9500
            name: grpc
            protocol: TCP
          - containerPort: 9000
            name: http
            protocol: TCP
```
no seldon container engine
```
  - annotations:
      seldon.io/no-engine: "true"
```
I also defined the ENV in the sdep as below:
```
          - name: MLSERVER_METRICS_PORT
            value: "6000"
          - name: MLSERVER_METRICS_ENDPOINT
            value: /promtheus
```

generated pod:
```
ports:
    - containerPort: 9500
      name: grpc
      protocol: TCP
    - containerPort: 9000
      name: http
      protocol: TCP
    readinessProbe:
```

With this, the podmonitor doesn't work. Pod monitoring definition
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-podmonitor
  namespace: seldon-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: seldon-core
  podMetricsEndpoints:
    - port: metrics
      path: /prometheus
  namespaceSelector:
    any: true
```
I can get the metrics if I manually create a pod with metrics port exposed.

I am wondering this behavior is introduced in this 
https://github.com/SeldonIO/seldon-core/blob/46ef14e60e1f8c5b4c30320b06293e8b60f721fa/operator/controllers/mlserver.go#L121
 
https://github.com/SeldonIO/seldon-core/blob/46ef14e60e1f8c5b4c30320b06293e8b60f721fa/operator/controllers/mlserver.go#L95
 
https://github.com/SeldonIO/seldon-core/blob/46ef14e60e1f8c5b4c30320b06293e8b60f721fa/operator/controllers/mlserver.go#L114

## To reproduce

deploy a model with
1, sdep with no engine
2, mlserver runtime

## Expected behaviour
The mlserver metrics port and metrics path can be exposed in the pod.
