### ISSUE TITLE
how to configure a nginx ingress on seldon-mesh service for grpc request

### ISSUE THREAD

**Issue by shuaiyy** [SeldonIO/seldon-core#5179]
my ingress is :
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: seldon-mesh
    app.kubernetes.io/name: seldon-mesh
  name: seldon-mesh
  namespace: seldon-mesh
spec:
  defaultBackend:
    service:
      name: seldon-mesh
      port:
        number: 80
  rules:
  - host: seldon-mesh.seldon-control-plane.orb.local
 ```

when send a grpc request , got: Error: rpc error: code = Unavailable desc = connection closed before server preface received
```
seldon model infer iris --inference-mode grpc  --inference-host seldon-mesh.seldon-control-plane.orb.local:80 \
  '{"model_name":"iris","inputs":[{"name":"input","contents":{"fp32_contents":[1,2,3,4]},"datatype":"FP32","shape":[1,4]}]}'
```
use port 443 got the same error.

it's ok to send a rest request:
```
seldon model infer iris --inference-host seldon-mesh.seldon-control-plane.orb.local \
  '{"inputs": [{"name": "predict", "shape": [1, 4], "datatype": "FP32", "data": [[1, 2, 3, 4]]}]}'
```
