### ISSUE TITLE
How to set type of K8s Service created by SeldonDeployment

### ISSUE THREAD

**Issue by tomaszstachera** [SeldonIO/seldon-core#5299]
## Describe the bug
I don't know how to change Service type created by SeldonDeployment.

## To reproduce
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: multi
  namespace: tomasz
spec:
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: pvc://ts-seldon-4-volume/triton/multi
      name: multi
      type: MODEL
      endpoint:
        type: NodePort
    componentSpecs:
    - spec:
        containers:
        - name: multi
        tolerations:
          - key: SystemResources
            value: reservedFor
            effect: NoSchedule
    explainer:
      endpoint:
        type: NodePort
    name: default
    replicas: 1
    labels:
      sidecar.istio.io/inject: "true"
  protocol: v2
```

## Expected behaviour
I would like to have NodePort service.
