### ISSUE TITLE
Seldon v1: seldon-controller-manager high availability settings in helm chart

### ISSUE THREAD

**Issue by nicodega** [SeldonIO/seldon-core#5564]
In our company we are using the seldon operator helmchart and realized there is no way to configure replica count, pdb or affinity for the deployment of the seldon-controller-manager. 

Given it's a kubebuilder operator capable of leader election wouldn't it be possible to make it parametrizable though the values section to get a HA deployment of the operator?

It would be great if under the manager section it could be configured as follows (or similar):

```yaml
manager:
  replicas: 2
  affinity: {}
  pdb:
    enabled: true
    minAvailable: 1  
```
