### ISSUE TITLE
OOMKilled when starting an operator

### ISSUE THREAD

**Issue by sujaymansingh** [SeldonIO/seldon-core#579]
I’ve tried installing seldon to a k8s cluster. I ran (as per the docs)
- `helm install seldon-core-operator --name seldon-core-sujay --repo https://storage.googleapis.com/seldon-charts --set usage_metrics.enabled=true --namespace sujay` to install the core operator
- `helm install stable/ambassador --name ambassador-sujay --namespace sujay --set image.tag=0.40.2`

Then I deployed the sample seldon chart at https://docs.seldon.io/projects/seldon-core/en/latest/graph/inference-graph.html

I have a seldon deployment:

```
$ kubectl get sdep
NAME           AGE
seldon-model   20m
```

The operator kept being killed by the cluster however.

```
$ kubectl get pods --namespace sujay seldon-operator-controller-manager-0
seldon-operator-controller-manager-0           0/1     OOMKilled          1          59s
```

The memory limits come from the helm chart itself.

```
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
```

Either more memory needs to be assigned, or the operator needs to be changed so that there is no chance of it taking up that much memory.
