### ISSUE TITLE
Unable to inject custom parameter in Python model

### ISSUE THREAD

**Issue by cbreuel** [SeldonIO/seldon-core#584]
I'm trying to inject a custom parameter into my Python model class. It looks like Seldon is picking up the custom parameter I configured, but the container is throwing an exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/seldon-core-microservice", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 302, in main
    user_object = user_class(**parameters)
TypeError: __init__() got an unexpected keyword argument 'pkl_path'`
```

I have added `pkl_path` (the name of my custom parameter) to my class' `__init__` method, but I get the same error. This is the class declaration right now:

```
class PredictAPI(object):
  def __init__(self, pkl_path=None):
    print("pkl_path={}", pkl_path)
```

I'm building the image with s2i, with this command:

```
s2i build $MODEL seldonio/seldon-core-s2i-python3:0.5 ${IMAGE}
```

Here is the s2i config:

```
MODEL_NAME=PredictAPI
API_TYPE=REST
SERVICE_TYPE=MODEL
PERSISTENCE=0
```

And this is how I'm declaring the parameter:

```
     graph:
       children: []
       endpoint:
         type: REST
       name: classifier
       type: MODEL
       parameters:
       - type: STRING
         name: pkl_path
         value: fake.pkl
```
