### ISSUE TITLE
argo workflow not detecting seldon deployment is available

### ISSUE THREAD

**Issue by mbron** [SeldonIO/seldon-core#668]
Hi, we're having an issue with our argo workflow sometimes not detecting the 'status.state' == 'Available' condition in the seldon deployment resource definition. We're using version v0.2.7.

Below an abbreviate argo workflow definition, note the `successCondition: status.state == Available` condition.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  templates:
    dag:
      tasks:
      - name: deploy-model
        template: deploy-model

  - name: deploy-model
    resource:
      action: apply
      successCondition: status.state == Available
      manifest: |
        apiVersion: machinelearning.seldon.io/v1alpha2
        kind: SeldonDeployment
        metadata:
          labels:
            app: seldon
```

So when the workflow successfully detects that the deployment is available the workflow logs contain the following json (snipped):

```
"{
  \"apiVersion\": \"machinelearning.seldon.io/v1alpha2\",
  \"kind\": \"SeldonDeployment\",
  \"metadata\": {
    \"annotations\": {
      \"kubectl.kubernetes.io/last-applied-configuration\": \"{\\\"apiVersion\\\":\\\"machinelearning.seldon.io/v1alpha2\\\",\\\"kind\\\":\\\"SeldonDeployment\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"labels\\\":{\\\"app\\\":\\\"seldon\\\"}, ... }\\n\"},
      \"creationTimestamp\": \"2019-07-01T10:44:59Z\",
      \"generation\": 1,
      \"labels\": {\"app\": \"seldon\"},
      \"name\": \"seldon-prediction-service\",
      \"resourceVersion\": \"15667665\",
      \"spec\": {
        \"predictors\": [...]
},

\"status\": {\"predictorStatus\": [{\"replicas\": 1,\"replicasAvailable\": 1}],\"state\": \"Available\"}}"
```

Note the last line, on the outer level of the resource description json, there is a `"status"` key which contains the `state` with value `available`.

Now let's look at the argo log output when the workflow does not detect that the deployment is available (snipped): 

```
"{
  \"apiVersion\": \"machinelearning.seldon.io/v1alpha2\",
  \"kind\": \"SeldonDeployment\",
  \"metadata\": {
    \"annotations\": {
    
      \"kubectl.kubernetes.io/last-applied-configuration\": \"{\\\"apiVersion\\\":\\\"machinelearning.seldon.io/v1alpha2\\\",\\\"kind\\\":\\\"SeldonDeployment\\\",\\\"metadata\\\":{\\\"name\\\":\\\"seldon-prediction-service\\\",\\\"generation\\\":2,\\\"creationTimestamp\\\":\\\"2019-06-29T17:32:40Z\\\",\\\"labels\\\":{\\\"app\\\":\\\"seldon\\\"}},\\\"spec\\\":{\\\"predictors\\\":[{\\\"graph\\\":{\\\"type\\\":\\\"MODEL\\\",\\\"endpoint\\\":{\\\"type\\\":\\\"REST\\\"}},\\\"componentSpecs\\\":[{\\\"spec\\\":{...}}],\\\"containers\\\":[{\\\"resources\\\":{\\\"requests\\\":{\\\"memory\\\":\\\"1Mi\\\"}},\\\"imagePullPolicy\\\":\\\"Always\\\"}],\\\"terminationGracePeriodSeconds\\\":20}}],\\\"replicas\\\":1,\\\"annotations\\\":{\\\"predictor_version\\\":\\\"0.0.1\\\"}}],\\\"annotations\\\":{\\\"deployment_version\\\":\\\"0.1\\\"}},\\\"status\\\":{\\\"state\\\":\\\"Available\\\",\\\"predictorStatus\\\":[{\\\"replicas\\\":1,\\\"replicasAvailable\\\":1}]}}\\n\"},
      
    \"creationTimestamp\": \"2019-06-29T17:32:40Z\",
    \"generation\": 2,
    \"labels\": {\"app\": \"seldon\"},
    \"name\": \"seldon-prediction-service\",
    \"resourceVersion\": \"15382733\",
    \"uid\": \"e4e3c2db-9a93-11e9-bfff-6c0b8465aea7\"},
  \"spec\": {\"predictors\": [...]}
}"
```

Note that the `{"status": {"state": "Available"}}` condition is actually in the description, however, it is no longer at the outer level, but part of the value of the `"kubectl.kubernetes.io/last-applied-configuration"` key, which is actually a string (not json)

So the question is why does the condition appear in different places some of the time.
