### ISSUE TITLE
Injecting S3 Credentials into tfserving Container

### ISSUE THREAD

**Issue by devstein** [SeldonIO/seldon-core#749]
Given the `SeldonDeployment` below, I want to inject AWS credentials in the `tfserving` container. Is there a way to do this?

```yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: test
spec:
  name: test
  predictors:
    - graph:
        children: []
        implementation: TENSORFLOW_SERVER
        modelUri: s3://bucket/path/to/model
        name: test
        parameters:
          - name: signature_name
            type: STRING
            value: predict
          - name: model_name
            type: STRING
            value: model
      name: default
      replicas: 1

```

**Comment by cliveseldon** [comment]
The solution is discussed in #748 @ryandawsonuk can expand on where we are with it.

**Comment by ryandawsonuk** [comment]
In the latest snapshot version the code is now in place for a SeldonDeployment to work like https://github.com/kubeflow/kfserving/tree/9b14e08038405348ac21f1acbbf8b26e4c26631d/docs/samples/s3

So you'd create the Secret and ServiceAccount like in that example and in the SeldonDeployment specify a serviceAccountName alsongside the modelUri like:

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: test
spec:
  name: test
  predictors:
    - graph:
        children: []
        implementation: TENSORFLOW_SERVER
        modelUri: s3://bucket/path/to/model
        serviceAccountName: NAMEOFSERVICEACCOUNT
        name: test
        parameters:
          - name: signature_name
            type: STRING
            value: predict
          - name: model_name
            type: STRING
            value: model
      name: default
      replicas: 1
```
I've checked that secrets do get applied to the pod like this. I haven't fully checked that a model is downloaded from a private bucket, though as far as I can see it should work. @devstein if you'd like to try it on the latest snapshot version it would certainly be appreciated.
