### ISSUE TITLE
initContainer resources required for some clusters

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#776]
I've applied this:
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: xgboost
  namespace: seldon-core
spec:
  name: xgboost
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - name: feature-transformer
                image: seldonio/clean_text_transformer:0.1
                env:
                  - name: TRACING
                    value: "1"
                  - name: JAEGER_CONFIG_PATH
                    value: /etc/tracing/config/tracing.yml
                  - name: OMP_NUM_THREADS
                    value: "6"
                resources:
                  limits:
                    cpu: 8
                    memory: 4Gi
                  requests:
                    cpu: 1
                    memory: 256Mi
                volumeMounts:
                  - mountPath: /etc/tracing/config
                    name: tracing-config
              - name: model
                env:
                  - name: OMP_NUM_THREADS
                    value: "6"
                envFrom:
                  - secretRef:
                      name: s3-secret
                resources:
                  limits:
                    cpu: 8
                    memory: 4Gi
                  requests:
                    cpu: 1
                    memory: 256Mi
                volumeMounts:
                  - mountPath: /etc/tracing/config
                    name: tracing-config
            volumes:
              - name: tracing-config
                configMap:
                  name: tracing-config
                  items:
                    - key: tracing.yml
                      path: tracing.yml
      svcOrchSpec:
        env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
          - name: TRACING
            value: "1"
          - name: JAEGER_SERVICE_NAME
            value: xgboost
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent.seldon-core.svc
          - name: JAEGER_AGENT_PORT
            value: "6831"
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_PROPAGATION
            value: "B3"
          - name: JAEGER_TAGS
            value: "deployment=xgboost"
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 512Mi
      graph:
        children:
          - children: []
            implementation: XGBOOST_SERVER
            name: model
            modelUri: gs://seldon-models/xgboost/iris
            type: MODEL
        endpoint:
          type: REST
        name: feature-transformer
        type: TRANSFORMER
      name: transformer
      replicas: 1
```
based on https://github.com/SeldonIO/seldon-core/issues/772 and it works for me on minikube but @lennon310  is seeing 
```
{"type":"ReplicaFailure","status":"True","lastUpdateTime":"2019-08-09T14:48:32Z","lastTransitionTime":"2019-08-09T14:48:32Z","reason":"FailedCreate","message":"pods \"xgboost-transformer-f1b02bb-59c5f6f877-mzlh5\" is forbidden: failed quota: quota-longrunning: must specify cpu,memory"}]}}
```
Presumably the policy is being violated by the initContainer like in https://github.com/kubedb/project/issues/311
