### ISSUE TITLE
consume a Secret in a volume in a Pod

### ISSUE THREAD

**Issue by PrathamSolanki** [SeldonIO/seldon-core#844]
Hi,

My code responsible for generating the predictions has to load the model from `gcs` and thus it needs the appropriate authentication.

I'm trying the approach of using a secret and mounting it as a volume to the container like this:

```
---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: "seldon-deployment"
  namespace: seldon-core-1
spec:
  annotations:
    project_name: Pipeline
    deployment_version: v1
  name: "seldon-deployment"
  oauth_key: oauth-key
  oauth_secret: oauth-secret
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: registrypreprocess
          imagePullPolicy: Always
          name: preprocess
          resources:
            requests:
              memory: 1Mi
        - image: registrytrain
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secret-volume"
          imagePullPolicy: Always
          name: train
        imagePullSecrets:
        - name: gitlab-auth
        volumes:
          - name: secret-volume
            secret:
              secretName: user-gcp-sa
        terminationGracePeriodSeconds: 20
    graph:
      children:
      - name: train
        endpoint:
          type: REST
        type: MODEL
        children: []
      name: preprocess
      endpoint:
        type: REST
      type: MODEL
    name: single-model
    replicas: 1
    annotations:
      predictor_version: v1
```

However, the deployment status fails. When I describe the deployment it shows the following:

```
Status:
  Description:  Cannot find field: secret in message k8s.io.api.core.v1.Volume
  State:        Failed
Events:         <none>
```

I do not really know what I'm doing wrong here.
