### ISSUE TITLE
Rest request  doesn't give the expected answer while using the predict function

### ISSUE THREAD

**Issue by elouayas** [SeldonIO/seldon-core#876]
Everything was perfectly working,

and I had that kind of answer : 
```
{"access_token":"ae1c883c-172e-4619-a99d-a6069b62e53a","token_type":"bearer","expires_in":40689,"scope":"read write"}
{
  "meta": {
    "puid": "797mmjpfmsm2ag3c984jt6b3lg",
    "tags": {
    },
    "routing": {
      "preprocess": -1
    },
    "requestPath": {
      "preprocess": "registry.xxx",
      "train": "registry.xxx"
    },
    "metrics": []
  },
  "strData": "[[3.3211398]]"
}
```

But since this morning I have the following answer while requesting : 

```
{"access_token":"df8a30c6-1f3b-47fc-b9ec-829600d521a9","token_type":"bearer","expires_in":25740,"scope":"read write"}
{
  "meta": {
    "puid": "cd2lm22ck0phbuvp9l5p515s2l",
    "tags": {
    },
    "routing": {
      "preprocess": -1
    },
    "requestPath": {
      "preprocess": "registry.xxx,
      "train": "registry.xxx"
    },
    "metrics": []
  },
  "data": {
    "names": [],
    "tensor": {
      "shape": [0],
      "values": []
    }
  }
}
```

Since that doesn't look like an error outcome I don't really find errors in the logs, and so I don't know how to fix it, or at least where to look at.

I'd highly appreciate any help.

**Comment by cliveseldon** [comment]
Can you tell us what has changed since yesterday?
We did a 0.4.1 release yesterday. Did you upgrade to that?
Can you tell us how you are call predict and what ingress you are using?
Also, what type of model. Providing the yaml of the resource if possible would be useful.

**Comment by elouayas** [comment]
I did no updates, and I am still on 0.2.7

here is my yaml 
```
---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: "seldon-deployment"
  namespace: seldon-core-1
spec:
  annotations:
    project_name: Pipeline
    deployment_version: v1
  name: "seldon-deployment"
  oauth_key: oauth-key
  oauth_secret: oauth-secret
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: registry.xxx
          imagePullPolicy: Always
          name: preprocess
          resources:
            requests:
              memory: 1Mi
        - image: registry.xxx
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secret-volume"
          imagePullPolicy: Always
          name: train
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secret-volume/user-gcp-sa.json"
            - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
              value: "/etc/secret-volume/user-gcp-sa.json"
        imagePullSecrets:
        - name: gitlab-auth
        volumes:
          - name: secret-volume
            volumeSource:
              secret:
                secretName: user-gcp-sa
        terminationGracePeriodSeconds: 20
    graph:
      children:
      - name: train
        endpoint:
          type: REST
        type: MODEL
        children: []
      name: preprocess
      endpoint:
        type: REST
      type: MODEL
    name: single-model
    replicas: 1
    annotations:
      predictor_version: v1
```
I am using a Keras model, and I am on gke.
